/* file: characterized_experience.swift 	 generated: Sat Feb 28 19:28:50 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY characterized_experience
    SUBTYPE OF ( characterized_object, experience );
  END_ENTITY; -- characterized_experience (line:10826 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	characterized_object
    ATTR:  name,	TYPE: label -- EXPLICIT (DYNAMIC)	(AMBIGUOUS/MASKED)
      -- possibly overridden by
          ENTITY: shape_feature_definition_element_relationship,	TYPE: label	(as DERIVED)
          ENTITY: shape_feature_fit_relationship,	TYPE: label	(as DERIVED)
          ENTITY: characterized_representation,	TYPE: label	(as DERIVED)
          ENTITY: shape_feature_definition_relationship,	TYPE: label	(as DERIVED)

    ATTR:  description,	TYPE: OPTIONAL text -- EXPLICIT (DYNAMIC)	(AMBIGUOUS/MASKED)
      -- possibly overridden by
          ENTITY: shape_feature_definition_element_relationship,	TYPE: text	(as DERIVED)
          ENTITY: shape_feature_fit_relationship,	TYPE: text	(as DERIVED)
          ENTITY: characterized_representation,	TYPE: text	(as DERIVED)
          ENTITY: shape_feature_definition_relationship,	TYPE: text	(as DERIVED)


  SUPER- ENTITY(2)	experience
    ATTR:  id,	TYPE: identifier -- EXPLICIT

    ATTR:  name,	TYPE: label -- EXPLICIT	(AMBIGUOUS/MASKED)

    ATTR:  description,	TYPE: OPTIONAL text -- EXPLICIT	(AMBIGUOUS/MASKED)


  ENTITY(SELF)	characterized_experience
    (no local attributes)

*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY characterized_experience
    SUBTYPE OF ( characterized_object, experience );
  END_ENTITY; -- characterized_experience (line:10826 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCHARACTERIZED_OBJECT``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXPERIENCE``

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCHARACTERIZED_EXPERIENCE/PartialEntity``
*/
  public final class eCHARACTERIZED_EXPERIENCE : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eCHARACTERIZED_EXPERIENCE>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eCHARACTERIZED_EXPERIENCE.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eCHARACTERIZED_EXPERIENCE.PartialEntity

    //MARK: SUPERTYPES
    public let super_eCHARACTERIZED_OBJECT: eCHARACTERIZED_OBJECT 	// [1]
    public let super_eEXPERIENCE: eEXPERIENCE 	// [2]
    public var super_eCHARACTERIZED_EXPERIENCE: eCHARACTERIZED_EXPERIENCE { return self } 	// [3]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    // DESCRIPTION: (2 AMBIGUOUS REFs)

    // NAME: (2 AMBIGUOUS REFs)

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXPERIENCE`` )
    public var ID: tIDENTIFIER {
      get {
        let originalValue = super_eEXPERIENCE.partialEntity._id
        let value = SDAI.UNWRAP( tIDENTIFIER( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eEXPERIENCE.partialEntity
        partial._id = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eCHARACTERIZED_EXPERIENCE.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eCHARACTERIZED_OBJECT.self) else { return nil }
      self.super_eCHARACTERIZED_OBJECT = super1

      guard let super2 = complexEntity?.entityReference(eEXPERIENCE.self) else { return nil }
      self.super_eEXPERIENCE = super2

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "CHARACTERIZED_EXPERIENCE", 
        type: self, explicitAttributeCount: 0)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eCHARACTERIZED_OBJECT.self)
      entityDef.add(supertype: eEXPERIENCE.self)
      entityDef.add(supertype: eCHARACTERIZED_EXPERIENCE.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "ID", 
        keyPath: \eCHARACTERIZED_EXPERIENCE.ID, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY characterized_experience
      SUBTYPE OF ( characterized_object, experience );
    END_ENTITY; -- characterized_experience (line:10826 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCHARACTERIZED_EXPERIENCE``
*/
    public final class PartialEntity : SDAI.PartialEntity, SDAI.Initializable.ByVoid, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eCHARACTERIZED_EXPERIENCE.self
      }

      //ATTRIBUTES
      // (no local attributes)

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init() {
        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        self.init( )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 0
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        self.init( )
      }
    }
  }
}
