/* file: edge_based_topological_representation_with_length_constraint_items.swift 	 generated: Fri Feb 27 19:08:27 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE edge_based_topological_representation_with_length_constraint_items = SELECT
    ( connected_edge_set (*ENTITY*),
     path (*ENTITY*),
     vertex_point (*ENTITY*) );
  END_TYPE; -- edge_based_topological_representation_with_length_constraint_items (line:2961 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES FOR SELECT
/*
  CASE: connected_edge_set (*ENTITY*):
  ATTR:  parent_edge_set: connected_edge_set
  ATTR:  permanent_aggregate_id: identifier
  ATTR:  ces_edges: SET [1 : ?] OF edge
  ATTR:  permanent_id: identifier
  ATTR:  name: label

  CASE: path (*ENTITY*):
  ATTR:  ne:  (AMBIGUOUS (CASE LEVEL))
  ATTR:  orientation: BOOLEAN
  ATTR:  permanent_aggregate_id: identifier
  ATTR:  parent_path: path
  ATTR:  path_element: path
  ATTR:  edge_list: LIST [1 : ?] OF UNIQUE oriented_edge
  ATTR:  permanent_id: identifier
  ATTR:  name: label

  CASE: vertex_point (*ENTITY*):
  ATTR:  permanent_aggregate_id: identifier
  ATTR:  vertex_geometry: point
  ATTR:  permanent_id: identifier
  ATTR:  name: label
  ATTR:  dim: dimension_count

*/

/** SELECT type
- EXPRESS source code:
```express
  TYPE edge_based_topological_representation_with_length_constraint_items = SELECT
    ( connected_edge_set (*ENTITY*),
     path (*ENTITY*),
     vertex_point (*ENTITY*) );
  END_TYPE; -- edge_based_topological_representation_with_length_constraint_items (line:2961 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS : SDAI.Value, 
    TypeHierarchy.sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS__TypeBehavior {

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    @_documentation(visibility:public)
    case _CONNECTED_EDGE_SET(eCONNECTED_EDGE_SET.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    @_documentation(visibility:public)
    case _PATH(ePATH.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    @_documentation(visibility:public)
    case _VERTEX_POINT(eVERTEX_POINT.PRef)	// (ENTITY)

    //MARK: - CONSTRUCTORS
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) { self = fundamental }

    /// initialize from the underlying type value
    public init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?){
      return nil
    }

    /// initialize from complex entity
    public init?(possiblyFrom complex: SDAI.ComplexEntity?) {
      guard let complex = complex else { return nil }

      if let base = complex.entityReference(eCONNECTED_EDGE_SET.self) {self = ._CONNECTED_EDGE_SET(base.pRef) }
      else if let base = complex.entityReference(ePATH.self) {self = ._PATH(base.pRef) }
      else if let base = complex.entityReference(eVERTEX_POINT.self) {self = ._VERTEX_POINT(base.pRef) }
      else { return nil }
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let select = generic else { return nil }

      if let fundamental = select as? Self {
        self.init(fundamental: fundamental)
      }
      else if let base = eCONNECTED_EDGE_SET.PRef.convert(fromGeneric: select) {
        self = ._CONNECTED_EDGE_SET(base)
      }
      else if let base = ePATH.PRef.convert(fromGeneric: select) {
        self = ._PATH(base)
      }
      else if let base = eVERTEX_POINT.PRef.convert(fromGeneric: select) {
        self = ._VERTEX_POINT(base)
      }
      else { return nil }
    }

    // Initializable.ByP21Parameter
    public static let bareTypeName: String = 
      "EDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS"

    /// initialize from ISO 10303-21 exchange structure typed parameters
    public init?(
      p21typedParam: P21Decode.ExchangeStructure.TypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      guard let keyword = p21typedParam.keyword.asStandardKeyword else { exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"; return nil }

      switch(keyword) {
      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public init?(
      p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      switch p21untypedParam {
      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantEntityName(let name):
          guard let entity = exchangeStructure.resolve(constantEntityName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: entity.complexEntity)

        case .entityInstanceName(let name):
          guard let complex = exchangeStructure.resolve(entityInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: complex)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
          return nil
        }

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init?(p21omittedParamfrom exchangeStructure: P21Decode.ExchangeStructure) {
      return nil
    }


    //MARK: - ENTITY UNDERLYING TYPE REFERENCES
    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_ePATH: ePATH.PRef {
      switch self {
      case ._PATH(let entity): return entity
      default: return ePATH.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_eTOPOLOGICAL_REPRESENTATION_ITEM: eTOPOLOGICAL_REPRESENTATION_ITEM.PRef {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return eTOPOLOGICAL_REPRESENTATION_ITEM.PRef(entity.eval?.super_eTOPOLOGICAL_REPRESENTATION_ITEM)
      case ._PATH(let entity): return eTOPOLOGICAL_REPRESENTATION_ITEM.PRef(entity.eval?.super_eTOPOLOGICAL_REPRESENTATION_ITEM)
      case ._VERTEX_POINT(let entity): return eTOPOLOGICAL_REPRESENTATION_ITEM.PRef(entity.eval?.super_eTOPOLOGICAL_REPRESENTATION_ITEM)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_eVERTEX: eVERTEX.PRef {
      switch self {
      case ._VERTEX_POINT(let entity): return eVERTEX.PRef(entity.eval?.super_eVERTEX)
      default: return eVERTEX.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM.PRef {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return eREPRESENTATION_ITEM.PRef(entity.eval?.super_eREPRESENTATION_ITEM)
      case ._PATH(let entity): return eREPRESENTATION_ITEM.PRef(entity.eval?.super_eREPRESENTATION_ITEM)
      case ._VERTEX_POINT(let entity): return eREPRESENTATION_ITEM.PRef(entity.eval?.super_eREPRESENTATION_ITEM)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_eVERTEX_POINT: eVERTEX_POINT.PRef {
      switch self {
      case ._VERTEX_POINT(let entity): return entity
      default: return eVERTEX_POINT.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_eCONNECTED_EDGE_SET: eCONNECTED_EDGE_SET.PRef {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity
      default: return eCONNECTED_EDGE_SET.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    public var super_eGEOMETRIC_REPRESENTATION_ITEM: eGEOMETRIC_REPRESENTATION_ITEM.PRef {
      switch self {
      case ._VERTEX_POINT(let entity): return eGEOMETRIC_REPRESENTATION_ITEM.PRef(entity.eval?.super_eGEOMETRIC_REPRESENTATION_ITEM)
      default: return eGEOMETRIC_REPRESENTATION_ITEM.PRef(nil)
      }
    }


    //MARK: - ENTITY ATTRIBUTE REFERENCES
    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` )
    public var PARENT_EDGE_SET: eCONNECTED_EDGE_SET.PRef?  {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.PARENT_EDGE_SET
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    public var ORIENTATION: SDAI.BOOLEAN?  {
      switch self {
      case ._PATH(let entity): return entity.ORIENTATION
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` )
    public var PERMANENT_AGGREGATE_ID: tIDENTIFIER?  {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.PERMANENT_AGGREGATE_ID
      case ._PATH(let entity): return entity.PERMANENT_AGGREGATE_ID
      case ._VERTEX_POINT(let entity): return entity.PERMANENT_AGGREGATE_ID
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    public var PARENT_PATH: ePATH.PRef?  {
      switch self {
      case ._PATH(let entity): return entity.PARENT_PATH
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    public var PATH_ELEMENT: ePATH.PRef?  {
      switch self {
      case ._PATH(let entity): return entity.PATH_ELEMENT
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    public var EDGE_LIST: (SDAI.LIST_UNIQUE<eORIENTED_EDGE.PRef>/*[1:(nil as SDAI.INTEGER?)]*/ )?  {
      switch self {
      case ._PATH(let entity): return entity.EDGE_LIST
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` )
    public var VERTEX_GEOMETRY: ePOINT.PRef?  {
      switch self {
      case ._VERTEX_POINT(let entity): return entity.VERTEX_GEOMETRY
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` )
    public var CES_EDGES: (SDAI.SET<eEDGE.PRef>/*[1:(nil as SDAI.INTEGER?)]*/ )?  {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.CES_EDGES
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` )
    public var PERMANENT_ID: tIDENTIFIER?  {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.PERMANENT_ID
      case ._PATH(let entity): return entity.PERMANENT_ID
      case ._VERTEX_POINT(let entity): return entity.PERMANENT_ID
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` )
    public var NAME: tLABEL?  {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.NAME
      case ._PATH(let entity): return entity.NAME
      case ._VERTEX_POINT(let entity): return entity.NAME
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` )
    public var DIM: tDIMENSION_COUNT?  {
      switch self {
      case ._VERTEX_POINT(let entity): return entity.DIM
      default: return nil
      }
    }


    //MARK: - SDAI.Value
    public func isValueEqual<T: SDAI.Value>(to rhs: T) -> Bool {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.value.isValueEqual(to: rhs)
      case ._PATH(let selection): return selection.value.isValueEqual(to: rhs)
      case ._VERTEX_POINT(let selection): return selection.value.isValueEqual(to: rhs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?) -> Bool? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._PATH(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._VERTEX_POINT(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      }
    }

    public func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._PATH(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._VERTEX_POINT(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }
    }

    public func isValueEqual<T: SDAI.Value>(to rhs: T, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._PATH(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._VERTEX_POINT(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._PATH(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._VERTEX_POINT(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      }
    }


    //MARK: SDAIGenericTypeBase
    public func copy() -> Self {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return ._CONNECTED_EDGE_SET(selection.copy())
      case ._PATH(let selection): return ._PATH(selection.copy())
      case ._VERTEX_POINT(let selection): return ._VERTEX_POINT(selection.copy())
      }
    }

    //MARK: SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members: Set<SDAI.STRING> = [SDAI.STRING(Self.typeName)]
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): members.formUnion(selection.typeMembers)
      case ._PATH(let selection): members.formUnion(selection.typeMembers)
      case ._VERTEX_POINT(let selection): members.formUnion(selection.typeMembers)
      }
      return members
    }

    public var entityReference: SDAI.EntityReference? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.entityReference
      case ._PATH(let selection): return selection.entityReference
      case ._VERTEX_POINT(let selection): return selection.entityReference
      }
    }
    public var stringValue: SDAI.STRING? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.stringValue
      case ._PATH(let selection): return selection.stringValue
      case ._VERTEX_POINT(let selection): return selection.stringValue
      }
    }
    public var binaryValue: SDAI.BINARY? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.binaryValue
      case ._PATH(let selection): return selection.binaryValue
      case ._VERTEX_POINT(let selection): return selection.binaryValue
      }
    }
    public var logicalValue: SDAI.LOGICAL? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.logicalValue
      case ._PATH(let selection): return selection.logicalValue
      case ._VERTEX_POINT(let selection): return selection.logicalValue
      }
    }
    public var booleanValue: SDAI.BOOLEAN? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.booleanValue
      case ._PATH(let selection): return selection.booleanValue
      case ._VERTEX_POINT(let selection): return selection.booleanValue
      }
    }
    public var numberValue: SDAI.NUMBER? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.numberValue
      case ._PATH(let selection): return selection.numberValue
      case ._VERTEX_POINT(let selection): return selection.numberValue
      }
    }
    public var realValue: SDAI.REAL? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.realValue
      case ._PATH(let selection): return selection.realValue
      case ._VERTEX_POINT(let selection): return selection.realValue
      }
    }
    public var integerValue: SDAI.INTEGER? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.integerValue
      case ._PATH(let selection): return selection.integerValue
      case ._VERTEX_POINT(let selection): return selection.integerValue
      }
    }
    public var genericEnumValue: SDAI.GenericEnumValue? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.genericEnumValue
      case ._PATH(let selection): return selection.genericEnumValue
      case ._VERTEX_POINT(let selection): return selection.genericEnumValue
      }
    }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._PATH(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._VERTEX_POINT(let selection): return selection.arrayOptionalValue(elementType:elementType)
      }
    }
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.arrayValue(elementType:elementType)
      case ._PATH(let selection): return selection.arrayValue(elementType:elementType)
      case ._VERTEX_POINT(let selection): return selection.arrayValue(elementType:elementType)
      }
    }
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.listValue(elementType:elementType)
      case ._PATH(let selection): return selection.listValue(elementType:elementType)
      case ._VERTEX_POINT(let selection): return selection.listValue(elementType:elementType)
      }
    }
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.bagValue(elementType:elementType)
      case ._PATH(let selection): return selection.bagValue(elementType:elementType)
      case ._VERTEX_POINT(let selection): return selection.bagValue(elementType:elementType)
      }
    }
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.setValue(elementType:elementType)
      case ._PATH(let selection): return selection.setValue(elementType:elementType)
      case ._VERTEX_POINT(let selection): return selection.setValue(elementType:elementType)
      }
    }
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? {
      switch self {
      case ._CONNECTED_EDGE_SET(let selection): return selection.enumValue(enumType:enumType)
      case ._PATH(let selection): return selection.enumValue(enumType:enumType)
      case ._VERTEX_POINT(let selection): return selection.enumValue(enumType:enumType)
      }
    }

    //MARK: SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.EDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS"
    public var asFundamentalType: FundamentalType { return self }

    //MARK: SDAI.EntityReferenceYielding
    public var entityReferences: AnySequence<SDAI.EntityReference> {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.entityReferences
      case ._PATH(let entity): return entity.entityReferences
      case ._VERTEX_POINT(let entity): return entity.entityReferences
      }
    }

    public var persistentEntityReferences: AnySequence<SDAI.GenericPersistentEntityReference> {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): return entity.persistentEntityReferences
      case ._PATH(let entity): return entity.persistentEntityReferences
      case ._VERTEX_POINT(let entity): return entity.persistentEntityReferences
      }
    }

    public func isHolding(entityReference: SDAI.EntityReference) -> Bool {
      switch self {
      case ._CONNECTED_EDGE_SET(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._PATH(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._VERTEX_POINT(let entity): 
        return entity.isHolding(entityReference: entityReference)
      }
    }


    //MARK: SDAIAggregationBehavior
    public var aggregationHiBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationHiIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationSize: Int? {
      switch self {
      default: return nil
      }
    }

    //MARK: WHERE RULE VALIDATION (SELECT TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      var result: SDAI.WhereRuleValidationRecords = [:]
      switch instance {
      case ._CONNECTED_EDGE_SET(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eCONNECTED_EDGE_SET.validateWhereRules(instance: entity.eval, 
        prefix:prefix + "\\\(entity)")
      case ._PATH(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = ePATH.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case ._VERTEX_POINT(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eVERTEX_POINT.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case nil: break
      }

      return result
    }

  }

}


//MARK: - SELECT TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
public protocol sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS__TypeBehavior: 
  SDAI.SelectType {
  //MARK: GROUP REFERENCES
  var super_ePATH: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePATH.PRef { get }
  var super_eTOPOLOGICAL_REPRESENTATION_ITEM: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTOPOLOGICAL_REPRESENTATION_ITEM.PRef { get }
  var super_eVERTEX: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX.PRef { get }
  var super_eREPRESENTATION_ITEM: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eREPRESENTATION_ITEM.PRef { get }
  var super_eVERTEX_POINT: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX_POINT.PRef { get }
  var super_eCONNECTED_EDGE_SET: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eCONNECTED_EDGE_SET.PRef { get }
  var super_eGEOMETRIC_REPRESENTATION_ITEM: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eGEOMETRIC_REPRESENTATION_ITEM.PRef { get }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var PARENT_EDGE_SET: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eCONNECTED_EDGE_SET.PRef?  { get }
  var ORIENTATION: SDAI.BOOLEAN?  { get }
  var PERMANENT_AGGREGATE_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var PARENT_PATH: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePATH.PRef?  { get }
  var PATH_ELEMENT: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePATH.PRef?  { get }
  var EDGE_LIST: (SDAI.LIST_UNIQUE<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORIENTED_EDGE.PRef>/*[1:
    (nil as SDAI.INTEGER?)]*/ )?  { get }
  var VERTEX_GEOMETRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePOINT.PRef?  { get }
  var CES_EDGES: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEDGE.PRef>/*[1:(nil as SDAI.INTEGER?)]*/ )?  { get }
  var PERMANENT_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var DIM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tDIMENSION_COUNT?  { get }
}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS__Subtype: 
  sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS__TypeBehavior, SDAI.DefinedType
where Supertype: sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS__TypeBehavior
{}
}

public extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy.sEDGE_BASED_TOPOLOGICAL_REPRESENTATION_WITH_LENGTH_CONSTRAINT_ITEMS__Subtype {
  //MARK: CONSTRUCTORS
  /// initialize SELECT subtype from complex entity
  init?(possiblyFrom complex: SDAI.ComplexEntity?) {
    self.init(fundamental: FundamentalType(possiblyFrom: complex))
  }

  /// initialize SELECT subtype from the underlying type value
  init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?) {
    self.init(fundamental: FundamentalType(possiblyFrom: underlyingType))
  }

  /// initialize SELECT subtype from SDAI generic type value
  init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
    self.init(fundamental: FundamentalType.convert(fromGeneric: generic))
  }

  //MARK: GROUP REFERENCES
  var super_ePATH: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePATH.PRef { rep.super_ePATH }
  var super_eTOPOLOGICAL_REPRESENTATION_ITEM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTOPOLOGICAL_REPRESENTATION_ITEM.PRef { rep.super_eTOPOLOGICAL_REPRESENTATION_ITEM }
  var super_eVERTEX: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX.PRef { rep.super_eVERTEX }
  var super_eREPRESENTATION_ITEM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eREPRESENTATION_ITEM.PRef { rep.super_eREPRESENTATION_ITEM }
  var super_eVERTEX_POINT: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX_POINT.PRef { rep.super_eVERTEX_POINT }
  var super_eCONNECTED_EDGE_SET: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eCONNECTED_EDGE_SET.PRef { rep.super_eCONNECTED_EDGE_SET }
  var super_eGEOMETRIC_REPRESENTATION_ITEM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eGEOMETRIC_REPRESENTATION_ITEM.PRef { rep.super_eGEOMETRIC_REPRESENTATION_ITEM }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var PARENT_EDGE_SET: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eCONNECTED_EDGE_SET.PRef?  { rep.PARENT_EDGE_SET }
  var ORIENTATION: SDAI.BOOLEAN?  { rep.ORIENTATION }
  var PERMANENT_AGGREGATE_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.PERMANENT_AGGREGATE_ID }
  var PARENT_PATH: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePATH.PRef?  { rep.PARENT_PATH }
  var PATH_ELEMENT: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePATH.PRef?  { rep.PATH_ELEMENT }
  var EDGE_LIST: (SDAI.LIST_UNIQUE<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORIENTED_EDGE.PRef>/*[1:
    (nil as SDAI.INTEGER?)]*/ )?  { rep.EDGE_LIST }
  var VERTEX_GEOMETRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePOINT.PRef?  { rep.VERTEX_GEOMETRY }
  var CES_EDGES: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEDGE.PRef>/*[1:(nil as SDAI.INTEGER?)]*/ )?  { rep.CES_EDGES }
  var PERMANENT_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.PERMANENT_ID }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.NAME }
  var DIM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tDIMENSION_COUNT?  { rep.DIM }
}

