/* file: exchange_identification_context_select.swift 	 generated: Fri Mar  6 17:48:00 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE exchange_identification_context_select = SELECT
    ( identification_assignment (*ENTITY*),
     organization (*ENTITY*) );
  END_TYPE; -- exchange_identification_context_select (line:3391 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES FOR SELECT
/*
  CASE: identification_assignment (*ENTITY*):
  ATTR:  role: identification_role
  ATTR:  items:  (AMBIGUOUS (CASE LEVEL))
  ATTR:  assigned_id: identifier
  ATTR:  source: external_source

  CASE: organization (*ENTITY*):
  ATTR:  description: text
  ATTR:  id: identifier
  ATTR:  name: label

*/

/** SELECT type
- EXPRESS source code:
```express
  TYPE exchange_identification_context_select = SELECT
    ( identification_assignment (*ENTITY*),
     organization (*ENTITY*) );
  END_TYPE; -- exchange_identification_context_select (line:3391 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT : SDAI.Value, TypeHierarchy.sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT__TypeBehavior {

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eIDENTIFICATION_ASSIGNMENT`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    @_documentation(visibility:public)
    case _IDENTIFICATION_ASSIGNMENT(eIDENTIFICATION_ASSIGNMENT.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    @_documentation(visibility:public)
    case _ORGANIZATION(eORGANIZATION.PRef)	// (ENTITY)

    //MARK: - CONSTRUCTORS
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) { self = fundamental }

    /// initialize from the underlying type value
    public init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?){
      return nil
    }

    /// initialize from complex entity
    public init?(possiblyFrom complex: SDAI.ComplexEntity?) {
      guard let complex = complex else { return nil }

      if let base = complex.entityReference(eIDENTIFICATION_ASSIGNMENT.self) {self = ._IDENTIFICATION_ASSIGNMENT(base.pRef) }
      else if let base = complex.entityReference(eORGANIZATION.self) {self = ._ORGANIZATION(base.pRef) }
      else { return nil }
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let select = generic else { return nil }

      if let fundamental = select as? Self {
        self.init(fundamental: fundamental)
      }
      else if let base = eIDENTIFICATION_ASSIGNMENT.PRef.convert(fromGeneric: select) {
        self = ._IDENTIFICATION_ASSIGNMENT(base)
      }
      else if let base = eORGANIZATION.PRef.convert(fromGeneric: select) {
        self = ._ORGANIZATION(base)
      }
      else { return nil }
    }

    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "EXCHANGE_IDENTIFICATION_CONTEXT_SELECT"

    /// initialize from ISO 10303-21 exchange structure typed parameters
    public init?(
      p21typedParam: P21Decode.ExchangeStructure.TypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      guard let keyword = p21typedParam.keyword.asStandardKeyword else { exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"; return nil }

      switch(keyword) {
      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public init?(
      p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      switch p21untypedParam {
      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantEntityName(let name):
          guard let entity = exchangeStructure.resolve(constantEntityName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: entity.complexEntity)

        case .entityInstanceName(let name):
          guard let complex = exchangeStructure.resolve(entityInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: complex)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
          return nil
        }

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init?(p21omittedParamfrom exchangeStructure: P21Decode.ExchangeStructure) {
      return nil
    }


    //MARK: - ENTITY UNDERLYING TYPE REFERENCES
    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    public var super_eIDENTIFICATION_ASSIGNMENT: eIDENTIFICATION_ASSIGNMENT.PRef {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): return entity
      default: return eIDENTIFICATION_ASSIGNMENT.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    public var super_eORGANIZATION: eORGANIZATION.PRef {
      switch self {
      case ._ORGANIZATION(let entity): return entity
      default: return eORGANIZATION.PRef(nil)
      }
    }


    //MARK: - ENTITY ATTRIBUTE REFERENCES
    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` )
    public var DESCRIPTION: tTEXT?  {
      switch self {
      case ._ORGANIZATION(let entity): return entity.DESCRIPTION
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eIDENTIFICATION_ASSIGNMENT`` )
    public var ROLE: eIDENTIFICATION_ROLE.PRef?  {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): return entity.ROLE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eIDENTIFICATION_ASSIGNMENT`` )
    public var ASSIGNED_ID: tIDENTIFIER?  {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): return entity.ASSIGNED_ID
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eIDENTIFICATION_ASSIGNMENT`` )
    public var SOURCE: eEXTERNAL_SOURCE.PRef?  {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): return entity.SOURCE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` )
    public var ID: tIDENTIFIER?  {
      switch self {
      case ._ORGANIZATION(let entity): return entity.ID
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` )
    public var NAME: tLABEL?  {
      switch self {
      case ._ORGANIZATION(let entity): return entity.NAME
      default: return nil
      }
    }


    //MARK: - SDAI.Value
    public func isValueEqual<T: SDAI.Value>(to rhs: T) -> Bool {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.value.isValueEqual(to: rhs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqual(to: rhs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?) -> Bool? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      }
    }

    public func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._ORGANIZATION(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }
    }

    public func isValueEqual<T: SDAI.Value>(to rhs: T, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      }
    }


    //MARK: SDAIGenericTypeBase
    public func copy() -> Self {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return ._IDENTIFICATION_ASSIGNMENT(selection.copy())
      case ._ORGANIZATION(let selection): return ._ORGANIZATION(selection.copy())
      }
    }

    //MARK: SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members: Set<SDAI.STRING> = [SDAI.STRING(Self.typeName)]
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): members.formUnion(selection.typeMembers)
      case ._ORGANIZATION(let selection): members.formUnion(selection.typeMembers)
      }
      return members
    }

    public var entityReference: SDAI.EntityReference? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.entityReference
      case ._ORGANIZATION(let selection): return selection.entityReference
      }
    }
    public var stringValue: SDAI.STRING? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.stringValue
      case ._ORGANIZATION(let selection): return selection.stringValue
      }
    }
    public var binaryValue: SDAI.BINARY? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.binaryValue
      case ._ORGANIZATION(let selection): return selection.binaryValue
      }
    }
    public var logicalValue: SDAI.LOGICAL? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.logicalValue
      case ._ORGANIZATION(let selection): return selection.logicalValue
      }
    }
    public var booleanValue: SDAI.BOOLEAN? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.booleanValue
      case ._ORGANIZATION(let selection): return selection.booleanValue
      }
    }
    public var numberValue: SDAI.NUMBER? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.numberValue
      case ._ORGANIZATION(let selection): return selection.numberValue
      }
    }
    public var realValue: SDAI.REAL? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.realValue
      case ._ORGANIZATION(let selection): return selection.realValue
      }
    }
    public var integerValue: SDAI.INTEGER? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.integerValue
      case ._ORGANIZATION(let selection): return selection.integerValue
      }
    }
    public var genericEnumValue: SDAI.GenericEnumValue? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.genericEnumValue
      case ._ORGANIZATION(let selection): return selection.genericEnumValue
      }
    }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.arrayOptionalValue(elementType:elementType)
      }
    }
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.arrayValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.arrayValue(elementType:elementType)
      }
    }
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.listValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.listValue(elementType:elementType)
      }
    }
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.bagValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.bagValue(elementType:elementType)
      }
    }
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.setValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.setValue(elementType:elementType)
      }
    }
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let selection): return selection.enumValue(enumType:enumType)
      case ._ORGANIZATION(let selection): return selection.enumValue(enumType:enumType)
      }
    }

    //MARK: SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.EXCHANGE_IDENTIFICATION_CONTEXT_SELECT"
    public var asFundamentalType: FundamentalType { return self }

    //MARK: SDAI.EntityReferenceYielding
    public var entityReferences: AnySequence<SDAI.EntityReference> {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): return entity.entityReferences
      case ._ORGANIZATION(let entity): return entity.entityReferences
      }
    }

    public var persistentEntityReferences: AnySequence<SDAI.GenericPersistentEntityReference> {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): return entity.persistentEntityReferences
      case ._ORGANIZATION(let entity): return entity.persistentEntityReferences
      }
    }

    public func isHolding(entityReference: SDAI.EntityReference) -> Bool {
      switch self {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._ORGANIZATION(let entity): 
        return entity.isHolding(entityReference: entityReference)
      }
    }


    //MARK: SDAIAggregationBehavior
    public var aggregationHiBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationHiIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationSize: Int? {
      switch self {
      default: return nil
      }
    }

    //MARK: WHERE RULE VALIDATION (SELECT TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      var result: SDAI.WhereRuleValidationRecords = [:]
      switch instance {
      case ._IDENTIFICATION_ASSIGNMENT(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eIDENTIFICATION_ASSIGNMENT.validateWhereRules(instance: entity.eval, 
        prefix:prefix + "\\\(entity)")
      case ._ORGANIZATION(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eORGANIZATION.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case nil: break
      }

      return result
    }

  }

}


//MARK: - SELECT TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
public protocol sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT__TypeBehavior: SDAI.SelectType {
  //MARK: GROUP REFERENCES
  var super_eIDENTIFICATION_ASSIGNMENT: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eIDENTIFICATION_ASSIGNMENT.PRef { get }
  var super_eORGANIZATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef { get }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var DESCRIPTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { get }
  var ROLE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eIDENTIFICATION_ROLE.PRef?  { get }
  var ASSIGNED_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var SOURCE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEXTERNAL_SOURCE.PRef?  { get }
  var ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT__Subtype: 
  sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT__TypeBehavior, SDAI.DefinedType
where Supertype: sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT__TypeBehavior
{}
}

public extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy.sEXCHANGE_IDENTIFICATION_CONTEXT_SELECT__Subtype {
  //MARK: CONSTRUCTORS
  /// initialize SELECT subtype from complex entity
  init?(possiblyFrom complex: SDAI.ComplexEntity?) {
    self.init(fundamental: FundamentalType(possiblyFrom: complex))
  }

  /// initialize SELECT subtype from the underlying type value
  init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?) {
    self.init(fundamental: FundamentalType(possiblyFrom: underlyingType))
  }

  /// initialize SELECT subtype from SDAI generic type value
  init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
    self.init(fundamental: FundamentalType.convert(fromGeneric: generic))
  }

  //MARK: GROUP REFERENCES
  var super_eIDENTIFICATION_ASSIGNMENT: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eIDENTIFICATION_ASSIGNMENT.PRef { rep.super_eIDENTIFICATION_ASSIGNMENT }
  var super_eORGANIZATION: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef { rep.super_eORGANIZATION }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var DESCRIPTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { rep.DESCRIPTION }
  var ROLE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eIDENTIFICATION_ROLE.PRef?  { rep.ROLE }
  var ASSIGNED_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.ASSIGNED_ID }
  var SOURCE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEXTERNAL_SOURCE.PRef?  { rep.SOURCE }
  var ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.ID }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.NAME }
}

