/* file: experience_type_item.swift 	 generated: Fri Mar  6 17:48:00 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE experience_type_item = SELECT
    ( action_method (*ENTITY*),
     action_resource_requirement (*ENTITY*),
     executed_action (*ENTITY*),
     organization (*ENTITY*),
     person (*ENTITY*),
     person_and_organization (*ENTITY*) );
  END_TYPE; -- experience_type_item (line:3633 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES FOR SELECT
/*
  CASE: action_method (*ENTITY*):
  ATTR:  description: text *** Multiple Select Case Sources ***
  ATTR:  configuration_type: STRING
  ATTR:  purpose: text
  ATTR:  usage_constraints: SET [1 : ?] OF document_usage_constraint
  ATTR:  number_of_elements: count_measure
  ATTR:  consequence: text
  ATTR:  documents: SET [1 : ?] OF document
  ATTR:  name: label *** Multiple Select Case Sources ***
  ATTR:  inheritance_type: STRING

  CASE: action_resource_requirement (*ENTITY*):
  ATTR:  description: text *** Multiple Select Case Sources ***
  ATTR:  operations: SET [1 : ?] OF characterized_action_definition
  ATTR:  resources: SET [1 : ?] OF action_resource
  ATTR:  kind: resource_requirement_type
  ATTR:  name: label *** Multiple Select Case Sources ***

  CASE: executed_action (*ENTITY*):
  ATTR:  description: text *** Multiple Select Case Sources ***
  ATTR:  directive: action_directive
  ATTR:  chosen_method: action_method
  ATTR:  id: identifier *** Multiple Select Case Sources ***
  ATTR:  name: label *** Multiple Select Case Sources ***

  CASE: organization (*ENTITY*):
  ATTR:  description: text *** Multiple Select Case Sources ***
  ATTR:  id: identifier *** Multiple Select Case Sources ***
  ATTR:  name: label *** Multiple Select Case Sources ***

  CASE: person (*ENTITY*):
  ATTR:  middle_names: LIST [1 : ?] OF label
  ATTR:  suffix_titles: LIST [1 : ?] OF label
  ATTR:  last_name: label
  ATTR:  first_name: label
  ATTR:  id: identifier *** Multiple Select Case Sources ***
  ATTR:  prefix_titles: LIST [1 : ?] OF label

  CASE: person_and_organization (*ENTITY*):
  ATTR:  description: text *** Multiple Select Case Sources ***
  ATTR:  the_person: person
  ATTR:  the_organization: organization
  ATTR:  name: label *** Multiple Select Case Sources ***

*/

/** SELECT type
- EXPRESS source code:
```express
  TYPE experience_type_item = SELECT
    ( action_method (*ENTITY*),
     action_resource_requirement (*ENTITY*),
     executed_action (*ENTITY*),
     organization (*ENTITY*),
     person (*ENTITY*),
     person_and_organization (*ENTITY*) );
  END_TYPE; -- experience_type_item (line:3633 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum sEXPERIENCE_TYPE_ITEM : SDAI.Value, TypeHierarchy.sEXPERIENCE_TYPE_ITEM__TypeBehavior {

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    @_documentation(visibility:public)
    case _ACTION_METHOD(eACTION_METHOD.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_RESOURCE_REQUIREMENT`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    @_documentation(visibility:public)
    case _ACTION_RESOURCE_REQUIREMENT(eACTION_RESOURCE_REQUIREMENT.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXECUTED_ACTION`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    @_documentation(visibility:public)
    case _EXECUTED_ACTION(eEXECUTED_ACTION.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    @_documentation(visibility:public)
    case _ORGANIZATION(eORGANIZATION.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    @_documentation(visibility:public)
    case _PERSON(ePERSON.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON_AND_ORGANIZATION`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    @_documentation(visibility:public)
    case _PERSON_AND_ORGANIZATION(ePERSON_AND_ORGANIZATION.PRef)	// (ENTITY)

    //MARK: - CONSTRUCTORS
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) { self = fundamental }

    /// initialize from the underlying type value
    public init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?){
      return nil
    }

    /// initialize from complex entity
    public init?(possiblyFrom complex: SDAI.ComplexEntity?) {
      guard let complex = complex else { return nil }

      if let base = complex.entityReference(eACTION_METHOD.self) {self = ._ACTION_METHOD(base.pRef) }
      else if let base = complex.entityReference(eACTION_RESOURCE_REQUIREMENT.self) {self = ._ACTION_RESOURCE_REQUIREMENT(base.pRef) }
      else if let base = complex.entityReference(eEXECUTED_ACTION.self) {self = ._EXECUTED_ACTION(base.pRef) }
      else if let base = complex.entityReference(eORGANIZATION.self) {self = ._ORGANIZATION(base.pRef) }
      else if let base = complex.entityReference(ePERSON.self) {self = ._PERSON(base.pRef) }
      else if let base = complex.entityReference(ePERSON_AND_ORGANIZATION.self) {self = ._PERSON_AND_ORGANIZATION(base.pRef) }
      else { return nil }
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let select = generic else { return nil }

      if let fundamental = select as? Self {
        self.init(fundamental: fundamental)
      }
      else if let base = eACTION_METHOD.PRef.convert(fromGeneric: select) {
        self = ._ACTION_METHOD(base)
      }
      else if let base = eACTION_RESOURCE_REQUIREMENT.PRef.convert(fromGeneric: select) {
        self = ._ACTION_RESOURCE_REQUIREMENT(base)
      }
      else if let base = eEXECUTED_ACTION.PRef.convert(fromGeneric: select) {
        self = ._EXECUTED_ACTION(base)
      }
      else if let base = eORGANIZATION.PRef.convert(fromGeneric: select) {
        self = ._ORGANIZATION(base)
      }
      else if let base = ePERSON.PRef.convert(fromGeneric: select) {
        self = ._PERSON(base)
      }
      else if let base = ePERSON_AND_ORGANIZATION.PRef.convert(fromGeneric: select) {
        self = ._PERSON_AND_ORGANIZATION(base)
      }
      else { return nil }
    }

    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "EXPERIENCE_TYPE_ITEM"

    /// initialize from ISO 10303-21 exchange structure typed parameters
    public init?(
      p21typedParam: P21Decode.ExchangeStructure.TypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      guard let keyword = p21typedParam.keyword.asStandardKeyword else { exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"; return nil }

      switch(keyword) {
      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public init?(
      p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      switch p21untypedParam {
      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantEntityName(let name):
          guard let entity = exchangeStructure.resolve(constantEntityName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: entity.complexEntity)

        case .entityInstanceName(let name):
          guard let complex = exchangeStructure.resolve(entityInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: complex)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
          return nil
        }

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init?(p21omittedParamfrom exchangeStructure: P21Decode.ExchangeStructure) {
      return nil
    }


    //MARK: - ENTITY UNDERLYING TYPE REFERENCES
    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_eACTION_RESOURCE_REQUIREMENT: eACTION_RESOURCE_REQUIREMENT.PRef {
      switch self {
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity
      default: return eACTION_RESOURCE_REQUIREMENT.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_ePERSON: ePERSON.PRef {
      switch self {
      case ._PERSON(let entity): return entity
      default: return ePERSON.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_eACTION_METHOD: eACTION_METHOD.PRef {
      switch self {
      case ._ACTION_METHOD(let entity): return entity
      default: return eACTION_METHOD.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_eEXECUTED_ACTION: eEXECUTED_ACTION.PRef {
      switch self {
      case ._EXECUTED_ACTION(let entity): return entity
      default: return eEXECUTED_ACTION.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_eORGANIZATION: eORGANIZATION.PRef {
      switch self {
      case ._ORGANIZATION(let entity): return entity
      default: return eORGANIZATION.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_ePERSON_AND_ORGANIZATION: ePERSON_AND_ORGANIZATION.PRef {
      switch self {
      case ._PERSON_AND_ORGANIZATION(let entity): return entity
      default: return ePERSON_AND_ORGANIZATION.PRef(nil)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    public var super_eACTION: eACTION.PRef {
      switch self {
      case ._EXECUTED_ACTION(let entity): return eACTION.PRef(entity.eval?.super_eACTION)
      default: return eACTION.PRef(nil)
      }
    }


    //MARK: - ENTITY ATTRIBUTE REFERENCES
    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_RESOURCE_REQUIREMENT`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXECUTED_ACTION`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON_AND_ORGANIZATION`` )
    public var DESCRIPTION: tTEXT?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.DESCRIPTION
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.DESCRIPTION
      case ._EXECUTED_ACTION(let entity): return entity.DESCRIPTION
      case ._ORGANIZATION(let entity): return entity.DESCRIPTION
      case ._PERSON_AND_ORGANIZATION(let entity): return entity.DESCRIPTION
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` )
    public var MIDDLE_NAMES: (SDAI.LIST<tLABEL>/*[1:?]*/ )?  {
      switch self {
      case ._PERSON(let entity): return entity.MIDDLE_NAMES
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXECUTED_ACTION`` )
    public var DIRECTIVE: eACTION_DIRECTIVE.PRef?  {
      switch self {
      case ._EXECUTED_ACTION(let entity): return entity.DIRECTIVE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` )
    public var SUFFIX_TITLES: (SDAI.LIST<tLABEL>/*[1:?]*/ )?  {
      switch self {
      case ._PERSON(let entity): return entity.SUFFIX_TITLES
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var CONFIGURATION_TYPE: SDAI.STRING?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.CONFIGURATION_TYPE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_RESOURCE_REQUIREMENT`` )
    public var OPERATIONS: (SDAI.SET<sCHARACTERIZED_ACTION_DEFINITION>/*[1:?]*/ )?  {
      switch self {
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.OPERATIONS
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_RESOURCE_REQUIREMENT`` )
    public var RESOURCES: (SDAI.SET<eACTION_RESOURCE.PRef>/*[1:?]*/ )?  {
      switch self {
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.RESOURCES
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` )
    public var LAST_NAME: tLABEL?  {
      switch self {
      case ._PERSON(let entity): return entity.LAST_NAME
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXECUTED_ACTION`` )
    public var CHOSEN_METHOD: eACTION_METHOD.PRef?  {
      switch self {
      case ._EXECUTED_ACTION(let entity): return entity.CHOSEN_METHOD
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var PURPOSE: tTEXT?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.PURPOSE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` )
    public var FIRST_NAME: tLABEL?  {
      switch self {
      case ._PERSON(let entity): return entity.FIRST_NAME
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var USAGE_CONSTRAINTS: (SDAI.SET<eDOCUMENT_USAGE_CONSTRAINT.PRef>/*[1:?]*/ )?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.USAGE_CONSTRAINTS
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON_AND_ORGANIZATION`` )
    public var THE_PERSON: ePERSON.PRef?  {
      switch self {
      case ._PERSON_AND_ORGANIZATION(let entity): return entity.THE_PERSON
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var NUMBER_OF_ELEMENTS: tCOUNT_MEASURE?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.NUMBER_OF_ELEMENTS
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_RESOURCE_REQUIREMENT`` )
    public var KIND: eRESOURCE_REQUIREMENT_TYPE.PRef?  {
      switch self {
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.KIND
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var CONSEQUENCE: tTEXT?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.CONSEQUENCE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON_AND_ORGANIZATION`` )
    public var THE_ORGANIZATION: eORGANIZATION.PRef?  {
      switch self {
      case ._PERSON_AND_ORGANIZATION(let entity): return entity.THE_ORGANIZATION
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var DOCUMENTS: (SDAI.SET<eDOCUMENT.PRef>/*[1:?]*/ )?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.DOCUMENTS
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXECUTED_ACTION`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` )
    public var ID: tIDENTIFIER?  {
      switch self {
      case ._EXECUTED_ACTION(let entity): return entity.ID
      case ._ORGANIZATION(let entity): return entity.ID
      case ._PERSON(let entity): return entity.ID
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_RESOURCE_REQUIREMENT`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEXECUTED_ACTION`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORGANIZATION`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON_AND_ORGANIZATION`` )
    public var NAME: tLABEL?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.NAME
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.NAME
      case ._EXECUTED_ACTION(let entity): return entity.NAME
      case ._ORGANIZATION(let entity): return entity.NAME
      case ._PERSON_AND_ORGANIZATION(let entity): return entity.NAME
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var INHERITANCE_TYPE: SDAI.STRING?  {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.INHERITANCE_TYPE
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sEXPERIENCE_TYPE_ITEM``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePERSON`` )
    public var PREFIX_TITLES: (SDAI.LIST<tLABEL>/*[1:?]*/ )?  {
      switch self {
      case ._PERSON(let entity): return entity.PREFIX_TITLES
      default: return nil
      }
    }


    //MARK: - SDAI.Value
    public func isValueEqual<T: SDAI.Value>(to rhs: T) -> Bool {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.value.isValueEqual(to: rhs)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.value.isValueEqual(to: rhs)
      case ._EXECUTED_ACTION(let selection): return selection.value.isValueEqual(to: rhs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqual(to: rhs)
      case ._PERSON(let selection): return selection.value.isValueEqual(to: rhs)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.value.isValueEqual(to: rhs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?) -> Bool? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._EXECUTED_ACTION(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._PERSON(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      }
    }

    public func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      switch self {
      case ._ACTION_METHOD(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._EXECUTED_ACTION(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._ORGANIZATION(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._PERSON(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._PERSON_AND_ORGANIZATION(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }
    }

    public func isValueEqual<T: SDAI.Value>(to rhs: T, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._EXECUTED_ACTION(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._PERSON(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._EXECUTED_ACTION(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._ORGANIZATION(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._PERSON(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      }
    }


    //MARK: SDAIGenericTypeBase
    public func copy() -> Self {
      switch self {
      case ._ACTION_METHOD(let selection): return ._ACTION_METHOD(selection.copy())
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return ._ACTION_RESOURCE_REQUIREMENT(selection.copy())
      case ._EXECUTED_ACTION(let selection): return ._EXECUTED_ACTION(selection.copy())
      case ._ORGANIZATION(let selection): return ._ORGANIZATION(selection.copy())
      case ._PERSON(let selection): return ._PERSON(selection.copy())
      case ._PERSON_AND_ORGANIZATION(let selection): return ._PERSON_AND_ORGANIZATION(selection.copy())
      }
    }

    //MARK: SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members: Set<SDAI.STRING> = [SDAI.STRING(Self.typeName)]
      switch self {
      case ._ACTION_METHOD(let selection): members.formUnion(selection.typeMembers)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): members.formUnion(selection.typeMembers)
      case ._EXECUTED_ACTION(let selection): members.formUnion(selection.typeMembers)
      case ._ORGANIZATION(let selection): members.formUnion(selection.typeMembers)
      case ._PERSON(let selection): members.formUnion(selection.typeMembers)
      case ._PERSON_AND_ORGANIZATION(let selection): members.formUnion(selection.typeMembers)
      }
      return members
    }

    public var entityReference: SDAI.EntityReference? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.entityReference
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.entityReference
      case ._EXECUTED_ACTION(let selection): return selection.entityReference
      case ._ORGANIZATION(let selection): return selection.entityReference
      case ._PERSON(let selection): return selection.entityReference
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.entityReference
      }
    }
    public var stringValue: SDAI.STRING? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.stringValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.stringValue
      case ._EXECUTED_ACTION(let selection): return selection.stringValue
      case ._ORGANIZATION(let selection): return selection.stringValue
      case ._PERSON(let selection): return selection.stringValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.stringValue
      }
    }
    public var binaryValue: SDAI.BINARY? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.binaryValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.binaryValue
      case ._EXECUTED_ACTION(let selection): return selection.binaryValue
      case ._ORGANIZATION(let selection): return selection.binaryValue
      case ._PERSON(let selection): return selection.binaryValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.binaryValue
      }
    }
    public var logicalValue: SDAI.LOGICAL? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.logicalValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.logicalValue
      case ._EXECUTED_ACTION(let selection): return selection.logicalValue
      case ._ORGANIZATION(let selection): return selection.logicalValue
      case ._PERSON(let selection): return selection.logicalValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.logicalValue
      }
    }
    public var booleanValue: SDAI.BOOLEAN? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.booleanValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.booleanValue
      case ._EXECUTED_ACTION(let selection): return selection.booleanValue
      case ._ORGANIZATION(let selection): return selection.booleanValue
      case ._PERSON(let selection): return selection.booleanValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.booleanValue
      }
    }
    public var numberValue: SDAI.NUMBER? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.numberValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.numberValue
      case ._EXECUTED_ACTION(let selection): return selection.numberValue
      case ._ORGANIZATION(let selection): return selection.numberValue
      case ._PERSON(let selection): return selection.numberValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.numberValue
      }
    }
    public var realValue: SDAI.REAL? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.realValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.realValue
      case ._EXECUTED_ACTION(let selection): return selection.realValue
      case ._ORGANIZATION(let selection): return selection.realValue
      case ._PERSON(let selection): return selection.realValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.realValue
      }
    }
    public var integerValue: SDAI.INTEGER? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.integerValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.integerValue
      case ._EXECUTED_ACTION(let selection): return selection.integerValue
      case ._ORGANIZATION(let selection): return selection.integerValue
      case ._PERSON(let selection): return selection.integerValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.integerValue
      }
    }
    public var genericEnumValue: SDAI.GenericEnumValue? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.genericEnumValue
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.genericEnumValue
      case ._EXECUTED_ACTION(let selection): return selection.genericEnumValue
      case ._ORGANIZATION(let selection): return selection.genericEnumValue
      case ._PERSON(let selection): return selection.genericEnumValue
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.genericEnumValue
      }
    }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._EXECUTED_ACTION(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._PERSON(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.arrayOptionalValue(elementType:elementType)
      }
    }
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.arrayValue(elementType:elementType)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.arrayValue(elementType:elementType)
      case ._EXECUTED_ACTION(let selection): return selection.arrayValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.arrayValue(elementType:elementType)
      case ._PERSON(let selection): return selection.arrayValue(elementType:elementType)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.arrayValue(elementType:elementType)
      }
    }
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.listValue(elementType:elementType)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.listValue(elementType:elementType)
      case ._EXECUTED_ACTION(let selection): return selection.listValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.listValue(elementType:elementType)
      case ._PERSON(let selection): return selection.listValue(elementType:elementType)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.listValue(elementType:elementType)
      }
    }
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.bagValue(elementType:elementType)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.bagValue(elementType:elementType)
      case ._EXECUTED_ACTION(let selection): return selection.bagValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.bagValue(elementType:elementType)
      case ._PERSON(let selection): return selection.bagValue(elementType:elementType)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.bagValue(elementType:elementType)
      }
    }
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.setValue(elementType:elementType)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.setValue(elementType:elementType)
      case ._EXECUTED_ACTION(let selection): return selection.setValue(elementType:elementType)
      case ._ORGANIZATION(let selection): return selection.setValue(elementType:elementType)
      case ._PERSON(let selection): return selection.setValue(elementType:elementType)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.setValue(elementType:elementType)
      }
    }
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? {
      switch self {
      case ._ACTION_METHOD(let selection): return selection.enumValue(enumType:enumType)
      case ._ACTION_RESOURCE_REQUIREMENT(let selection): return selection.enumValue(enumType:enumType)
      case ._EXECUTED_ACTION(let selection): return selection.enumValue(enumType:enumType)
      case ._ORGANIZATION(let selection): return selection.enumValue(enumType:enumType)
      case ._PERSON(let selection): return selection.enumValue(enumType:enumType)
      case ._PERSON_AND_ORGANIZATION(let selection): return selection.enumValue(enumType:enumType)
      }
    }

    //MARK: SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.EXPERIENCE_TYPE_ITEM"
    public var asFundamentalType: FundamentalType { return self }

    //MARK: SDAI.EntityReferenceYielding
    public var entityReferences: AnySequence<SDAI.EntityReference> {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.entityReferences
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.entityReferences
      case ._EXECUTED_ACTION(let entity): return entity.entityReferences
      case ._ORGANIZATION(let entity): return entity.entityReferences
      case ._PERSON(let entity): return entity.entityReferences
      case ._PERSON_AND_ORGANIZATION(let entity): return entity.entityReferences
      }
    }

    public var persistentEntityReferences: AnySequence<SDAI.GenericPersistentEntityReference> {
      switch self {
      case ._ACTION_METHOD(let entity): return entity.persistentEntityReferences
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): return entity.persistentEntityReferences
      case ._EXECUTED_ACTION(let entity): return entity.persistentEntityReferences
      case ._ORGANIZATION(let entity): return entity.persistentEntityReferences
      case ._PERSON(let entity): return entity.persistentEntityReferences
      case ._PERSON_AND_ORGANIZATION(let entity): return entity.persistentEntityReferences
      }
    }

    public func isHolding(entityReference: SDAI.EntityReference) -> Bool {
      switch self {
      case ._ACTION_METHOD(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._EXECUTED_ACTION(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._ORGANIZATION(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._PERSON(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._PERSON_AND_ORGANIZATION(let entity): 
        return entity.isHolding(entityReference: entityReference)
      }
    }


    //MARK: SDAIAggregationBehavior
    public var aggregationHiBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationHiIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationSize: Int? {
      switch self {
      default: return nil
      }
    }

    //MARK: WHERE RULE VALIDATION (SELECT TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      var result: SDAI.WhereRuleValidationRecords = [:]
      switch instance {
      case ._ACTION_METHOD(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eACTION_METHOD.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case ._ACTION_RESOURCE_REQUIREMENT(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eACTION_RESOURCE_REQUIREMENT.validateWhereRules(instance: entity.eval, 
        prefix:prefix + "\\\(entity)")
      case ._EXECUTED_ACTION(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eEXECUTED_ACTION.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case ._ORGANIZATION(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eORGANIZATION.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case ._PERSON(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = ePERSON.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case ._PERSON_AND_ORGANIZATION(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = ePERSON_AND_ORGANIZATION.validateWhereRules(instance: entity.eval, 
        prefix:prefix + "\\\(entity)")
      case nil: break
      }

      return result
    }

  }

}


//MARK: - SELECT TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
public protocol sEXPERIENCE_TYPE_ITEM__TypeBehavior: SDAI.SelectType {
  //MARK: GROUP REFERENCES
  var super_eACTION_RESOURCE_REQUIREMENT: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_RESOURCE_REQUIREMENT.PRef { get }
  var super_ePERSON: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON.PRef { get }
  var super_eACTION_METHOD: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_METHOD.PRef { get }
  var super_eEXECUTED_ACTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEXECUTED_ACTION.PRef { get }
  var super_eORGANIZATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef { get }
  var super_ePERSON_AND_ORGANIZATION: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON_AND_ORGANIZATION.PRef { get }
  var super_eACTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION.PRef { get }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var DESCRIPTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { get }
  var MIDDLE_NAMES: (SDAI.LIST<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL>/*[1:?]*/ )?  { get }
  var DIRECTIVE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_DIRECTIVE.PRef?  { get }
  var SUFFIX_TITLES: (SDAI.LIST<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL>/*[1:?]*/ )?  { get }
  var CONFIGURATION_TYPE: SDAI.STRING?  { get }
  var OPERATIONS: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.sCHARACTERIZED_ACTION_DEFINITION>
    /*[1:?]*/ )?  { get }
  var RESOURCES: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_RESOURCE.PRef>/*[1:?]*/ )?  { get }
  var LAST_NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var CHOSEN_METHOD: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_METHOD.PRef?  { get }
  var PURPOSE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { get }
  var FIRST_NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var USAGE_CONSTRAINTS: (SDAI.SET<
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eDOCUMENT_USAGE_CONSTRAINT.PRef>/*[1:?]*/ )?  { get }
  var THE_PERSON: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON.PRef?  { get }
  var NUMBER_OF_ELEMENTS: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tCOUNT_MEASURE?  { get }
  var KIND: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eRESOURCE_REQUIREMENT_TYPE.PRef?  { get }
  var CONSEQUENCE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { get }
  var THE_ORGANIZATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef?  { get }
  var DOCUMENTS: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eDOCUMENT.PRef>/*[1:?]*/ )?  { get }
  var ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var INHERITANCE_TYPE: SDAI.STRING?  { get }
  var PREFIX_TITLES: (SDAI.LIST<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL>/*[1:?]*/ )?  { get }
}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sEXPERIENCE_TYPE_ITEM__Subtype: sEXPERIENCE_TYPE_ITEM__TypeBehavior, SDAI.DefinedType
where Supertype: sEXPERIENCE_TYPE_ITEM__TypeBehavior
{}
}

public extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy.sEXPERIENCE_TYPE_ITEM__Subtype {
  //MARK: CONSTRUCTORS
  /// initialize SELECT subtype from complex entity
  init?(possiblyFrom complex: SDAI.ComplexEntity?) {
    self.init(fundamental: FundamentalType(possiblyFrom: complex))
  }

  /// initialize SELECT subtype from the underlying type value
  init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?) {
    self.init(fundamental: FundamentalType(possiblyFrom: underlyingType))
  }

  /// initialize SELECT subtype from SDAI generic type value
  init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
    self.init(fundamental: FundamentalType.convert(fromGeneric: generic))
  }

  //MARK: GROUP REFERENCES
  var super_eACTION_RESOURCE_REQUIREMENT: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_RESOURCE_REQUIREMENT.PRef { rep.super_eACTION_RESOURCE_REQUIREMENT }
  var super_ePERSON: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON.PRef { rep.super_ePERSON }
  var super_eACTION_METHOD: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_METHOD.PRef { rep.super_eACTION_METHOD }
  var super_eEXECUTED_ACTION: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEXECUTED_ACTION.PRef { rep.super_eEXECUTED_ACTION }
  var super_eORGANIZATION: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef { rep.super_eORGANIZATION }
  var super_ePERSON_AND_ORGANIZATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON_AND_ORGANIZATION.PRef { rep.super_ePERSON_AND_ORGANIZATION }
  var super_eACTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION.PRef { rep.super_eACTION }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var DESCRIPTION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { rep.DESCRIPTION }
  var MIDDLE_NAMES: (SDAI.LIST<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL>/*[1:?]*/ )?  { rep.MIDDLE_NAMES }
  var DIRECTIVE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_DIRECTIVE.PRef?  { rep.DIRECTIVE }
  var SUFFIX_TITLES: (SDAI.LIST<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL>/*[1:?]*/ )?  { rep.SUFFIX_TITLES }
  var CONFIGURATION_TYPE: SDAI.STRING?  { rep.CONFIGURATION_TYPE }
  var OPERATIONS: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.sCHARACTERIZED_ACTION_DEFINITION>
    /*[1:?]*/ )?  { rep.OPERATIONS }
  var RESOURCES: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_RESOURCE.PRef>/*[1:?]*/ )?  { rep.RESOURCES }
  var LAST_NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.LAST_NAME }
  var CHOSEN_METHOD: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_METHOD.PRef?  { rep.CHOSEN_METHOD }
  var PURPOSE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { rep.PURPOSE }
  var FIRST_NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.FIRST_NAME }
  var USAGE_CONSTRAINTS: (SDAI.SET<
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eDOCUMENT_USAGE_CONSTRAINT.PRef>/*[1:?]*/ )?  { rep.USAGE_CONSTRAINTS }
  var THE_PERSON: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON.PRef?  { rep.THE_PERSON }
  var NUMBER_OF_ELEMENTS: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tCOUNT_MEASURE?  { rep.NUMBER_OF_ELEMENTS }
  var KIND: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eRESOURCE_REQUIREMENT_TYPE.PRef?  { rep.KIND }
  var CONSEQUENCE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tTEXT?  { rep.CONSEQUENCE }
  var THE_ORGANIZATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef?  { rep.THE_ORGANIZATION }
  var DOCUMENTS: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eDOCUMENT.PRef>/*[1:?]*/ )?  { rep.DOCUMENTS }
  var ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.ID }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.NAME }
  var INHERITANCE_TYPE: SDAI.STRING?  { rep.INHERITANCE_TYPE }
  var PREFIX_TITLES: (SDAI.LIST<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL>/*[1:?]*/ )?  { rep.PREFIX_TITLES }
}

