/* file: compatible_dimension.swift 	 generated: Thu Apr  2 16:34:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -RULE definition in EXPRESS

/** RULE definition
- EXPRESS source code:
```express

  RULE compatible_dimension FOR ( cartesian_point, direction, geometric_representation_context );

  WHERE
    wr1: ( ( ( SIZEOF( cartesian_point ) = 0 ) AND ( SIZEOF( direction ) = 0 ) AND ( SIZEOF( 
             geometric_representation_context ) = 0 ) ) OR check_geometric_dimension( cartesian_point, 
             direction, geometric_representation_context ) );

  END_RULE; -- compatible_dimension (line:53468 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static
  func COMPATIBLE_DIMENSION( 
    allComplexEntities: AnySequence<SDAI.ComplexEntity> ) -> [SDAI.WhereLabel:SDAI.LOGICAL] {

    //ENTITY REFERENCES
    let CARTESIAN_POINT = 
      SDAI.POPULATION(OF: eCARTESIAN_POINT.self, FROM: allComplexEntities); SDAI.TOUCH(let: CARTESIAN_POINT)
    let DIRECTION = 
      SDAI.POPULATION(OF: eDIRECTION.self, FROM: allComplexEntities); SDAI.TOUCH(let: DIRECTION)
    let GEOMETRIC_REPRESENTATION_CONTEXT = SDAI.POPULATION(OF: eGEOMETRIC_REPRESENTATION_CONTEXT.self, FROM: allComplexEntities); SDAI.TOUCH(let: GEOMETRIC_REPRESENTATION_CONTEXT)


    //WHERE
    var _conformance: [SDAI.WhereLabel:SDAI.LOGICAL] = [:]
    //
    let _TEMP1 /* SDAI.INTEGER? */ = SDAI.SIZEOF( CARTESIAN_POINT )
    let _TEMP2 /* SDAI.LOGICAL */ = _TEMP1 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
    let _TEMP3 /* SDAI.INTEGER? */ = SDAI.SIZEOF( DIRECTION )
    let _TEMP4 /* SDAI.LOGICAL */ = _TEMP3 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
    let _TEMP5 /* SDAI.LOGICAL */ = _TEMP2 && _TEMP4
    let _TEMP6 /* SDAI.INTEGER? */ = SDAI.SIZEOF( GEOMETRIC_REPRESENTATION_CONTEXT )
    let _TEMP7 /* SDAI.LOGICAL */ = _TEMP6 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
    let _TEMP8 /* SDAI.LOGICAL */ = _TEMP5 && _TEMP7
    let _TEMP9 /* SDAI.BOOLEAN? */ = 
        CHECK_GEOMETRIC_DIMENSION( 
        CAPT: SDAI.SET<eCARTESIAN_POINT.PRef>(
        bound1:SDAI.UNWRAP(0), bound2:(nil as SDAI.INTEGER?), /*SDAI.SET<eCARTESIAN_POINT.PRef>*/
        CARTESIAN_POINT), 
        DIR: SDAI.SET<eDIRECTION.PRef>(
        bound1:SDAI.UNWRAP(0), bound2:(nil as SDAI.INTEGER?), /*SDAI.SET<eDIRECTION.PRef>*/DIRECTION), 
        GRC: SDAI.SET<eGEOMETRIC_REPRESENTATION_CONTEXT.PRef>(
        bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), /*SDAI.SET<
        eGEOMETRIC_REPRESENTATION_CONTEXT.PRef>*/GEOMETRIC_REPRESENTATION_CONTEXT) )
    let _TEMP10 /* SDAI.LOGICAL */ = _TEMP8 || _TEMP9
    let WHERE_wr1 = _TEMP10
    _conformance["WHERE_wr1"] = WHERE_wr1


    return _conformance
  }

}
