/* file: hybrid_brep_edge_select.swift 	 generated: Mon Mar 30 15:41:24 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE hybrid_brep_edge_select = SELECT
    ( edge_curve (*ENTITY*),
     tessellated_edge_curve (*ENTITY*) );
  END_TYPE; -- hybrid_brep_edge_select (line:4269 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES FOR SELECT
/*
  CASE: edge_curve (*ENTITY*):
  ATTR:  permanent_aggregate_id: identifier
  ATTR:  edge_end: vertex
  ATTR:  edge_start: vertex
  ATTR:  edge_geometry: curve
  ATTR:  same_sense: BOOLEAN *** Multiple Select Case Sources ***
  ATTR:  permanent_id: identifier
  ATTR:  name: label
  ATTR:  dim: dimension_count

  CASE: tessellated_edge_curve (*ENTITY*):
  ATTR:  permanent_aggregate_id: identifier
  ATTR:  tessellated_edge_geometry: tessellated_edge
  ATTR:  edge_end: vertex
  ATTR:  edge_start: vertex
  ATTR:  same_sense: BOOLEAN *** Multiple Select Case Sources ***
  ATTR:  permanent_id: identifier
  ATTR:  name: label
  ATTR:  dim: dimension_count

*/

/** SELECT type
- EXPRESS source code:
```express
  TYPE hybrid_brep_edge_select = SELECT
    ( edge_curve (*ENTITY*),
     tessellated_edge_curve (*ENTITY*) );
  END_TYPE; -- hybrid_brep_edge_select (line:4269 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum sHYBRID_BREP_EDGE_SELECT : SDAI.Value, TypeHierarchy.sHYBRID_BREP_EDGE_SELECT__TypeBehavior {

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    @_documentation(visibility:public)
    case _EDGE_CURVE(eEDGE_CURVE.PRef)	// (ENTITY)

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    @_documentation(visibility:public)
    case _TESSELLATED_EDGE_CURVE(eTESSELLATED_EDGE_CURVE.PRef)	// (ENTITY)

    //MARK: - CONSTRUCTORS
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) { self = fundamental }

    /// initialize from the underlying type value
    public init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?){
      return nil
    }

    /// initialize from complex entity
    public init?(possiblyFrom complex: SDAI.ComplexEntity?) {
      guard let complex = complex else { return nil }

      if let base = complex.entityReference(eEDGE_CURVE.self) {self = ._EDGE_CURVE(base.pRef) }
      else if let base = complex.entityReference(eTESSELLATED_EDGE_CURVE.self) {self = ._TESSELLATED_EDGE_CURVE(base.pRef) }
      else { return nil }
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let select = generic else { return nil }

      if let fundamental = select as? Self {
        self.init(fundamental: fundamental)
      }
      else if let base = eEDGE_CURVE.PRef.convert(fromGeneric: select) {
        self = ._EDGE_CURVE(base)
      }
      else if let base = eTESSELLATED_EDGE_CURVE.PRef.convert(fromGeneric: select) {
        self = ._TESSELLATED_EDGE_CURVE(base)
      }
      else { return nil }
    }

    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "HYBRID_BREP_EDGE_SELECT"

    /// initialize from ISO 10303-21 exchange structure typed parameters
    public init?(
      p21typedParam: P21Decode.ExchangeStructure.TypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      guard let keyword = p21typedParam.keyword.asStandardKeyword else { exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"; return nil }

      switch(keyword) {
      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public init?(
      p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      switch p21untypedParam {
      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantEntityName(let name):
          guard let entity = exchangeStructure.resolve(constantEntityName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: entity.complexEntity)

        case .entityInstanceName(let name):
          guard let complex = exchangeStructure.resolve(entityInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: complex)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
          return nil
        }

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init?(p21omittedParamFrom exchangeStructure: P21Decode.ExchangeStructure) {
      return nil
    }


    //MARK: - ENTITY UNDERLYING TYPE REFERENCES
    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    public var underlying_eTOPOLOGICAL_REPRESENTATION_ITEM: eTOPOLOGICAL_REPRESENTATION_ITEM.PRef? {
      switch self {
      case ._EDGE_CURVE(let entity): return eTOPOLOGICAL_REPRESENTATION_ITEM.PRef(entity.eval?.super_eTOPOLOGICAL_REPRESENTATION_ITEM)
      case ._TESSELLATED_EDGE_CURVE(let entity): return eTOPOLOGICAL_REPRESENTATION_ITEM.PRef(entity.eval?.super_eTOPOLOGICAL_REPRESENTATION_ITEM)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    public var underlying_eEDGE: eEDGE.PRef? {
      switch self {
      case ._EDGE_CURVE(let entity): return eEDGE.PRef(entity.eval?.super_eEDGE)
      case ._TESSELLATED_EDGE_CURVE(let entity): return eEDGE.PRef(entity.eval?.super_eEDGE)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    public var underlying_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM.PRef? {
      switch self {
      case ._EDGE_CURVE(let entity): return eREPRESENTATION_ITEM.PRef(entity.eval?.super_eREPRESENTATION_ITEM)
      case ._TESSELLATED_EDGE_CURVE(let entity): return eREPRESENTATION_ITEM.PRef(entity.eval?.super_eREPRESENTATION_ITEM)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    public var underlying_eTESSELLATED_EDGE_CURVE: eTESSELLATED_EDGE_CURVE.PRef? {
      switch self {
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity
      default: return nil
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    public var underlying_eGEOMETRIC_REPRESENTATION_ITEM: eGEOMETRIC_REPRESENTATION_ITEM.PRef? {
      switch self {
      case ._EDGE_CURVE(let entity): return eGEOMETRIC_REPRESENTATION_ITEM.PRef(entity.eval?.super_eGEOMETRIC_REPRESENTATION_ITEM)
      case ._TESSELLATED_EDGE_CURVE(let entity): return eGEOMETRIC_REPRESENTATION_ITEM.PRef(entity.eval?.super_eGEOMETRIC_REPRESENTATION_ITEM)
      }
    }

    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    public var underlying_eEDGE_CURVE: eEDGE_CURVE.PRef? {
      switch self {
      case ._EDGE_CURVE(let entity): return entity
      default: return nil
      }
    }


    //MARK: - ENTITY ATTRIBUTE REFERENCES
    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var PERMANENT_AGGREGATE_ID: tIDENTIFIER?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.PERMANENT_AGGREGATE_ID
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.PERMANENT_AGGREGATE_ID
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var TESSELLATED_EDGE_GEOMETRY: eTESSELLATED_EDGE.PRef?  {
      switch self {
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.TESSELLATED_EDGE_GEOMETRY
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var EDGE_END: eVERTEX.PRef?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.EDGE_END
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.EDGE_END
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var EDGE_START: eVERTEX.PRef?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.EDGE_START
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.EDGE_START
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    public var EDGE_GEOMETRY: eCURVE.PRef?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.EDGE_GEOMETRY
      default: return nil
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var SAME_SENSE: SDAI.BOOLEAN?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.SAME_SENSE
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.SAME_SENSE
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var PERMANENT_ID: tIDENTIFIER?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.PERMANENT_ID
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.PERMANENT_ID
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var NAME: tLABEL?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.NAME
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.NAME
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sHYBRID_BREP_EDGE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var DIM: tDIMENSION_COUNT?  {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.DIM
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.DIM
      }
    }


    //MARK: - SDAI.Value
    public func isValueEqual<T: SDAI.Value>(to rhs: T) -> Bool {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.value.isValueEqual(to: rhs)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.value.isValueEqual(to: rhs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?) -> Bool? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      }
    }

    public func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      switch self {
      case ._EDGE_CURVE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._TESSELLATED_EDGE_CURVE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }
    }

    public func isValueEqual<T: SDAI.Value>(to rhs: T, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      }
    }


    //MARK: SDAIGenericTypeBase
    public func copy() -> Self {
      switch self {
      case ._EDGE_CURVE(let selection): return ._EDGE_CURVE(selection.copy())
      case ._TESSELLATED_EDGE_CURVE(let selection): return ._TESSELLATED_EDGE_CURVE(selection.copy())
      }
    }

    //MARK: SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members: Set<SDAI.STRING> = [SDAI.STRING(Self.typeName)]
      switch self {
      case ._EDGE_CURVE(let selection): members.formUnion(selection.typeMembers)
      case ._TESSELLATED_EDGE_CURVE(let selection): members.formUnion(selection.typeMembers)
      }
      return members
    }

    public var entityReference: SDAI.EntityReference? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.entityReference
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.entityReference
      }
    }
    public var stringValue: SDAI.STRING? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.stringValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.stringValue
      }
    }
    public var binaryValue: SDAI.BINARY? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.binaryValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.binaryValue
      }
    }
    public var logicalValue: SDAI.LOGICAL? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.logicalValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.logicalValue
      }
    }
    public var booleanValue: SDAI.BOOLEAN? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.booleanValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.booleanValue
      }
    }
    public var numberValue: SDAI.NUMBER? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.numberValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.numberValue
      }
    }
    public var realValue: SDAI.REAL? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.realValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.realValue
      }
    }
    public var integerValue: SDAI.INTEGER? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.integerValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.integerValue
      }
    }
    public var genericEnumValue: SDAI.GenericEnumValue? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.genericEnumValue
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.genericEnumValue
      }
    }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      }
    }
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.arrayValue(elementType:elementType)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.arrayValue(elementType:elementType)
      }
    }
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.listValue(elementType:elementType)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.listValue(elementType:elementType)
      }
    }
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.bagValue(elementType:elementType)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.bagValue(elementType:elementType)
      }
    }
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.setValue(elementType:elementType)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.setValue(elementType:elementType)
      }
    }
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? {
      switch self {
      case ._EDGE_CURVE(let selection): return selection.enumValue(enumType:enumType)
      case ._TESSELLATED_EDGE_CURVE(let selection): return selection.enumValue(enumType:enumType)
      }
    }

    //MARK: SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.HYBRID_BREP_EDGE_SELECT"
    public var asFundamentalType: FundamentalType { return self }

    //MARK: SDAI.EntityReferenceYielding
    public var entityReferences: AnySequence<SDAI.EntityReference> {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.entityReferences
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.entityReferences
      }
    }

    public var persistentEntityReferences: AnySequence<SDAI.GenericPersistentEntityReference> {
      switch self {
      case ._EDGE_CURVE(let entity): return entity.persistentEntityReferences
      case ._TESSELLATED_EDGE_CURVE(let entity): return entity.persistentEntityReferences
      }
    }

    public func isHolding(entityReference: SDAI.EntityReference) -> Bool {
      switch self {
      case ._EDGE_CURVE(let entity): 
        return entity.isHolding(entityReference: entityReference)
      case ._TESSELLATED_EDGE_CURVE(let entity): 
        return entity.isHolding(entityReference: entityReference)
      }
    }


    //MARK: SDAIAggregationBehavior
    public var aggregationHiBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationHiIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationSize: Int? {
      switch self {
      default: return nil
      }
    }

    //MARK: WHERE RULE VALIDATION (SELECT TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      var result: SDAI.WhereRuleValidationRecords = [:]
      switch instance {
      case ._EDGE_CURVE(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eEDGE_CURVE.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case ._TESSELLATED_EDGE_CURVE(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eTESSELLATED_EDGE_CURVE.validateWhereRules(instance: entity.eval, 
        prefix:prefix + "\\\(entity)")
      case nil: break
      }

      return result
    }

  }

}


//MARK: - SELECT TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
public protocol sHYBRID_BREP_EDGE_SELECT__TypeBehavior: SDAI.SelectType {
  //MARK: UNDERLYING TYPE REFERENCES
  var underlying_eTOPOLOGICAL_REPRESENTATION_ITEM: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTOPOLOGICAL_REPRESENTATION_ITEM.PRef? { get }
  var underlying_eEDGE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEDGE.PRef? { get }
  var underlying_eREPRESENTATION_ITEM: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eREPRESENTATION_ITEM.PRef? { get }
  var underlying_eTESSELLATED_EDGE_CURVE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTESSELLATED_EDGE_CURVE.PRef? { get }
  var underlying_eGEOMETRIC_REPRESENTATION_ITEM: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eGEOMETRIC_REPRESENTATION_ITEM.PRef? { get }
  var underlying_eEDGE_CURVE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEDGE_CURVE.PRef? { get }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var PERMANENT_AGGREGATE_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var TESSELLATED_EDGE_GEOMETRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTESSELLATED_EDGE.PRef?  { get }
  var EDGE_END: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX.PRef?  { get }
  var EDGE_START: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX.PRef?  { get }
  var EDGE_GEOMETRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eCURVE.PRef?  { get }
  var SAME_SENSE: SDAI.BOOLEAN?  { get }
  var PERMANENT_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var DIM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tDIMENSION_COUNT?  { get }
}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sHYBRID_BREP_EDGE_SELECT__Subtype: sHYBRID_BREP_EDGE_SELECT__TypeBehavior, SDAI.DefinedType
where Supertype: sHYBRID_BREP_EDGE_SELECT__TypeBehavior
{}
}

public extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy.sHYBRID_BREP_EDGE_SELECT__Subtype {
  //MARK: CONSTRUCTORS
  /// initialize SELECT subtype from complex entity
  init?(possiblyFrom complex: SDAI.ComplexEntity?) {
    self.init(fundamental: FundamentalType(possiblyFrom: complex))
  }

  /// initialize SELECT subtype from the underlying type value
  init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?) {
    self.init(fundamental: FundamentalType(possiblyFrom: underlyingType))
  }

  /// initialize SELECT subtype from SDAI generic type value
  init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
    self.init(fundamental: FundamentalType.convert(fromGeneric: generic))
  }

  //MARK: UNDERLYING TYPE REFERENCES
  var underlying_eTOPOLOGICAL_REPRESENTATION_ITEM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTOPOLOGICAL_REPRESENTATION_ITEM.PRef? { rep.underlying_eTOPOLOGICAL_REPRESENTATION_ITEM }
  var underlying_eEDGE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEDGE.PRef? { rep.underlying_eEDGE }
  var underlying_eREPRESENTATION_ITEM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eREPRESENTATION_ITEM.PRef? { rep.underlying_eREPRESENTATION_ITEM }
  var underlying_eTESSELLATED_EDGE_CURVE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTESSELLATED_EDGE_CURVE.PRef? { rep.underlying_eTESSELLATED_EDGE_CURVE }
  var underlying_eGEOMETRIC_REPRESENTATION_ITEM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eGEOMETRIC_REPRESENTATION_ITEM.PRef? { rep.underlying_eGEOMETRIC_REPRESENTATION_ITEM }
  var underlying_eEDGE_CURVE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eEDGE_CURVE.PRef? { rep.underlying_eEDGE_CURVE }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var PERMANENT_AGGREGATE_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.PERMANENT_AGGREGATE_ID }
  var TESSELLATED_EDGE_GEOMETRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eTESSELLATED_EDGE.PRef?  { rep.TESSELLATED_EDGE_GEOMETRY }
  var EDGE_END: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX.PRef?  { rep.EDGE_END }
  var EDGE_START: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eVERTEX.PRef?  { rep.EDGE_START }
  var EDGE_GEOMETRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eCURVE.PRef?  { rep.EDGE_GEOMETRY }
  var SAME_SENSE: SDAI.BOOLEAN?  { rep.SAME_SENSE }
  var PERMANENT_ID: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.PERMANENT_ID }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.NAME }
  var DIM: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tDIMENSION_COUNT?  { rep.DIM }
}

