/* file: md_valid_content_in_geometric_set_for_placeholder.swift 	 generated: Thu Apr  2 16:34:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -FUNCTION definition in EXPRESS

/** FUNCTION definition
- EXPRESS source code:
```express

  FUNCTION md_valid_content_in_geometric_set_for_placeholder(
               input : geometric_set
           ) : BOOLEAN;

    LOCAL
      pass       : BOOLEAN := TRUE;
      boxes      : BAG OF planar_box := [];
      texts      : BAG OF annotation_text := [];
      placements : BAG OF placement := [];
      points     : BAG OF point := [];
    END_LOCAL;
    REPEAT i := LOINDEX( input\geometric_set.elements ) TO HIINDEX( input\geometric_set.elements ) BY 1;
      IF ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POINT' IN TYPEOF( input\geometric_set.elements[i] ) ) 
          AND ( NOT ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.CARTESIAN_POINT', 
          'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POINT_ON_CURVE' , 
          'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POINT_ON_SURFACE' ] * TYPEOF( input\geometric_set.
          elements[i] ) ) = 1 ) ) THEN
        pass := FALSE;
      ELSE
        points := points + input\geometric_set.elements[i];
      END_IF;
      IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PLANAR_BOX' IN TYPEOF( input\geometric_set.elements
          [i] ) THEN
        boxes := boxes + input\geometric_set.elements[i];
      END_IF;
      IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ANNOTATION_TEXT' IN TYPEOF( input\geometric_set.
          elements[i] ) THEN
        texts := texts + input\geometric_set.elements[i];
      END_IF;
      IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PLACEMENT' IN TYPEOF( input\geometric_set.elements[
          i] ) THEN
        placements := placements + input\geometric_set.elements[i];
      END_IF;
    END_REPEAT;
    IF SIZEOF( boxes ) > 1 THEN
      pass := FALSE;
    END_IF;
    IF SIZEOF( texts ) > 1 THEN
      pass := FALSE;
    END_IF;
    IF SIZEOF( placements ) <> 1 THEN
      pass := FALSE;
    END_IF;
    RETURN( pass );

  END_FUNCTION; -- md_valid_content_in_geometric_set_for_placeholder (line:46915 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static 
  func MD_VALID_CONTENT_IN_GEOMETRIC_SET_FOR_PLACEHOLDER( _ INPUT: eGEOMETRIC_SET.PRef?  ) 
    -> SDAI.BOOLEAN? {

    //CACHE LOOKUP
    let _params = SDAI.ParameterList( INPUT )
    if case .available(let _cached_value) = _md_valid_content_in_geometric_set_for_placeholder__cache.cachedValue(params: _params) {
      return _cached_value as? SDAI.BOOLEAN
    }

    //PARAMETER VALUES
    var INPUT = INPUT; SDAI.TOUCH(var: &INPUT)

    //LOCAL
    var PASS: SDAI.BOOLEAN?  = SDAI.BOOLEAN(SDAI.TRUE); SDAI.TOUCH(var: &PASS)
    var BOXES: SDAI.BAG<ePLANAR_BOX.PRef>?  = SDAI.BAG<ePLANAR_BOX.PRef>(SDAI.EMPTY_AGGREGATE); SDAI.TOUCH(var: &BOXES)
    var TEXTS: SDAI.BAG<eANNOTATION_TEXT.PRef>?  = SDAI.BAG<eANNOTATION_TEXT.PRef>(SDAI.EMPTY_AGGREGATE); SDAI.TOUCH(var: &TEXTS)
    var PLACEMENTS: SDAI.BAG<ePLACEMENT.PRef>?  = SDAI.BAG<ePLACEMENT.PRef>(SDAI.EMPTY_AGGREGATE); SDAI.TOUCH(var: &PLACEMENTS)
    var POINTS: SDAI.BAG<ePOINT.PRef>?  = SDAI.BAG<ePOINT.PRef>(SDAI.EMPTY_AGGREGATE); SDAI.TOUCH(var: &POINTS)
    //END_LOCAL

    //BODY
    if let incrementControl/*SDAI.INTEGER*/ = SDAI.FROM(/*SDAI.INTEGER*/SDAI.LOINDEX( 
        (INPUT?.GROUP_REF(eGEOMETRIC_SET.self))?.ELEMENTS ), TO:/*SDAI.INTEGER*/SDAI.HIINDEX( 
        (INPUT?.GROUP_REF(eGEOMETRIC_SET.self))?.ELEMENTS )) {
      for I in incrementControl {
        //
        let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( (INPUT?.GROUP_REF(eGEOMETRIC_SET.self))?.ELEMENTS?[I], 
          IS: ePOINT.self )
        let _TEMP2 /* SDAI.AGGREGATE<SDAI.STRING> */ =  ([ 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.CARTESIAN_POINT")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POINT_ON_CURVE")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POINT_ON_SURFACE")) ] 
            as [SDAI.AggregationInitializerElement<SDAI.STRING>]) 
        let _TEMP3 /* eGEOMETRIC_SET.PRef? */ = INPUT?.GROUP_REF(eGEOMETRIC_SET.self)
        let _TEMP4 /* SDAI.SET<sGEOMETRIC_SET_SELECT>[1:?] ? */ = _TEMP3?.ELEMENTS
        let _TEMP5 /* sGEOMETRIC_SET_SELECT? */ = _TEMP4?[I]
        let _TEMP6 /* SDAI.SET<SDAI.STRING> */ = SDAI.TYPEOF( _TEMP5 )
        let _TEMP7 /* SDAI.SET<SDAI.STRING>? */ = SDAI.FORCE_OPTIONAL(_TEMP2) * SDAI.FORCE_OPTIONAL(_TEMP6)
        let _TEMP8 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP7 )
        let _TEMP9 /* SDAI.LOGICAL */ = _TEMP8 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
        let _TEMP10 /* SDAI.LOGICAL */ =  !_TEMP9
        let _TEMP11 /* SDAI.LOGICAL */ = _TEMP1 && _TEMP10
        if SDAI.IS_TRUE( _TEMP11 ) {
          PASS = SDAI.BOOLEAN(SDAI.FALSE)
        }
        else {
          //
          let _TEMP12 /* eGEOMETRIC_SET.PRef? */ = INPUT?.GROUP_REF(eGEOMETRIC_SET.self)
          let _TEMP13 /* SDAI.SET<sGEOMETRIC_SET_SELECT>[1:?] ? */ = _TEMP12?.ELEMENTS
          let _TEMP14 /* sGEOMETRIC_SET_SELECT? */ = _TEMP13?[I]
          let _TEMP15 /* SDAI.BAG<ePOINT.PRef>? */ = POINTS + _TEMP14
          POINTS = _TEMP15
        }
        //
        let _TEMP16 /* SDAI.LOGICAL */ = SDAI.TYPEOF( (INPUT?.GROUP_REF(eGEOMETRIC_SET.self))?.ELEMENTS?[I], 
          IS: ePLANAR_BOX.self )
        if SDAI.IS_TRUE( _TEMP16 ) {
          //
          let _TEMP17 /* eGEOMETRIC_SET.PRef? */ = INPUT?.GROUP_REF(eGEOMETRIC_SET.self)
          let _TEMP18 /* SDAI.SET<sGEOMETRIC_SET_SELECT>[1:?] ? */ = _TEMP17?.ELEMENTS
          let _TEMP19 /* sGEOMETRIC_SET_SELECT? */ = _TEMP18?[I]
          let _TEMP20 /* SDAI.BAG<ePLANAR_BOX.PRef>? */ = BOXES + _TEMP19
          BOXES = _TEMP20
        }
        //
        let _TEMP21 /* SDAI.LOGICAL */ = SDAI.TYPEOF( (INPUT?.GROUP_REF(eGEOMETRIC_SET.self))?.ELEMENTS?[I], 
          IS: eANNOTATION_TEXT.self )
        if SDAI.IS_TRUE( _TEMP21 ) {
          //
          let _TEMP22 /* eGEOMETRIC_SET.PRef? */ = INPUT?.GROUP_REF(eGEOMETRIC_SET.self)
          let _TEMP23 /* SDAI.SET<sGEOMETRIC_SET_SELECT>[1:?] ? */ = _TEMP22?.ELEMENTS
          let _TEMP24 /* sGEOMETRIC_SET_SELECT? */ = _TEMP23?[I]
          let _TEMP25 /* SDAI.BAG<eANNOTATION_TEXT.PRef>? */ = TEXTS + _TEMP24
          TEXTS = _TEMP25
        }
        //
        let _TEMP26 /* SDAI.LOGICAL */ = SDAI.TYPEOF( (INPUT?.GROUP_REF(eGEOMETRIC_SET.self))?.ELEMENTS?[I], 
          IS: ePLACEMENT.self )
        if SDAI.IS_TRUE( _TEMP26 ) {
          //
          let _TEMP27 /* eGEOMETRIC_SET.PRef? */ = INPUT?.GROUP_REF(eGEOMETRIC_SET.self)
          let _TEMP28 /* SDAI.SET<sGEOMETRIC_SET_SELECT>[1:?] ? */ = _TEMP27?.ELEMENTS
          let _TEMP29 /* sGEOMETRIC_SET_SELECT? */ = _TEMP28?[I]
          let _TEMP30 /* SDAI.BAG<ePLACEMENT.PRef>? */ = PLACEMENTS + _TEMP29
          PLACEMENTS = _TEMP30
        }
      }
    }
    //
    let _TEMP31 /* SDAI.INTEGER? */ = SDAI.SIZEOF( BOXES )
    let _TEMP32 /* SDAI.LOGICAL */ = _TEMP31 > SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
    if SDAI.IS_TRUE( _TEMP32 ) {
      PASS = SDAI.BOOLEAN(SDAI.FALSE)
    }
    //
    let _TEMP33 /* SDAI.INTEGER? */ = SDAI.SIZEOF( TEXTS )
    let _TEMP34 /* SDAI.LOGICAL */ = _TEMP33 > SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
    if SDAI.IS_TRUE( _TEMP34 ) {
      PASS = SDAI.BOOLEAN(SDAI.FALSE)
    }
    //
    let _TEMP35 /* SDAI.INTEGER? */ = SDAI.SIZEOF( PLACEMENTS )
    let _TEMP36 /* SDAI.LOGICAL */ = _TEMP35 .!=. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
    if SDAI.IS_TRUE( _TEMP36 ) {
      PASS = SDAI.BOOLEAN(SDAI.FALSE)
    }
    return _md_valid_content_in_geometric_set_for_placeholder__cache.updateCache(params: _params, value: PASS)
  }

}

//MARK: - function result cache
private let _md_valid_content_in_geometric_set_for_placeholder__cache = SDAI.FunctionResultCache(
  label: "MD_VALID_CONTENT_IN_GEOMETRIC_SET_FOR_PLACEHOLDER",
  controller: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.schemaDefinition )

