/* file: uuid_attribute.swift 	 generated: Thu Apr  2 16:34:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY uuid_attribute
    ABSTRACT SUPERTYPE OF ( 
        ONEOF ( 
            v5_uuid_attribute, 
            v4_uuid_attribute ) 
        ANDOR
        uuid_attribute_with_approximate_location );
      identifier       : uuid;
      identified_item  : uuid_set_or_list_attribute_select;
    UNIQUE
      ur1 : identifier;
  END_ENTITY; -- uuid_attribute (line:37198 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  ENTITY(SELF)	uuid_attribute
    ATTR:  identifier,	TYPE: uuid -- EXPLICIT

    ATTR:  identified_item,	TYPE: uuid_set_or_list_attribute_select -- EXPLICIT


  SUB- ENTITY(2)	hash_based_v5_uuid_attribute
    ATTR:  hash_function,	TYPE: STRING -- EXPLICIT


  SUB- ENTITY(3)	v5_uuid_attribute
    (no local attributes)

  SUB- ENTITY(4)	v4_uuid_attribute
    (no local attributes)

  SUB- ENTITY(5)	uuid_attribute_with_approximate_location
    ATTR:  location_representation,	TYPE: shape_representation -- EXPLICIT

    ATTR:  approximate_location,	TYPE: cartesian_point -- EXPLICIT


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY uuid_attribute
    ABSTRACT SUPERTYPE OF ( 
        ONEOF ( 
            v5_uuid_attribute, 
            v4_uuid_attribute ) 
        ANDOR
        uuid_attribute_with_approximate_location );
      identifier       : uuid;
      identified_item  : uuid_set_or_list_attribute_select;
    UNIQUE
      ur1 : identifier;
  END_ENTITY; -- uuid_attribute (line:37198 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:

- SUBTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eHASH_BASED_V5_UUID_ATTRIBUTE``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eV5_UUID_ATTRIBUTE``
	3.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eV4_UUID_ATTRIBUTE``
	4.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION``

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE/PartialEntity``
*/
  public final class eUUID_ATTRIBUTE : SDAI.EntityReference, SDAI.DualModeReference, SDAI.SimpleEntityType, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eUUID_ATTRIBUTE>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eUUID_ATTRIBUTE.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eUUID_ATTRIBUTE.PartialEntity

    //MARK: SUPERTYPES
    public var super_eUUID_ATTRIBUTE: eUUID_ATTRIBUTE { return self } 	// [1]

    //MARK: SUBTYPES
    public var sub_eHASH_BASED_V5_UUID_ATTRIBUTE: eHASH_BASED_V5_UUID_ATTRIBUTE? {	// [2]
      return self.complexEntity.entityReference(eHASH_BASED_V5_UUID_ATTRIBUTE.self)
    }

    public var sub_eV5_UUID_ATTRIBUTE: eV5_UUID_ATTRIBUTE? {	// [3]
      return self.complexEntity.entityReference(eV5_UUID_ATTRIBUTE.self)
    }

    public var sub_eV4_UUID_ATTRIBUTE: eV4_UUID_ATTRIBUTE? {	// [4]
      return self.complexEntity.entityReference(eV4_UUID_ATTRIBUTE.self)
    }

    public var sub_eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION: eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION? {	// [5]
      return self.complexEntity.entityReference(eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION.self)
    }


    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION`` )
    public var LOCATION_REPRESENTATION: eSHAPE_REPRESENTATION.PRef?  {
      get {
        let originalValue = sub_eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION?.partialEntity
          ._location_representation
        let value = eSHAPE_REPRESENTATION.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION?.partialEntity
          else { return }
        partial._location_representation = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE`` )
    public var IDENTIFIED_ITEM: sUUID_SET_OR_LIST_ATTRIBUTE_SELECT {
      get {
        let originalValue = self.partialEntity._identified_item
        let value = SDAI.UNWRAP( sUUID_SET_OR_LIST_ATTRIBUTE_SELECT( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._identified_item = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eHASH_BASED_V5_UUID_ATTRIBUTE`` )
    public var HASH_FUNCTION: SDAI.STRING?  {
      get {
        let originalValue = sub_eHASH_BASED_V5_UUID_ATTRIBUTE?.partialEntity._hash_function
        let value = SDAI.STRING( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eHASH_BASED_V5_UUID_ATTRIBUTE?.partialEntity
          else { return }
        partial._hash_function = SDAI.UNWRAP(SDAI.STRING(
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE`` )
    public var IDENTIFIER: tUUID {
      get {
        let originalValue = self.partialEntity._identifier
        let value = SDAI.UNWRAP( tUUID( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        let SELF = self; SDAI.TOUCH(let:SELF)
        partial._identifier = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION`` )
    public var APPROXIMATE_LOCATION: eCARTESIAN_POINT.PRef?  {
      get {
        let originalValue = sub_eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION?.partialEntity
          ._approximate_location
        let value = eCARTESIAN_POINT.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eUUID_ATTRIBUTE_WITH_APPROXIMATE_LOCATION?.partialEntity
          else { return }
        partial._approximate_location = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eUUID_ATTRIBUTE.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }

    //SIMPLE ENTITY REFERENCE
    /// initialize simple entity reference from single partial entity
    public convenience init?(_ partial:PartialEntity) {
      let complex = SDAI.ComplexEntity(entities:[partial])
      self.init(complex: complex)
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "UUID_ATTRIBUTE", 
        type: self, explicitAttributeCount: 2)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eUUID_ATTRIBUTE.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "LOCATION_REPRESENTATION", 
        keyPath: \eUUID_ATTRIBUTE.LOCATION_REPRESENTATION, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "IDENTIFIED_ITEM", 
        keyPath: \eUUID_ATTRIBUTE.IDENTIFIED_ITEM, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "HASH_FUNCTION", 
        keyPath: \eUUID_ATTRIBUTE.HASH_FUNCTION, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "IDENTIFIER", 
        keyPath: \eUUID_ATTRIBUTE.IDENTIFIER, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "APPROXIMATE_LOCATION", 
        keyPath: \eUUID_ATTRIBUTE.APPROXIMATE_LOCATION, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)

      //MARK: UNIQUENESS RULE REGISTRATIONS
      entityDef.addUniquenessRule(label:"UNIQUE_ur1", rule: eUUID_ATTRIBUTE.PartialEntity.UNIQUE_ur1)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY uuid_attribute
      ABSTRACT SUPERTYPE OF ( 
          ONEOF ( 
              v5_uuid_attribute, 
              v4_uuid_attribute ) 
          ANDOR
          uuid_attribute_with_approximate_location );
        identifier       : uuid;
        identified_item  : uuid_set_or_list_attribute_select;
      UNIQUE
        ur1 : identifier;
    END_ENTITY; -- uuid_attribute (line:37198 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eUUID_ATTRIBUTE.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _identifier: tUUID // PLAIN EXPLICIT ATTRIBUTE

      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _identified_item: sUUID_SET_OR_LIST_ATTRIBUTE_SELECT // PLAIN EXPLICIT ATTRIBUTE

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._identifier.value.hashAsValue(into: &hasher, visited: &complexEntities)
        self._identified_item.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._identifier.value.isValueEqualOptionally(to: rhs._identifier.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        if let comp = self._identified_item.value.isValueEqualOptionally(to: rhs._identified_item.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._identifier.value.isValueEqualOptionally(to: rhs._identifier.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._identified_item.value.isValueEqualOptionally(to: rhs._identified_item.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //UNIQUENESS RULES
      public static func UNIQUE_ur1(SELF: SDAI.EntityReference) -> AnyHashable? {
        guard let SELF = (SELF as? eUUID_ATTRIBUTE)?.pRef else { return nil }
        //SIMPLE UNIQUE RULE

        guard let attr = SELF.IDENTIFIER else { return nil }
        return AnyHashable( attr )
      }

      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(
        IDENTIFIER: tUUID, 
        IDENTIFIED_ITEM: sUUID_SET_OR_LIST_ATTRIBUTE_SELECT
      ) {

        self._identifier = IDENTIFIER
        self._identified_item = IDENTIFIED_ITEM

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( IDENTIFIER: original._identifier, IDENTIFIED_ITEM: original._identified_item )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 2
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: tUUID.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]IDENTIFIER for partial entity(\(Self.entityName)) constructor"); return nil }

        guard case .success(let p1) = exchangeStructure.recoverRequiredParameter(as: 
          sUUID_SET_OR_LIST_ATTRIBUTE_SELECT.self, from: parameters[1])
        else { exchangeStructure.add(errorContext: "while recovering parameter [1]IDENTIFIED_ITEM for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( IDENTIFIER: p0, IDENTIFIED_ITEM: p1 )
      }
    }
  }
}
