/* file: uuid_provenance.swift 	 generated: Fri Mar  6 17:48:00 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY uuid_provenance;
      identifier  : uuid;
      content     : LIST [1 : ?] OF UNIQUE uuid_relationship;
    UNIQUE
      ur1 : identifier;
  END_ENTITY; -- uuid_provenance (line:37225 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  ENTITY(SELF)	uuid_provenance
    ATTR:  identifier,	TYPE: uuid -- EXPLICIT

    ATTR:  content,	TYPE: LIST [1 : ?] OF UNIQUE uuid_relationship -- EXPLICIT


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY uuid_provenance;
      identifier  : uuid;
      content     : LIST [1 : ?] OF UNIQUE uuid_relationship;
    UNIQUE
      ur1 : identifier;
  END_ENTITY; -- uuid_provenance (line:37225 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_PROVENANCE/PartialEntity``
*/
  public final class eUUID_PROVENANCE : SDAI.EntityReference, SDAI.DualModeReference, SDAI.SimpleEntityType, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eUUID_PROVENANCE>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eUUID_PROVENANCE.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eUUID_PROVENANCE.PartialEntity

    //MARK: SUPERTYPES
    public var super_eUUID_PROVENANCE: eUUID_PROVENANCE { return self } 	// [1]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_PROVENANCE`` )
    public var IDENTIFIER: tUUID {
      get {
        let originalValue = self.partialEntity._identifier
        let value = SDAI.UNWRAP( tUUID( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        let SELF = self; SDAI.TOUCH(let:SELF)
        partial._identifier = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_PROVENANCE`` )
    public var CONTENT: SDAI.LIST_UNIQUE<eUUID_RELATIONSHIP.PRef>/*[1:?]*/  {
      get {
        let originalValue = self.partialEntity._content
        let value = SDAI.UNWRAP( SDAI.LIST_UNIQUE<eUUID_RELATIONSHIP.PRef>( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        let SELF = self; SDAI.TOUCH(let:SELF)
        partial._content = SDAI.UNWRAP(SDAI.LIST_UNIQUE<eUUID_RELATIONSHIP.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eUUID_PROVENANCE.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }

    //SIMPLE ENTITY REFERENCE
    /// initialize simple entity reference from single partial entity
    public convenience init?(_ partial:PartialEntity) {
      let complex = SDAI.ComplexEntity(entities:[partial])
      self.init(complex: complex)
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "UUID_PROVENANCE", 
        type: self, explicitAttributeCount: 2)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eUUID_PROVENANCE.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "IDENTIFIER", 
        keyPath: \eUUID_PROVENANCE.IDENTIFIER, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "CONTENT", 
        keyPath: \eUUID_PROVENANCE.CONTENT, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)

      //MARK: UNIQUENESS RULE REGISTRATIONS
      entityDef.addUniquenessRule(label:"UNIQUE_ur1", rule: eUUID_PROVENANCE.PartialEntity.UNIQUE_ur1)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY uuid_provenance;
        identifier  : uuid;
        content     : LIST [1 : ?] OF UNIQUE uuid_relationship;
      UNIQUE
        ur1 : identifier;
    END_ENTITY; -- uuid_provenance (line:37225 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_PROVENANCE``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eUUID_PROVENANCE.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _identifier: tUUID // PLAIN EXPLICIT ATTRIBUTE

      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _content: SDAI.LIST_UNIQUE<eUUID_RELATIONSHIP.PRef>/*[1:?]*/  // PLAIN EXPLICIT ATTRIBUTE

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._identifier.value.hashAsValue(into: &hasher, visited: &complexEntities)
        self._content.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._identifier.value.isValueEqualOptionally(to: rhs._identifier.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        if let comp = self._content.value.isValueEqualOptionally(to: rhs._content.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._identifier.value.isValueEqualOptionally(to: rhs._identifier.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._content.value.isValueEqualOptionally(to: rhs._content.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //UNIQUENESS RULES
      public static func UNIQUE_ur1(SELF: SDAI.EntityReference) -> AnyHashable? {
        guard let SELF = (SELF as? eUUID_PROVENANCE)?.pRef else { return nil }
        //SIMPLE UNIQUE RULE

        guard let attr = SELF.IDENTIFIER else { return nil }
        return AnyHashable( attr )
      }

      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(
        IDENTIFIER: tUUID, 
        CONTENT: SDAI.LIST_UNIQUE<eUUID_RELATIONSHIP.PRef>/*[1:?]*/ 
      ) {

        self._identifier = IDENTIFIER
        self._content = 
        SDAI.LIST_UNIQUE<eUUID_RELATIONSHIP.PRef>(from: CONTENT.asSwiftType, 
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?))

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( IDENTIFIER: original._identifier, CONTENT: original._content )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 2
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: tUUID.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]IDENTIFIER for partial entity(\(Self.entityName)) constructor"); return nil }

        guard case .success(let p1) = exchangeStructure.recoverRequiredParameter(as: SDAI.LIST_UNIQUE<
          eUUID_RELATIONSHIP.PRef>.self, from: parameters[1])
        else { exchangeStructure.add(errorContext: "while recovering parameter [1]CONTENT for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( IDENTIFIER: p0, CONTENT: p1 )
      }
    }
  }
}
