/* file: generic_attribute_select.swift 	 generated: Sun Mar  1 18:06:18 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE generic_attribute_select = SELECT
    ( address (*ENTITY*) );
  END_TYPE; -- generic_attribute_select (line:3960 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES FOR SELECT
/*
  CASE: address (*ENTITY*):
  ATTR:  people: SET [1 : ?] OF person
  ATTR:  street: label
  ATTR:  description:  (AMBIGUOUS (CASE LEVEL))
  ATTR:  organizations: SET [1 : ?] OF organization
  ATTR:  telex_number: label
  ATTR:  facsimile_number: label
  ATTR:  region: label
  ATTR:  electronic_mail_address: label
  ATTR:  street_number: label
  ATTR:  internal_location: label
  ATTR:  postal_code: label
  ATTR:  postal_box: label
  ATTR:  url: identifier
  ATTR:  town: label
  ATTR:  country: label
  ATTR:  telephone_number: label
  ATTR:  name: label

*/

/** SELECT type
- EXPRESS source code:
```express
  TYPE generic_attribute_select = SELECT
    ( address (*ENTITY*) );
  END_TYPE; -- generic_attribute_select (line:3960 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum sGENERIC_ATTRIBUTE_SELECT : SDAI.Value, TypeHierarchy.sGENERIC_ATTRIBUTE_SELECT__TypeBehavior {

    /// SELECT case (ENTITY)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` (ENTITY)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    @_documentation(visibility:public)
    case _ADDRESS(eADDRESS.PRef)	// (ENTITY)

    //MARK: - CONSTRUCTORS
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) { self = fundamental }

    /// initialize from the underlying type value
    public init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?){
      return nil
    }

    /// initialize from complex entity
    public init?(possiblyFrom complex: SDAI.ComplexEntity?) {
      guard let complex = complex else { return nil }

      if let base = complex.entityReference(eADDRESS.self) {self = ._ADDRESS(base.pRef) }
      else { return nil }
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let select = generic else { return nil }

      if let fundamental = select as? Self {
        self.init(fundamental: fundamental)
      }
      else if let base = eADDRESS.PRef.convert(fromGeneric: select) {
        self = ._ADDRESS(base)
      }
      else { return nil }
    }

    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "GENERIC_ATTRIBUTE_SELECT"

    /// initialize from ISO 10303-21 exchange structure typed parameters
    public init?(
      p21typedParam: P21Decode.ExchangeStructure.TypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      guard let keyword = p21typedParam.keyword.asStandardKeyword else { exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"; return nil }

      switch(keyword) {
      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public init?(
      p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      switch p21untypedParam {
      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantEntityName(let name):
          guard let entity = exchangeStructure.resolve(constantEntityName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: entity.complexEntity)

        case .entityInstanceName(let name):
          guard let complex = exchangeStructure.resolve(entityInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: complex)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
          return nil
        }

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init?(p21omittedParamfrom exchangeStructure: P21Decode.ExchangeStructure) {
      return nil
    }


    //MARK: - ENTITY UNDERLYING TYPE REFERENCES
    /// underlying type reference (ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    public var super_eADDRESS: eADDRESS.PRef {
      switch self {
      case ._ADDRESS(let entity): return entity
      }
    }


    //MARK: - ENTITY ATTRIBUTE REFERENCES
    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var PEOPLE: (SDAI.SET<ePERSON.PRef>/*[1:?]*/ )?  {
      switch self {
      case ._ADDRESS(let entity): return entity.PEOPLE
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var STREET: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.STREET
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var ORGANIZATIONS: (SDAI.SET<eORGANIZATION.PRef>/*[1:?]*/ )?  {
      switch self {
      case ._ADDRESS(let entity): return entity.ORGANIZATIONS
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var TELEX_NUMBER: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.TELEX_NUMBER
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var FACSIMILE_NUMBER: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.FACSIMILE_NUMBER
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var REGION: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.REGION
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var ELECTRONIC_MAIL_ADDRESS: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.ELECTRONIC_MAIL_ADDRESS
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var STREET_NUMBER: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.STREET_NUMBER
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var INTERNAL_LOCATION: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.INTERNAL_LOCATION
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var POSTAL_CODE: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.POSTAL_CODE
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var POSTAL_BOX: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.POSTAL_BOX
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var URL: tIDENTIFIER?  {
      switch self {
      case ._ADDRESS(let entity): return entity.URL
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var TOWN: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.TOWN
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var COUNTRY: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.COUNTRY
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var TELEPHONE_NUMBER: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.TELEPHONE_NUMBER
      }
    }

    /// SELECT type attribute
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sGENERIC_ATTRIBUTE_SELECT``
    /// - origin: ENTITY( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADDRESS`` )
    public var NAME: tLABEL?  {
      switch self {
      case ._ADDRESS(let entity): return entity.NAME
      }
    }


    //MARK: - SDAI.Value
    public func isValueEqual<T: SDAI.Value>(to rhs: T) -> Bool {
      switch self {
      case ._ADDRESS(let selection): return selection.value.isValueEqual(to: rhs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?) -> Bool? {
      switch self {
      case ._ADDRESS(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      }
    }

    public func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      switch self {
      case ._ADDRESS(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }
    }

    public func isValueEqual<T: SDAI.Value>(to rhs: T, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      switch self {
      case ._ADDRESS(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      switch self {
      case ._ADDRESS(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      }
    }


    //MARK: SDAIGenericTypeBase
    public func copy() -> Self {
      switch self {
      case ._ADDRESS(let selection): return ._ADDRESS(selection.copy())
      }
    }

    //MARK: SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members: Set<SDAI.STRING> = [SDAI.STRING(Self.typeName)]
      switch self {
      case ._ADDRESS(let selection): members.formUnion(selection.typeMembers)
      }
      return members
    }

    public var entityReference: SDAI.EntityReference? {
      switch self {
      case ._ADDRESS(let selection): return selection.entityReference
      }
    }
    public var stringValue: SDAI.STRING? {
      switch self {
      case ._ADDRESS(let selection): return selection.stringValue
      }
    }
    public var binaryValue: SDAI.BINARY? {
      switch self {
      case ._ADDRESS(let selection): return selection.binaryValue
      }
    }
    public var logicalValue: SDAI.LOGICAL? {
      switch self {
      case ._ADDRESS(let selection): return selection.logicalValue
      }
    }
    public var booleanValue: SDAI.BOOLEAN? {
      switch self {
      case ._ADDRESS(let selection): return selection.booleanValue
      }
    }
    public var numberValue: SDAI.NUMBER? {
      switch self {
      case ._ADDRESS(let selection): return selection.numberValue
      }
    }
    public var realValue: SDAI.REAL? {
      switch self {
      case ._ADDRESS(let selection): return selection.realValue
      }
    }
    public var integerValue: SDAI.INTEGER? {
      switch self {
      case ._ADDRESS(let selection): return selection.integerValue
      }
    }
    public var genericEnumValue: SDAI.GenericEnumValue? {
      switch self {
      case ._ADDRESS(let selection): return selection.genericEnumValue
      }
    }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {
      switch self {
      case ._ADDRESS(let selection): return selection.arrayOptionalValue(elementType:elementType)
      }
    }
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {
      switch self {
      case ._ADDRESS(let selection): return selection.arrayValue(elementType:elementType)
      }
    }
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {
      switch self {
      case ._ADDRESS(let selection): return selection.listValue(elementType:elementType)
      }
    }
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {
      switch self {
      case ._ADDRESS(let selection): return selection.bagValue(elementType:elementType)
      }
    }
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {
      switch self {
      case ._ADDRESS(let selection): return selection.setValue(elementType:elementType)
      }
    }
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? {
      switch self {
      case ._ADDRESS(let selection): return selection.enumValue(enumType:enumType)
      }
    }

    //MARK: SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.GENERIC_ATTRIBUTE_SELECT"
    public var asFundamentalType: FundamentalType { return self }

    //MARK: SDAI.EntityReferenceYielding
    public var entityReferences: AnySequence<SDAI.EntityReference> {
      switch self {
      case ._ADDRESS(let entity): return entity.entityReferences
      }
    }

    public var persistentEntityReferences: AnySequence<SDAI.GenericPersistentEntityReference> {
      switch self {
      case ._ADDRESS(let entity): return entity.persistentEntityReferences
      }
    }

    public func isHolding(entityReference: SDAI.EntityReference) -> Bool {
      switch self {
      case ._ADDRESS(let entity): 
        return entity.isHolding(entityReference: entityReference)
      }
    }


    //MARK: SDAIAggregationBehavior
    public var aggregationHiBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationHiIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationSize: Int? {
      switch self {
      default: return nil
      }
    }

    //MARK: WHERE RULE VALIDATION (SELECT TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      var result: SDAI.WhereRuleValidationRecords = [:]
      switch instance {
      case ._ADDRESS(let entity): 
        if !entity.shouldPropagateValidation { break }
        result = eADDRESS.validateWhereRules(instance: entity.eval, prefix:prefix + "\\\(entity)")
      case nil: break
      }

      return result
    }

  }

}


//MARK: - SELECT TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
public protocol sGENERIC_ATTRIBUTE_SELECT__TypeBehavior: SDAI.SelectType {
  //MARK: GROUP REFERENCES
  var super_eADDRESS: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eADDRESS.PRef { get }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var PEOPLE: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON.PRef>/*[1:?]*/ )?  { get }
  var STREET: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var ORGANIZATIONS: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef>/*[1:?]*/ )?  { get }
  var TELEX_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var FACSIMILE_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var REGION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var ELECTRONIC_MAIL_ADDRESS: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var STREET_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var INTERNAL_LOCATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var POSTAL_CODE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var POSTAL_BOX: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var URL: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { get }
  var TOWN: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var COUNTRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var TELEPHONE_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { get }
}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sGENERIC_ATTRIBUTE_SELECT__Subtype: 
  sGENERIC_ATTRIBUTE_SELECT__TypeBehavior, SDAI.DefinedType
where Supertype: sGENERIC_ATTRIBUTE_SELECT__TypeBehavior
{}
}

public extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy.sGENERIC_ATTRIBUTE_SELECT__Subtype {
  //MARK: CONSTRUCTORS
  /// initialize SELECT subtype from complex entity
  init?(possiblyFrom complex: SDAI.ComplexEntity?) {
    self.init(fundamental: FundamentalType(possiblyFrom: complex))
  }

  /// initialize SELECT subtype from the underlying type value
  init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?) {
    self.init(fundamental: FundamentalType(possiblyFrom: underlyingType))
  }

  /// initialize SELECT subtype from SDAI generic type value
  init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
    self.init(fundamental: FundamentalType.convert(fromGeneric: generic))
  }

  //MARK: GROUP REFERENCES
  var super_eADDRESS: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eADDRESS.PRef { rep.super_eADDRESS }

  //MARK: ENTITY ATTRIBUTE REFERENCES
  var PEOPLE: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePERSON.PRef>/*[1:?]*/ )?  { rep.PEOPLE }
  var STREET: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.STREET }
  var ORGANIZATIONS: (SDAI.SET<AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eORGANIZATION.PRef>/*[1:?]*/ )?  { rep.ORGANIZATIONS }
  var TELEX_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.TELEX_NUMBER }
  var FACSIMILE_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.FACSIMILE_NUMBER }
  var REGION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.REGION }
  var ELECTRONIC_MAIL_ADDRESS: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.ELECTRONIC_MAIL_ADDRESS }
  var STREET_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.STREET_NUMBER }
  var INTERNAL_LOCATION: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.INTERNAL_LOCATION }
  var POSTAL_CODE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.POSTAL_CODE }
  var POSTAL_BOX: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.POSTAL_BOX }
  var URL: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tIDENTIFIER?  { rep.URL }
  var TOWN: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.TOWN }
  var COUNTRY: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.COUNTRY }
  var TELEPHONE_NUMBER: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.TELEPHONE_NUMBER }
  var NAME: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tLABEL?  { rep.NAME }
}

