/* file: gps_filtration_enumeration.swift 	 generated: Thu Apr  2 16:34:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE gps_filtration_enumeration = ENUMERATION OF
    ( alternating_ball,
     alternating_disc,
     alternating_horizontal_segment,
     ball_radius,
     closing_ball,
     closing_disc,
     closing_horizontal_segment,
     complex_wavelet,
     cutoff_length,
     cutoff_upr,
     disc_radius,
     fourier,
     gaussian,
     hull,
     long_wave_pass_filter,
     opening_ball,
     opening_disc,
     opening_horizontal_segment,
     robust_gaussian,
     robust_spline,
     segment_length,
     short_wave_pass_filter,
     spline,
     spline_wavelet,
     urp_number,
     wavelength );
  END_TYPE; -- gps_filtration_enumeration (line:4068 file:ap242ed4_mim_lf_TY.exp)

*/


/** ENUMERATION type
- EXPRESS source code:
```express
  TYPE gps_filtration_enumeration = ENUMERATION OF
    ( alternating_ball,
     alternating_disc,
     alternating_horizontal_segment,
     ball_radius,
     closing_ball,
     closing_disc,
     closing_horizontal_segment,
     complex_wavelet,
     cutoff_length,
     cutoff_upr,
     disc_radius,
     fourier,
     gaussian,
     hull,
     long_wave_pass_filter,
     opening_ball,
     opening_disc,
     opening_horizontal_segment,
     robust_gaussian,
     robust_spline,
     segment_length,
     short_wave_pass_filter,
     spline,
     spline_wavelet,
     urp_number,
     wavelength );
  END_TYPE; -- gps_filtration_enumeration (line:4068 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum nGPS_FILTRATION_ENUMERATION : SDAI.ENUMERATION, SDAI.Value, 
    TypeHierarchy.nGPS_FILTRATION_ENUMERATION__TypeBehavior {
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case ALTERNATING_BALL
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case ALTERNATING_DISC
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case ALTERNATING_HORIZONTAL_SEGMENT
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case BALL_RADIUS
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case CLOSING_BALL
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case CLOSING_DISC
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case CLOSING_HORIZONTAL_SEGMENT
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case COMPLEX_WAVELET
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case CUTOFF_LENGTH
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case CUTOFF_UPR
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case DISC_RADIUS
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case FOURIER
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case GAUSSIAN
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case HULL
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case LONG_WAVE_PASS_FILTER
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case OPENING_BALL
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case OPENING_DISC
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case OPENING_HORIZONTAL_SEGMENT
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case ROBUST_GAUSSIAN
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case ROBUST_SPLINE
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case SEGMENT_LENGTH
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case SHORT_WAVE_PASS_FILTER
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case SPLINE
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case SPLINE_WAVELET
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case URP_NUMBER
    /// ENUMERATION case
    ///
    /// - defined in: ``nGPS_FILTRATION_ENUMERATION``
    case WAVELENGTH

    // SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members = Set<SDAI.STRING>()
      members.insert(SDAI.STRING(Self.typeName))
      //SELECT data types (indirectly) referencing the current type as a member of the select list
      members.insert(SDAI.STRING(sGPS_FILTRATION_TYPE.typeName)) // -> Self
      return members
    }

    public var entityReference: SDAI.EntityReference? {nil}
    public var stringValue: SDAI.STRING? {nil}
    public var binaryValue: SDAI.BINARY? {nil}
    public var logicalValue: SDAI.LOGICAL? {nil}
    public var booleanValue: SDAI.BOOLEAN? {nil}
    public var numberValue: SDAI.NUMBER? {nil}
    public var realValue: SDAI.REAL? {nil}
    public var integerValue: SDAI.INTEGER? {nil}
    public var genericEnumValue: SDAI.GenericEnumValue? { SDAI.GenericEnumValue(self) }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {nil}
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {nil}
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {nil}
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {nil}
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {nil}
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? { return self as? ENUM }

    // SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.GPS_FILTRATION_ENUMERATION"
    public var asFundamentalType: FundamentalType { return self }

    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) {
      self = fundamental
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let enumval = generic?.enumValue(enumType: Self.self) else { return nil }
      self = enumval
    }
    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "GPS_FILTRATION_ENUMERATION"

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public	init?(p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter, from exchangeStructure: P21Decode.ExchangeStructure) {
      switch p21untypedParam {
      case .enumeration(let enumcase):
        switch enumcase {
        case "ALTERNATING_BALL": self = .ALTERNATING_BALL
        case "ALTERNATING_DISC": self = .ALTERNATING_DISC
        case "ALTERNATING_HORIZONTAL_SEGMENT": self = .ALTERNATING_HORIZONTAL_SEGMENT
        case "BALL_RADIUS": self = .BALL_RADIUS
        case "CLOSING_BALL": self = .CLOSING_BALL
        case "CLOSING_DISC": self = .CLOSING_DISC
        case "CLOSING_HORIZONTAL_SEGMENT": self = .CLOSING_HORIZONTAL_SEGMENT
        case "COMPLEX_WAVELET": self = .COMPLEX_WAVELET
        case "CUTOFF_LENGTH": self = .CUTOFF_LENGTH
        case "CUTOFF_UPR": self = .CUTOFF_UPR
        case "DISC_RADIUS": self = .DISC_RADIUS
        case "FOURIER": self = .FOURIER
        case "GAUSSIAN": self = .GAUSSIAN
        case "HULL": self = .HULL
        case "LONG_WAVE_PASS_FILTER": self = .LONG_WAVE_PASS_FILTER
        case "OPENING_BALL": self = .OPENING_BALL
        case "OPENING_DISC": self = .OPENING_DISC
        case "OPENING_HORIZONTAL_SEGMENT": self = .OPENING_HORIZONTAL_SEGMENT
        case "ROBUST_GAUSSIAN": self = .ROBUST_GAUSSIAN
        case "ROBUST_SPLINE": self = .ROBUST_SPLINE
        case "SEGMENT_LENGTH": self = .SEGMENT_LENGTH
        case "SHORT_WAVE_PASS_FILTER": self = .SHORT_WAVE_PASS_FILTER
        case "SPLINE": self = .SPLINE
        case "SPLINE_WAVELET": self = .SPLINE_WAVELET
        case "URP_NUMBER": self = .URP_NUMBER
        case "WAVELENGTH": self = .WAVELENGTH
        default:
          exchangeStructure.error = "unexpected p21parameter enum case(\(enumcase)) while resolving \(Self.bareTypeName) value"
          return nil
        }

      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantValueName(let name):
          guard let generic = exchangeStructure.resolve(constantValueName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) value"); return nil }
          guard let enumValue = generic.enumValue(enumType:Self.self) else { exchangeStructure.error = "constant value(\(name): \(generic)) is not compatible with \(Self.bareTypeName)"; return nil }
          self = enumValue

        case .valueInstanceName(let name):
          guard let param = exchangeStructure.resolve(valueInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) value from \(rhsname)"); return nil }
          self.init(p21param: param, from: exchangeStructure)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) value"
          return nil
        }

      case .noValue:
        return nil

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) value"
        return nil
      }
    }

  /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init(p21omittedParamFrom exchangeStructure: P21Decode.ExchangeStructure) {
      self = .ALTERNATING_BALL
    }

    //WHERE RULE VALIDATION (ENUMERATION TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      return [:]
    }

  }

  //MARK: -enum case symbol promotions
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let ALTERNATING_BALL = nGPS_FILTRATION_ENUMERATION.ALTERNATING_BALL
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let ALTERNATING_DISC = nGPS_FILTRATION_ENUMERATION.ALTERNATING_DISC
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let ALTERNATING_HORIZONTAL_SEGMENT = nGPS_FILTRATION_ENUMERATION
    .ALTERNATING_HORIZONTAL_SEGMENT
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let BALL_RADIUS = nGPS_FILTRATION_ENUMERATION.BALL_RADIUS
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let CLOSING_BALL = nGPS_FILTRATION_ENUMERATION.CLOSING_BALL
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let CLOSING_DISC = nGPS_FILTRATION_ENUMERATION.CLOSING_DISC
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let CLOSING_HORIZONTAL_SEGMENT = nGPS_FILTRATION_ENUMERATION.CLOSING_HORIZONTAL_SEGMENT
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let COMPLEX_WAVELET = nGPS_FILTRATION_ENUMERATION.COMPLEX_WAVELET
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let CUTOFF_LENGTH = nGPS_FILTRATION_ENUMERATION.CUTOFF_LENGTH
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let CUTOFF_UPR = nGPS_FILTRATION_ENUMERATION.CUTOFF_UPR
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let DISC_RADIUS = nGPS_FILTRATION_ENUMERATION.DISC_RADIUS
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let FOURIER = nGPS_FILTRATION_ENUMERATION.FOURIER
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let GAUSSIAN = nGPS_FILTRATION_ENUMERATION.GAUSSIAN
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let HULL = nGPS_FILTRATION_ENUMERATION.HULL
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let LONG_WAVE_PASS_FILTER = nGPS_FILTRATION_ENUMERATION.LONG_WAVE_PASS_FILTER
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let OPENING_BALL = nGPS_FILTRATION_ENUMERATION.OPENING_BALL
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let OPENING_DISC = nGPS_FILTRATION_ENUMERATION.OPENING_DISC
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let OPENING_HORIZONTAL_SEGMENT = nGPS_FILTRATION_ENUMERATION.OPENING_HORIZONTAL_SEGMENT
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let ROBUST_GAUSSIAN = nGPS_FILTRATION_ENUMERATION.ROBUST_GAUSSIAN
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let ROBUST_SPLINE = nGPS_FILTRATION_ENUMERATION.ROBUST_SPLINE
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let SEGMENT_LENGTH = nGPS_FILTRATION_ENUMERATION.SEGMENT_LENGTH
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let SHORT_WAVE_PASS_FILTER = nGPS_FILTRATION_ENUMERATION.SHORT_WAVE_PASS_FILTER
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let SPLINE = nGPS_FILTRATION_ENUMERATION.SPLINE
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let SPLINE_WAVELET = nGPS_FILTRATION_ENUMERATION.SPLINE_WAVELET
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let URP_NUMBER = nGPS_FILTRATION_ENUMERATION.URP_NUMBER
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nGPS_FILTRATION_ENUMERATION``
  public static let WAVELENGTH = nGPS_FILTRATION_ENUMERATION.WAVELENGTH
}


//MARK: - ENUMERATION TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nGPS_FILTRATION_ENUMERATION__TypeBehavior: SDAI.EnumerationType {}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nGPS_FILTRATION_ENUMERATION__Subtype: 
  nGPS_FILTRATION_ENUMERATION__TypeBehavior, SDAI.DefinedType
where Supertype: nGPS_FILTRATION_ENUMERATION__TypeBehavior
{}
}

