/* file: topological_representation_item.swift 	 generated: Sat Feb 28 19:28:50 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*
  ENTITY topological_representation_item
    SUPERTYPE OF ( 
        ONEOF ( 
            vertex, 
            edge, 
            face_bound, 
            face, 
            vertex_shell, 
            wire_shell, 
            connected_edge_set, 
            connected_face_set, 
            ( 
            loop 
            ANDOR
            path ) ) )
    SUBTYPE OF ( representation_item );
    DERIVE
      permanent_id            : identifier := get_id_value( SELF );
      permanent_aggregate_id  : identifier := get_aggregate_id_value( SELF );
    WHERE
      wr1: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ID_ATTRIBUTE.'
               + 'IDENTIFIED_ITEM'  ) ) <= 1 );
      wr2: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.AGGREGATE_ID_ATTRIBUTE.'
               + 'IDENTIFIED_ITEM'  ) ) <= 1 );
  END_ENTITY; -- topological_representation_item (line:36442 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	representation_item
    ATTR:  name,	TYPE: label -- EXPLICIT


  ENTITY(SELF)	topological_representation_item
    ATTR:  permanent_id,	TYPE: identifier -- DERIVED
      := get_id_value( SELF )

    ATTR:  permanent_aggregate_id,	TYPE: identifier -- DERIVED
      := get_aggregate_id_value( SELF )


  SUB- ENTITY(3)	open_path
    ATTR:  ne,	TYPE: INTEGER -- DERIVED	(AMBIGUOUS/MASKED)
      := SIZEOF( SELF\path.edge_list )


  SUB- ENTITY(4)	kinematic_loop
    REDCR: edge_list,	TYPE: LIST [1 : ?] OF UNIQUE oriented_joint -- EXPLICIT
      -- OVERRIDING ENTITY: path


  SUB- ENTITY(5)	edge_loop
    ATTR:  ne,	TYPE: INTEGER -- DERIVED	(AMBIGUOUS/MASKED)
      := SIZEOF( SELF\path.edge_list )


  SUB- ENTITY(6)	oriented_path
    ATTR:  path_element,	TYPE: path -- EXPLICIT

    ATTR:  orientation,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)

    REDCR: edge_list,	TYPE: LIST [1 : ?] OF UNIQUE oriented_edge -- DERIVED (DYNAMIC)
      := conditional_reverse( SELF.orientation, SELF.path_element.edge_list )
      -- OVERRIDING ENTITY: path


  SUB- ENTITY(7)	subpath
    ATTR:  parent_path,	TYPE: path -- EXPLICIT


  SUB- ENTITY(8)	path
    ATTR:  edge_list,	TYPE: LIST [1 : ?] OF UNIQUE oriented_edge -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: kinematic_loop,	TYPE: LIST [1 : ?] OF UNIQUE oriented_joint
          ENTITY: oriented_path,	TYPE: LIST [1 : ?] OF UNIQUE oriented_edge	(as DERIVED)


  SUB- ENTITY(9)	kinematic_link
    (no local attributes)

  SUB- ENTITY(10)	vertex_point
    ATTR:  vertex_geometry,	TYPE: point -- EXPLICIT


  SUB- ENTITY(11)	tessellated_vertex_point
    ATTR:  tessellated_vertex_geometry,	TYPE: tessellated_vertex -- EXPLICIT


  SUB- ENTITY(12)	vertex
    (no local attributes)

  SUB- ENTITY(13)	subedge
    ATTR:  parent_edge,	TYPE: edge -- EXPLICIT


  SUB- ENTITY(14)	oriented_joint
    REDCR: edge_element,	TYPE: kinematic_joint -- EXPLICIT
      -- OVERRIDING ENTITY: oriented_edge


  SUB- ENTITY(15)	oriented_edge
    ATTR:  edge_element,	TYPE: edge -- EXPLICIT
      -- possibly overridden by
          ENTITY: oriented_joint,	TYPE: kinematic_joint

    ATTR:  orientation,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)

    REDCR: edge_start,	TYPE: vertex -- DERIVED (DYNAMIC)
      := boolean_choose( SELF.orientation, SELF.edge_element.edge_start, SELF.edge_element.edge_end )
      -- OVERRIDING ENTITY: edge

    REDCR: edge_end,	TYPE: vertex -- DERIVED (DYNAMIC)
      := boolean_choose( SELF.orientation, SELF.edge_element.edge_end, SELF.edge_element.edge_start )
      -- OVERRIDING ENTITY: edge


  SUB- ENTITY(16)	edge_bounded_curve_with_length
    REDCR: edge_start,	TYPE: vertex_point -- EXPLICIT
      -- OVERRIDING ENTITY: edge

    REDCR: edge_end,	TYPE: vertex_point -- EXPLICIT
      -- OVERRIDING ENTITY: edge

    REDCR: edge_geometry,	TYPE: bounded_curve_with_length -- EXPLICIT
      -- OVERRIDING ENTITY: edge_curve


  SUB- ENTITY(17)	edge_curve
    ATTR:  edge_geometry,	TYPE: curve -- EXPLICIT
      -- possibly overridden by
          ENTITY: edge_bounded_curve_with_length,	TYPE: bounded_curve_with_length

    ATTR:  same_sense,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)


  SUB- ENTITY(18)	kinematic_joint
    REDCR: edge_start,	TYPE: kinematic_link -- EXPLICIT
      -- OVERRIDING ENTITY: edge

    REDCR: edge_end,	TYPE: kinematic_link -- EXPLICIT
      -- OVERRIDING ENTITY: edge


  SUB- ENTITY(19)	tessellated_edge_curve
    ATTR:  tessellated_edge_geometry,	TYPE: tessellated_edge -- EXPLICIT

    ATTR:  same_sense,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)


  SUB- ENTITY(20)	edge
    ATTR:  edge_start,	TYPE: vertex -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: oriented_edge,	TYPE: vertex	(as DERIVED)
          ENTITY: kinematic_joint,	TYPE: kinematic_link
          ENTITY: edge_bounded_curve_with_length,	TYPE: vertex_point

    ATTR:  edge_end,	TYPE: vertex -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: oriented_edge,	TYPE: vertex	(as DERIVED)
          ENTITY: kinematic_joint,	TYPE: kinematic_link
          ENTITY: edge_bounded_curve_with_length,	TYPE: vertex_point


  SUB- ENTITY(21)	face_outer_bound
    (no local attributes)

  SUB- ENTITY(22)	face_bound
    ATTR:  bound,	TYPE: loop -- EXPLICIT

    ATTR:  orientation,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)


  SUB- ENTITY(23)	advanced_face
    REDCR: face_geometry,	TYPE: advanced_face_geometry_select -- EXPLICIT
      -- OVERRIDING ENTITY: face_surface


  SUB- ENTITY(24)	face_surface
    ATTR:  face_geometry,	TYPE: surface -- EXPLICIT
      -- possibly overridden by
          ENTITY: advanced_face,	TYPE: advanced_face_geometry_select

    ATTR:  same_sense,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)


  SUB- ENTITY(25)	subface
    ATTR:  parent_face,	TYPE: face -- EXPLICIT


  SUB- ENTITY(26)	oriented_face
    ATTR:  face_element,	TYPE: face -- EXPLICIT

    ATTR:  orientation,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)

    REDCR: bounds,	TYPE: SET [1 : ?] OF face_bound -- DERIVED (DYNAMIC)
      := conditional_reverse( SELF.orientation, SELF.face_element.bounds )
      -- OVERRIDING ENTITY: face


  SUB- ENTITY(27)	tessellated_face_surface
    ATTR:  tessellated_face_geometry,	TYPE: tessellated_face -- EXPLICIT

    ATTR:  same_sense,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)


  SUB- ENTITY(28)	face
    ATTR:  bounds,	TYPE: SET [1 : ?] OF face_bound -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: oriented_face,	TYPE: SET [1 : ?] OF face_bound	(as DERIVED)


  SUB- ENTITY(29)	vertex_shell
    ATTR:  vertex_shell_extent,	TYPE: vertex_loop -- EXPLICIT


  SUB- ENTITY(30)	wire_shell
    ATTR:  wire_shell_extent,	TYPE: SET [1 : ?] OF loop -- EXPLICIT


  SUB- ENTITY(31)	connected_edge_sub_set
    ATTR:  parent_edge_set,	TYPE: connected_edge_set -- EXPLICIT


  SUB- ENTITY(32)	connected_edge_set
    ATTR:  ces_edges,	TYPE: SET [1 : ?] OF edge -- EXPLICIT


  SUB- ENTITY(33)	tessellated_closed_shell
    (no local attributes)

  SUB- ENTITY(34)	oriented_closed_shell
    ATTR:  closed_shell_element,	TYPE: closed_shell -- EXPLICIT

    ATTR:  orientation,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)

    REDCR: cfs_faces,	TYPE: SET [1 : ?] OF face -- DERIVED (DYNAMIC)
      := conditional_reverse( SELF.orientation, SELF.closed_shell_element.cfs_faces )
      -- OVERRIDING ENTITY: connected_face_set


  SUB- ENTITY(35)	closed_shell
    (no local attributes)

  SUB- ENTITY(36)	connected_face_sub_set
    ATTR:  parent_face_set,	TYPE: connected_face_set -- EXPLICIT


  SUB- ENTITY(37)	surfaced_open_shell
    (no local attributes)

  SUB- ENTITY(38)	tessellated_open_shell
    (no local attributes)

  SUB- ENTITY(39)	oriented_open_shell
    ATTR:  open_shell_element,	TYPE: open_shell -- EXPLICIT

    ATTR:  orientation,	TYPE: BOOLEAN -- EXPLICIT	(AMBIGUOUS/MASKED)

    REDCR: cfs_faces,	TYPE: SET [1 : ?] OF face -- DERIVED (DYNAMIC)
      := conditional_reverse( SELF.orientation, SELF.open_shell_element.cfs_faces )
      -- OVERRIDING ENTITY: connected_face_set


  SUB- ENTITY(40)	open_shell
    (no local attributes)

  SUB- ENTITY(41)	connected_face_set
    ATTR:  cfs_faces,	TYPE: SET [1 : ?] OF face -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: oriented_closed_shell,	TYPE: SET [1 : ?] OF face	(as DERIVED)
          ENTITY: oriented_open_shell,	TYPE: SET [1 : ?] OF face	(as DERIVED)


  SUB- ENTITY(42)	poly_loop
    ATTR:  polygon,	TYPE: LIST [3 : ?] OF UNIQUE cartesian_point -- EXPLICIT


  SUB- ENTITY(43)	vertex_loop
    ATTR:  loop_vertex,	TYPE: vertex -- EXPLICIT


  SUB- ENTITY(44)	loop
    (no local attributes)

*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY topological_representation_item
    SUPERTYPE OF ( 
        ONEOF ( 
            vertex, 
            edge, 
            face_bound, 
            face, 
            vertex_shell, 
            wire_shell, 
            connected_edge_set, 
            connected_face_set, 
            ( 
            loop 
            ANDOR
            path ) ) )
    SUBTYPE OF ( representation_item );
    DERIVE
      permanent_id            : identifier := get_id_value( SELF );
      permanent_aggregate_id  : identifier := get_aggregate_id_value( SELF );
    WHERE
      wr1: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ID_ATTRIBUTE.'
               + 'IDENTIFIED_ITEM'  ) ) <= 1 );
      wr2: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.AGGREGATE_ID_ATTRIBUTE.'
               + 'IDENTIFIED_ITEM'  ) ) <= 1 );
  END_ENTITY; -- topological_representation_item (line:36442 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM``

- SUBTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eOPEN_PATH``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eKINEMATIC_LOOP``
	3.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_LOOP``
	4.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_PATH``
	5.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSUBPATH``
	6.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH``
	7.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eKINEMATIC_LINK``
	8.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT``
	9.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_VERTEX_POINT``
	10.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX``
	11.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSUBEDGE``
	12.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_JOINT``
	13.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_EDGE``
	14.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_BOUNDED_CURVE_WITH_LENGTH``
	15.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE``
	16.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eKINEMATIC_JOINT``
	17.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE``
	18.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE``
	19.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE_OUTER_BOUND``
	20.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE_BOUND``
	21.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eADVANCED_FACE``
	22.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE_SURFACE``
	23.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSUBFACE``
	24.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_FACE``
	25.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_FACE_SURFACE``
	26.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE``
	27.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_SHELL``
	28.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eWIRE_SHELL``
	29.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SUB_SET``
	30.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET``
	31.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_CLOSED_SHELL``
	32.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_CLOSED_SHELL``
	33.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCLOSED_SHELL``
	34.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_FACE_SUB_SET``
	35.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSURFACED_OPEN_SHELL``
	36.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_OPEN_SHELL``
	37.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_OPEN_SHELL``
	38.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eOPEN_SHELL``
	39.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_FACE_SET``
	40.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePOLY_LOOP``
	41.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_LOOP``
	42.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eLOOP``

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTOPOLOGICAL_REPRESENTATION_ITEM/PartialEntity``
*/
  public final class eTOPOLOGICAL_REPRESENTATION_ITEM : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eTOPOLOGICAL_REPRESENTATION_ITEM>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eTOPOLOGICAL_REPRESENTATION_ITEM.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eTOPOLOGICAL_REPRESENTATION_ITEM.PartialEntity

    //MARK: SUPERTYPES
    public let super_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM 	// [1]
    public var super_eTOPOLOGICAL_REPRESENTATION_ITEM: eTOPOLOGICAL_REPRESENTATION_ITEM { return self } 	// [2]

    //MARK: SUBTYPES
    public var sub_eOPEN_PATH: eOPEN_PATH? {	// [3]
      return self.complexEntity.entityReference(eOPEN_PATH.self)
    }

    public var sub_eKINEMATIC_LOOP: eKINEMATIC_LOOP? {	// [4]
      return self.complexEntity.entityReference(eKINEMATIC_LOOP.self)
    }

    public var sub_eEDGE_LOOP: eEDGE_LOOP? {	// [5]
      return self.complexEntity.entityReference(eEDGE_LOOP.self)
    }

    public var sub_eORIENTED_PATH: eORIENTED_PATH? {	// [6]
      return self.complexEntity.entityReference(eORIENTED_PATH.self)
    }

    public var sub_eSUBPATH: eSUBPATH? {	// [7]
      return self.complexEntity.entityReference(eSUBPATH.self)
    }

    public var sub_ePATH: ePATH? {	// [8]
      return self.complexEntity.entityReference(ePATH.self)
    }

    public var sub_eKINEMATIC_LINK: eKINEMATIC_LINK? {	// [9]
      return self.complexEntity.entityReference(eKINEMATIC_LINK.self)
    }

    public var sub_eVERTEX_POINT: eVERTEX_POINT? {	// [10]
      return self.complexEntity.entityReference(eVERTEX_POINT.self)
    }

    public var sub_eTESSELLATED_VERTEX_POINT: eTESSELLATED_VERTEX_POINT? {	// [11]
      return self.complexEntity.entityReference(eTESSELLATED_VERTEX_POINT.self)
    }

    public var sub_eVERTEX: eVERTEX? {	// [12]
      return self.complexEntity.entityReference(eVERTEX.self)
    }

    public var sub_eSUBEDGE: eSUBEDGE? {	// [13]
      return self.complexEntity.entityReference(eSUBEDGE.self)
    }

    public var sub_eORIENTED_JOINT: eORIENTED_JOINT? {	// [14]
      return self.complexEntity.entityReference(eORIENTED_JOINT.self)
    }

    public var sub_eORIENTED_EDGE: eORIENTED_EDGE? {	// [15]
      return self.complexEntity.entityReference(eORIENTED_EDGE.self)
    }

    public var sub_eEDGE_BOUNDED_CURVE_WITH_LENGTH: eEDGE_BOUNDED_CURVE_WITH_LENGTH? {	// [16]
      return self.complexEntity.entityReference(eEDGE_BOUNDED_CURVE_WITH_LENGTH.self)
    }

    public var sub_eEDGE_CURVE: eEDGE_CURVE? {	// [17]
      return self.complexEntity.entityReference(eEDGE_CURVE.self)
    }

    public var sub_eKINEMATIC_JOINT: eKINEMATIC_JOINT? {	// [18]
      return self.complexEntity.entityReference(eKINEMATIC_JOINT.self)
    }

    public var sub_eTESSELLATED_EDGE_CURVE: eTESSELLATED_EDGE_CURVE? {	// [19]
      return self.complexEntity.entityReference(eTESSELLATED_EDGE_CURVE.self)
    }

    public var sub_eEDGE: eEDGE? {	// [20]
      return self.complexEntity.entityReference(eEDGE.self)
    }

    public var sub_eFACE_OUTER_BOUND: eFACE_OUTER_BOUND? {	// [21]
      return self.complexEntity.entityReference(eFACE_OUTER_BOUND.self)
    }

    public var sub_eFACE_BOUND: eFACE_BOUND? {	// [22]
      return self.complexEntity.entityReference(eFACE_BOUND.self)
    }

    public var sub_eADVANCED_FACE: eADVANCED_FACE? {	// [23]
      return self.complexEntity.entityReference(eADVANCED_FACE.self)
    }

    public var sub_eFACE_SURFACE: eFACE_SURFACE? {	// [24]
      return self.complexEntity.entityReference(eFACE_SURFACE.self)
    }

    public var sub_eSUBFACE: eSUBFACE? {	// [25]
      return self.complexEntity.entityReference(eSUBFACE.self)
    }

    public var sub_eORIENTED_FACE: eORIENTED_FACE? {	// [26]
      return self.complexEntity.entityReference(eORIENTED_FACE.self)
    }

    public var sub_eTESSELLATED_FACE_SURFACE: eTESSELLATED_FACE_SURFACE? {	// [27]
      return self.complexEntity.entityReference(eTESSELLATED_FACE_SURFACE.self)
    }

    public var sub_eFACE: eFACE? {	// [28]
      return self.complexEntity.entityReference(eFACE.self)
    }

    public var sub_eVERTEX_SHELL: eVERTEX_SHELL? {	// [29]
      return self.complexEntity.entityReference(eVERTEX_SHELL.self)
    }

    public var sub_eWIRE_SHELL: eWIRE_SHELL? {	// [30]
      return self.complexEntity.entityReference(eWIRE_SHELL.self)
    }

    public var sub_eCONNECTED_EDGE_SUB_SET: eCONNECTED_EDGE_SUB_SET? {	// [31]
      return self.complexEntity.entityReference(eCONNECTED_EDGE_SUB_SET.self)
    }

    public var sub_eCONNECTED_EDGE_SET: eCONNECTED_EDGE_SET? {	// [32]
      return self.complexEntity.entityReference(eCONNECTED_EDGE_SET.self)
    }

    public var sub_eTESSELLATED_CLOSED_SHELL: eTESSELLATED_CLOSED_SHELL? {	// [33]
      return self.complexEntity.entityReference(eTESSELLATED_CLOSED_SHELL.self)
    }

    public var sub_eORIENTED_CLOSED_SHELL: eORIENTED_CLOSED_SHELL? {	// [34]
      return self.complexEntity.entityReference(eORIENTED_CLOSED_SHELL.self)
    }

    public var sub_eCLOSED_SHELL: eCLOSED_SHELL? {	// [35]
      return self.complexEntity.entityReference(eCLOSED_SHELL.self)
    }

    public var sub_eCONNECTED_FACE_SUB_SET: eCONNECTED_FACE_SUB_SET? {	// [36]
      return self.complexEntity.entityReference(eCONNECTED_FACE_SUB_SET.self)
    }

    public var sub_eSURFACED_OPEN_SHELL: eSURFACED_OPEN_SHELL? {	// [37]
      return self.complexEntity.entityReference(eSURFACED_OPEN_SHELL.self)
    }

    public var sub_eTESSELLATED_OPEN_SHELL: eTESSELLATED_OPEN_SHELL? {	// [38]
      return self.complexEntity.entityReference(eTESSELLATED_OPEN_SHELL.self)
    }

    public var sub_eORIENTED_OPEN_SHELL: eORIENTED_OPEN_SHELL? {	// [39]
      return self.complexEntity.entityReference(eORIENTED_OPEN_SHELL.self)
    }

    public var sub_eOPEN_SHELL: eOPEN_SHELL? {	// [40]
      return self.complexEntity.entityReference(eOPEN_SHELL.self)
    }

    public var sub_eCONNECTED_FACE_SET: eCONNECTED_FACE_SET? {	// [41]
      return self.complexEntity.entityReference(eCONNECTED_FACE_SET.self)
    }

    public var sub_ePOLY_LOOP: ePOLY_LOOP? {	// [42]
      return self.complexEntity.entityReference(ePOLY_LOOP.self)
    }

    public var sub_eVERTEX_LOOP: eVERTEX_LOOP? {	// [43]
      return self.complexEntity.entityReference(eVERTEX_LOOP.self)
    }

    public var sub_eLOOP: eLOOP? {	// [44]
      return self.complexEntity.entityReference(eLOOP.self)
    }


    //MARK: ATTRIBUTES
    // NE: (2 AMBIGUOUS REFs)

    // ORIENTATION: (6 AMBIGUOUS REFs)

    // SAME_SENSE: (4 AMBIGUOUS REFs)

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_VERTEX_POINT`` )
    public var TESSELLATED_VERTEX_GEOMETRY: eTESSELLATED_VERTEX.PRef?  {
      get {
        let originalValue = sub_eTESSELLATED_VERTEX_POINT?.partialEntity._tessellated_vertex_geometry
        let value = eTESSELLATED_VERTEX.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eTESSELLATED_VERTEX_POINT?.partialEntity
          else { return }
        partial._tessellated_vertex_geometry = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_FACE_SET`` )
    public var CFS_FACES: (SDAI.SET<eFACE.PRef>/*[1:?]*/ )?  {
      get {
        if let resolved = eCONNECTED_FACE_SET.PartialEntity._cfs_faces__provider(complex: self.complexEntity) {
          let originalValue = resolved._cfs_faces__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = sub_eCONNECTED_FACE_SET?.partialEntity._cfs_faces
          let value = SDAI.SET<eFACE.PRef>( originalValue )
          return value
        }
      }
      set(newValue) {
        if let _ = eCONNECTED_FACE_SET.PartialEntity._cfs_faces__provider(complex: self.complexEntity) { return }

        guard let partial = 
          sub_eCONNECTED_FACE_SET?.partialEntity
          else { return }
        guard let SELF = sub_eCONNECTED_FACE_SET
           else { return }; SDAI.TOUCH(let:SELF)
        partial._cfs_faces = SDAI.UNWRAP(SDAI.SET<eFACE.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SUB_SET`` )
    public var PARENT_EDGE_SET: eCONNECTED_EDGE_SET.PRef?  {
      get {
        let originalValue = sub_eCONNECTED_EDGE_SUB_SET?.partialEntity._parent_edge_set
        let value = eCONNECTED_EDGE_SET.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eCONNECTED_EDGE_SUB_SET?.partialEntity
          else { return }
        partial._parent_edge_set = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE`` )
    public var BOUNDS: (SDAI.SET<eFACE_BOUND.PRef>/*[1:?]*/ )?  {
      get {
        if let resolved = eFACE.PartialEntity._bounds__provider(complex: self.complexEntity) {
          let originalValue = resolved._bounds__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = sub_eFACE?.partialEntity._bounds
          let value = SDAI.SET<eFACE_BOUND.PRef>( originalValue )
          return value
        }
      }
      set(newValue) {
        if let _ = eFACE.PartialEntity._bounds__provider(complex: self.complexEntity) { return }

        guard let partial = 
          sub_eFACE?.partialEntity
          else { return }
        guard let SELF = sub_eFACE
           else { return }; SDAI.TOUCH(let:SELF)
        partial._bounds = SDAI.UNWRAP(SDAI.SET<eFACE_BOUND.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_EDGE`` )
    public var EDGE_ELEMENT: eEDGE.PRef?  {
      get {
        let originalValue = sub_eORIENTED_EDGE?.partialEntity._edge_element
        let value = eEDGE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eORIENTED_EDGE?.partialEntity
          else { return }
        partial._edge_element = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_LOOP`` )
    public var LOOP_VERTEX: eVERTEX.PRef?  {
      get {
        let originalValue = sub_eVERTEX_LOOP?.partialEntity._loop_vertex
        let value = eVERTEX.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eVERTEX_LOOP?.partialEntity
          else { return }
        partial._loop_vertex = SDAI.UNWRAP(newValue)
      }
    }

    /// __DERIVE__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTOPOLOGICAL_REPRESENTATION_ITEM`` )
    public var PERMANENT_AGGREGATE_ID: tIDENTIFIER?  {
      get {
        if let cached = cachedValue(derivedAttributeName:"PERMANENT_AGGREGATE_ID") {
          return cached.value as! tIDENTIFIER? 
        }
        let origin = self
        let value = origin.partialEntity._permanent_aggregate_id__getter(SELF: origin.pRef)
        updateCache(derivedAttributeName:"PERMANENT_AGGREGATE_ID", value:value)
        return value
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSUBPATH`` )
    public var PARENT_PATH: ePATH.PRef?  {
      get {
        let originalValue = sub_eSUBPATH?.partialEntity._parent_path
        let value = ePATH.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eSUBPATH?.partialEntity
          else { return }
        partial._parent_path = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_PATH`` )
    public var PATH_ELEMENT: ePATH.PRef?  {
      get {
        let originalValue = sub_eORIENTED_PATH?.partialEntity._path_element
        let value = ePATH.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eORIENTED_PATH?.partialEntity
          else { return }
        partial._path_element = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePATH`` )
    public var EDGE_LIST: (SDAI.LIST_UNIQUE<eORIENTED_EDGE.PRef>/*[1:?]*/ )?  {
      get {
        if let resolved = ePATH.PartialEntity._edge_list__provider(complex: self.complexEntity) {
          let originalValue = resolved._edge_list__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = sub_ePATH?.partialEntity._edge_list
          let value = SDAI.LIST_UNIQUE<eORIENTED_EDGE.PRef>( originalValue )
          return value
        }
      }
      set(newValue) {
        if let _ = ePATH.PartialEntity._edge_list__provider(complex: self.complexEntity) { return }

        guard let partial = 
          sub_ePATH?.partialEntity
          else { return }
        guard let SELF = sub_ePATH
           else { return }; SDAI.TOUCH(let:SELF)
        partial._edge_list = SDAI.UNWRAP(SDAI.LIST_UNIQUE<eORIENTED_EDGE.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSUBFACE`` )
    public var PARENT_FACE: eFACE.PRef?  {
      get {
        let originalValue = sub_eSUBFACE?.partialEntity._parent_face
        let value = eFACE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eSUBFACE?.partialEntity
          else { return }
        partial._parent_face = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_FACE_SUB_SET`` )
    public var PARENT_FACE_SET: eCONNECTED_FACE_SET.PRef?  {
      get {
        let originalValue = sub_eCONNECTED_FACE_SUB_SET?.partialEntity._parent_face_set
        let value = eCONNECTED_FACE_SET.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eCONNECTED_FACE_SUB_SET?.partialEntity
          else { return }
        partial._parent_face_set = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_OPEN_SHELL`` )
    public var OPEN_SHELL_ELEMENT: eOPEN_SHELL.PRef?  {
      get {
        let originalValue = sub_eORIENTED_OPEN_SHELL?.partialEntity._open_shell_element
        let value = eOPEN_SHELL.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eORIENTED_OPEN_SHELL?.partialEntity
          else { return }
        partial._open_shell_element = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_SHELL`` )
    public var VERTEX_SHELL_EXTENT: eVERTEX_LOOP.PRef?  {
      get {
        let originalValue = sub_eVERTEX_SHELL?.partialEntity._vertex_shell_extent
        let value = eVERTEX_LOOP.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eVERTEX_SHELL?.partialEntity
          else { return }
        partial._vertex_shell_extent = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_EDGE_CURVE`` )
    public var TESSELLATED_EDGE_GEOMETRY: eTESSELLATED_EDGE.PRef?  {
      get {
        let originalValue = sub_eTESSELLATED_EDGE_CURVE?.partialEntity._tessellated_edge_geometry
        let value = eTESSELLATED_EDGE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eTESSELLATED_EDGE_CURVE?.partialEntity
          else { return }
        partial._tessellated_edge_geometry = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_CLOSED_SHELL`` )
    public var CLOSED_SHELL_ELEMENT: eCLOSED_SHELL.PRef?  {
      get {
        let originalValue = sub_eORIENTED_CLOSED_SHELL?.partialEntity._closed_shell_element
        let value = eCLOSED_SHELL.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eORIENTED_CLOSED_SHELL?.partialEntity
          else { return }
        partial._closed_shell_element = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE_BOUND`` )
    public var BOUND: eLOOP.PRef?  {
      get {
        let originalValue = sub_eFACE_BOUND?.partialEntity._bound
        let value = eLOOP.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eFACE_BOUND?.partialEntity
          else { return }
        partial._bound = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE`` )
    public var EDGE_END: eVERTEX.PRef?  {
      get {
        if let resolved = eEDGE.PartialEntity._edge_end__provider(complex: self.complexEntity) {
          let originalValue = resolved._edge_end__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = sub_eEDGE?.partialEntity._edge_end
          let value = eVERTEX.PRef( originalValue )
          return value
        }
      }
      set(newValue) {
        if let _ = eEDGE.PartialEntity._edge_end__provider(complex: self.complexEntity) { return }

        guard let partial = 
          sub_eEDGE?.partialEntity
          else { return }
        partial._edge_end = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTESSELLATED_FACE_SURFACE`` )
    public var TESSELLATED_FACE_GEOMETRY: eTESSELLATED_FACE.PRef?  {
      get {
        let originalValue = sub_eTESSELLATED_FACE_SURFACE?.partialEntity._tessellated_face_geometry
        let value = eTESSELLATED_FACE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eTESSELLATED_FACE_SURFACE?.partialEntity
          else { return }
        partial._tessellated_face_geometry = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eFACE_SURFACE`` )
    public var FACE_GEOMETRY: eSURFACE.PRef?  {
      get {
        let originalValue = sub_eFACE_SURFACE?.partialEntity._face_geometry
        let value = eSURFACE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eFACE_SURFACE?.partialEntity
          else { return }
        partial._face_geometry = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eORIENTED_FACE`` )
    public var FACE_ELEMENT: eFACE.PRef?  {
      get {
        let originalValue = sub_eORIENTED_FACE?.partialEntity._face_element
        let value = eFACE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eORIENTED_FACE?.partialEntity
          else { return }
        partial._face_element = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eVERTEX_POINT`` )
    public var VERTEX_GEOMETRY: ePOINT.PRef?  {
      get {
        let originalValue = sub_eVERTEX_POINT?.partialEntity._vertex_geometry
        let value = ePOINT.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eVERTEX_POINT?.partialEntity
          else { return }
        partial._vertex_geometry = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eWIRE_SHELL`` )
    public var WIRE_SHELL_EXTENT: (SDAI.SET<eLOOP.PRef>/*[1:?]*/ )?  {
      get {
        let originalValue = sub_eWIRE_SHELL?.partialEntity._wire_shell_extent
        let value = SDAI.SET<eLOOP.PRef>( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eWIRE_SHELL?.partialEntity
          else { return }
        guard let SELF = sub_eWIRE_SHELL
           else { return }; SDAI.TOUCH(let:SELF)
        partial._wire_shell_extent = SDAI.UNWRAP(SDAI.SET<eLOOP.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE`` )
    public var EDGE_START: eVERTEX.PRef?  {
      get {
        if let resolved = eEDGE.PartialEntity._edge_start__provider(complex: self.complexEntity) {
          let originalValue = resolved._edge_start__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = sub_eEDGE?.partialEntity._edge_start
          let value = eVERTEX.PRef( originalValue )
          return value
        }
      }
      set(newValue) {
        if let _ = eEDGE.PartialEntity._edge_start__provider(complex: self.complexEntity) { return }

        guard let partial = 
          sub_eEDGE?.partialEntity
          else { return }
        partial._edge_start = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eEDGE_CURVE`` )
    public var EDGE_GEOMETRY: eCURVE.PRef?  {
      get {
        let originalValue = sub_eEDGE_CURVE?.partialEntity._edge_geometry
        let value = eCURVE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eEDGE_CURVE?.partialEntity
          else { return }
        partial._edge_geometry = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eCONNECTED_EDGE_SET`` )
    public var CES_EDGES: (SDAI.SET<eEDGE.PRef>/*[1:?]*/ )?  {
      get {
        let originalValue = sub_eCONNECTED_EDGE_SET?.partialEntity._ces_edges
        let value = SDAI.SET<eEDGE.PRef>( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eCONNECTED_EDGE_SET?.partialEntity
          else { return }
        guard let SELF = sub_eCONNECTED_EDGE_SET
           else { return }; SDAI.TOUCH(let:SELF)
        partial._ces_edges = SDAI.UNWRAP(SDAI.SET<eEDGE.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __DERIVE__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTOPOLOGICAL_REPRESENTATION_ITEM`` )
    public var PERMANENT_ID: tIDENTIFIER?  {
      get {
        if let cached = cachedValue(derivedAttributeName:"PERMANENT_ID") {
          return cached.value as! tIDENTIFIER? 
        }
        let origin = self
        let value = origin.partialEntity._permanent_id__getter(SELF: origin.pRef)
        updateCache(derivedAttributeName:"PERMANENT_ID", value:value)
        return value
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eSUBEDGE`` )
    public var PARENT_EDGE: eEDGE.PRef?  {
      get {
        let originalValue = sub_eSUBEDGE?.partialEntity._parent_edge
        let value = eEDGE.PRef( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_eSUBEDGE?.partialEntity
          else { return }
        partial._parent_edge = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM`` )
    public var NAME: tLABEL {
      get {
        let originalValue = super_eREPRESENTATION_ITEM.partialEntity._name
        let value = SDAI.UNWRAP( tLABEL( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eREPRESENTATION_ITEM.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUB( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/ePOLY_LOOP`` )
    public var POLYGON: (SDAI.LIST_UNIQUE<eCARTESIAN_POINT.PRef>/*[3:?]*/ )?  {
      get {
        let originalValue = sub_ePOLY_LOOP?.partialEntity._polygon
        let value = SDAI.LIST_UNIQUE<eCARTESIAN_POINT.PRef>( originalValue )
        return value
      }
      set(newValue) {
        guard let partial = 
          sub_ePOLY_LOOP?.partialEntity
          else { return }
        guard let SELF = sub_ePOLY_LOOP
           else { return }; SDAI.TOUCH(let:SELF)
        partial._polygon = SDAI.UNWRAP(SDAI.LIST_UNIQUE<eCARTESIAN_POINT.PRef>(
          bound1:SDAI.UNWRAP(3), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eTOPOLOGICAL_REPRESENTATION_ITEM.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eREPRESENTATION_ITEM.self) else { return nil }
      self.super_eREPRESENTATION_ITEM = super1

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: WHERE RULE VALIDATION (ENTITY)
    public override class func validateWhereRules(instance:SDAI.EntityReference?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      guard let instance = instance as? Self else { return [:] }

      var result = super.validateWhereRules(instance:instance, prefix:prefix)
      result[prefix + " .WHERE_wr1"] = eTOPOLOGICAL_REPRESENTATION_ITEM.PartialEntity.WHERE_wr1(SELF: instance.pRef)
      result[prefix + " .WHERE_wr2"] = eTOPOLOGICAL_REPRESENTATION_ITEM.PartialEntity.WHERE_wr2(SELF: instance.pRef)
      return result
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "TOPOLOGICAL_REPRESENTATION_ITEM", 
        type: self, explicitAttributeCount: 0)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eREPRESENTATION_ITEM.self)
      entityDef.add(supertype: eTOPOLOGICAL_REPRESENTATION_ITEM.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "TESSELLATED_VERTEX_GEOMETRY", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.TESSELLATED_VERTEX_GEOMETRY, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "CFS_FACES", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.CFS_FACES, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "PARENT_EDGE_SET", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PARENT_EDGE_SET, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "BOUNDS", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.BOUNDS, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "EDGE_ELEMENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.EDGE_ELEMENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "LOOP_VERTEX", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.LOOP_VERTEX, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "PERMANENT_AGGREGATE_ID", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PERMANENT_AGGREGATE_ID, 
        kind: .derived, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "PARENT_PATH", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PARENT_PATH, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "PATH_ELEMENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PATH_ELEMENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "EDGE_LIST", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.EDGE_LIST, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "PARENT_FACE", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PARENT_FACE, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "PARENT_FACE_SET", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PARENT_FACE_SET, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "OPEN_SHELL_ELEMENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.OPEN_SHELL_ELEMENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "VERTEX_SHELL_EXTENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.VERTEX_SHELL_EXTENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "TESSELLATED_EDGE_GEOMETRY", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.TESSELLATED_EDGE_GEOMETRY, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "CLOSED_SHELL_ELEMENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.CLOSED_SHELL_ELEMENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "BOUND", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.BOUND, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "EDGE_END", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.EDGE_END, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "TESSELLATED_FACE_GEOMETRY", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.TESSELLATED_FACE_GEOMETRY, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "FACE_GEOMETRY", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.FACE_GEOMETRY, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "FACE_ELEMENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.FACE_ELEMENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "VERTEX_GEOMETRY", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.VERTEX_GEOMETRY, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "WIRE_SHELL_EXTENT", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.WIRE_SHELL_EXTENT, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "EDGE_START", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.EDGE_START, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "EDGE_GEOMETRY", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.EDGE_GEOMETRY, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "CES_EDGES", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.CES_EDGES, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "PERMANENT_ID", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PERMANENT_ID, 
        kind: .derived, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "PARENT_EDGE", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.PARENT_EDGE, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "NAME", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.NAME, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "POLYGON", 
        keyPath: \eTOPOLOGICAL_REPRESENTATION_ITEM.POLYGON, 
        kind: .explicit, source: .subEntity, mayYieldEntityReference: true)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY topological_representation_item
      SUPERTYPE OF ( 
          ONEOF ( 
              vertex, 
              edge, 
              face_bound, 
              face, 
              vertex_shell, 
              wire_shell, 
              connected_edge_set, 
              connected_face_set, 
              ( 
              loop 
              ANDOR
              path ) ) )
      SUBTYPE OF ( representation_item );
      DERIVE
        permanent_id            : identifier := get_id_value( SELF );
        permanent_aggregate_id  : identifier := get_aggregate_id_value( SELF );
      WHERE
        wr1: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ID_ATTRIBUTE.'
                 + 'IDENTIFIED_ITEM'  ) ) <= 1 );
        wr2: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.AGGREGATE_ID_ATTRIBUTE.'
                 + 'IDENTIFIED_ITEM'  ) ) <= 1 );
    END_ENTITY; -- topological_representation_item (line:36442 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTOPOLOGICAL_REPRESENTATION_ITEM``
*/
    public final class PartialEntity : SDAI.PartialEntity, SDAI.Initializable.ByVoid, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eTOPOLOGICAL_REPRESENTATION_ITEM.self
      }

      //ATTRIBUTES
      /// DERIVE ATTRIBUTE
      @_documentation(visibility:public)
      internal func _permanent_id__getter(SELF: eTOPOLOGICAL_REPRESENTATION_ITEM.PRef) -> tIDENTIFIER?  {
        //
        let _TEMP1 /* tIDENTIFIER? */ = GET_ID_VALUE( sID_ATTRIBUTE_SELECT(/*
            eTOPOLOGICAL_REPRESENTATION_ITEM.PRef*/SELF) )
        return _TEMP1
      }

      /// DERIVE ATTRIBUTE
      @_documentation(visibility:public)
      internal func _permanent_aggregate_id__getter(SELF: eTOPOLOGICAL_REPRESENTATION_ITEM.PRef) -> 
        tIDENTIFIER?  {
        //
        let _TEMP1 /* tIDENTIFIER? */ = GET_AGGREGATE_ID_VALUE( sID_ATTRIBUTE_SELECT(/*
            eTOPOLOGICAL_REPRESENTATION_ITEM.PRef*/SELF) )
        return _TEMP1
      }

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        //SELECT data types (indirectly) referencing the current type as a member of the select list
        members.insert(SDAI.STRING(sMULTI_LANGUAGE_ATTRIBUTE_ITEM.typeName)) // -> Self
        members.insert(SDAI.STRING(sID_ATTRIBUTE_SELECT.typeName)) // -> Self
        members.insert(SDAI.STRING(sUUID_ATTRIBUTE_SELECT.typeName)) // -> sID_ATTRIBUTE_SELECT
        members.insert(SDAI.STRING(sSTYLED_ITEM_TARGET.typeName)) // -> Self
        members.insert(SDAI.STRING(sATTRIBUTE_LANGUAGE_ITEM.typeName)) // -> Self
        members.insert(SDAI.STRING(sSHAPE_REPRESENTATION_ITEM.typeName)) // -> Self
        members.insert(SDAI.STRING(sGROUPABLE_ITEM.typeName)) // -> Self
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //MARK: WHERE RULES (ENTITY)
      public static func WHERE_wr1(SELF: eTOPOLOGICAL_REPRESENTATION_ITEM.PRef?) -> SDAI.LOGICAL {
        guard let SELF = SELF else { return SDAI.UNKNOWN }
        //
        let _TEMP1 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = SDAI.USEDIN(T: SELF, 
          ROLE: \AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eID_ATTRIBUTE.IDENTIFIED_ITEM)
        let _TEMP2 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP1 )
        let _TEMP3 /* SDAI.LOGICAL */ = _TEMP2 <= SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
        return _TEMP3
      }
      public static func WHERE_wr2(SELF: eTOPOLOGICAL_REPRESENTATION_ITEM.PRef?) -> SDAI.LOGICAL {
        guard let SELF = SELF else { return SDAI.UNKNOWN }
        //
        let _TEMP1 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = SDAI.USEDIN(T: SELF, 
          ROLE: \AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eAGGREGATE_ID_ATTRIBUTE.IDENTIFIED_ITEM)
        let _TEMP2 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP1 )
        let _TEMP3 /* SDAI.LOGICAL */ = _TEMP2 <= SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
        return _TEMP3
      }

      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init() {
        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        self.init( )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 0
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        self.init( )
      }
    }
  }
}
