/* file: tsdq_location_of_extreme_value.swift 	 generated: Sun Mar  1 18:06:18 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY tsdq_location_of_extreme_value
    SUBTYPE OF ( representation_item );
    INVERSE
      location_of_extreme_value : tsdq_location_of_extreme_value_representation_item_relationship FOR 
                                     related_representation_item -- defined in ENTITY: tsdq_location_of_extreme_value_representation_item_relationship;
  END_ENTITY; -- tsdq_location_of_extreme_value (line:36705 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	representation_item
    ATTR:  name,	TYPE: label -- EXPLICIT


  ENTITY(SELF)	tsdq_location_of_extreme_value
    ATTR:  location_of_extreme_value,	TYPE: tsdq_location_of_extreme_value_representation_item_relationship -- INVERSE
      FOR related_representation_item;


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY tsdq_location_of_extreme_value
    SUBTYPE OF ( representation_item );
    INVERSE
      location_of_extreme_value : tsdq_location_of_extreme_value_representation_item_relationship FOR 
                                     related_representation_item -- defined in ENTITY: tsdq_location_of_extreme_value_representation_item_relationship;
  END_ENTITY; -- tsdq_location_of_extreme_value (line:36705 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM``

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTSDQ_LOCATION_OF_EXTREME_VALUE/PartialEntity``
*/
  public final class eTSDQ_LOCATION_OF_EXTREME_VALUE : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eTSDQ_LOCATION_OF_EXTREME_VALUE>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eTSDQ_LOCATION_OF_EXTREME_VALUE.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eTSDQ_LOCATION_OF_EXTREME_VALUE.PartialEntity

    //MARK: SUPERTYPES
    public let super_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM 	// [1]
    public var super_eTSDQ_LOCATION_OF_EXTREME_VALUE: eTSDQ_LOCATION_OF_EXTREME_VALUE { return self } 	// [2]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __INVERSE__ attribute
    /// observing ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTSDQ_LOCATION_OF_EXTREME_VALUE_REPRESENTATION_ITEM_RELATIONSHIP/RELATED_REPRESENTATION_ITEM``
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTSDQ_LOCATION_OF_EXTREME_VALUE`` )
    public var LOCATION_OF_EXTREME_VALUE: 
      eTSDQ_LOCATION_OF_EXTREME_VALUE_REPRESENTATION_ITEM_RELATIONSHIP.PRef?  {
    get {
      if let cached = cachedValue(derivedAttributeName:"LOCATION_OF_EXTREME_VALUE") {
        return cached.value as! eTSDQ_LOCATION_OF_EXTREME_VALUE_REPRESENTATION_ITEM_RELATIONSHIP.PRef? 
      }
      let value = self.referencingEntity(for: \eTSDQ_LOCATION_OF_EXTREME_VALUE_REPRESENTATION_ITEM_RELATIONSHIP.RELATED_REPRESENTATION_ITEM)
      updateCache(derivedAttributeName:"LOCATION_OF_EXTREME_VALUE", value:value)
      return value
    }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM`` )
    public var NAME: tLABEL {
      get {
        let originalValue = super_eREPRESENTATION_ITEM.partialEntity._name
        let value = SDAI.UNWRAP( tLABEL( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eREPRESENTATION_ITEM.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eTSDQ_LOCATION_OF_EXTREME_VALUE.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eREPRESENTATION_ITEM.self) else { return nil }
      self.super_eREPRESENTATION_ITEM = super1

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "TSDQ_LOCATION_OF_EXTREME_VALUE", 
        type: self, explicitAttributeCount: 0)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eREPRESENTATION_ITEM.self)
      entityDef.add(supertype: eTSDQ_LOCATION_OF_EXTREME_VALUE.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "LOCATION_OF_EXTREME_VALUE", 
        keyPath: \eTSDQ_LOCATION_OF_EXTREME_VALUE.LOCATION_OF_EXTREME_VALUE, 
        kind: .inverse, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "NAME", 
        keyPath: \eTSDQ_LOCATION_OF_EXTREME_VALUE.NAME, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY tsdq_location_of_extreme_value
      SUBTYPE OF ( representation_item );
      INVERSE
        location_of_extreme_value : tsdq_location_of_extreme_value_representation_item_relationship FOR 
                                       related_representation_item -- defined in ENTITY: tsdq_location_of_extreme_value_representation_item_relationship;
    END_ENTITY; -- tsdq_location_of_extreme_value (line:36705 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eTSDQ_LOCATION_OF_EXTREME_VALUE``
*/
    public final class PartialEntity : SDAI.PartialEntity, SDAI.Initializable.ByVoid, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eTSDQ_LOCATION_OF_EXTREME_VALUE.self
      }

      //ATTRIBUTES
      // INVERSE SIMPLE ATTRIBUTE
      // observing eTSDQ_LOCATION_OF_EXTREME_VALUE_REPRESENTATION_ITEM_RELATIONSHIP.PartialEntity ._related_representation_item
      //internal private(set) weak var _location_of_extreme_value: eTSDQ_LOCATION_OF_EXTREME_VALUE_REPRESENTATION_ITEM_RELATIONSHIP.PRef? 	(SEE CORRESPONDING ENTITY REFERENCE DEFINITION)

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        //SELECT data types (indirectly) referencing the current type as a member of the select list
        members.insert(SDAI.STRING(sA3M_LOCATION_OF_EXTREME_VALUE_SELECT.typeName)) // -> Self
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init() {
        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        self.init( )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 0
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        self.init( )
      }
    }
  }
}
