/* file: get_product_definition_shape.swift 	 generated: Thu Apr  2 16:34:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -FUNCTION definition in EXPRESS

/** FUNCTION definition
- EXPRESS source code:
```express

  FUNCTION get_product_definition_shape(
               current : constituent_shape_aspect
           ) : product_definition_shape;
    REPEAT WHILE 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.CONSTITUENT_SHAPE_ASPECT' IN TYPEOF( 
        current.parent );
      current := current.parent;
    END_REPEAT;
    RETURN( current.parent\shape_aspect.of_shape );

  END_FUNCTION; -- get_product_definition_shape (line:45717 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static 
  func GET_PRODUCT_DEFINITION_SHAPE( _ CURRENT: eCONSTITUENT_SHAPE_ASPECT.PRef?  ) 
    -> ePRODUCT_DEFINITION_SHAPE.PRef? {

    //CACHE LOOKUP
    let _params = SDAI.ParameterList( CURRENT )
    if case .available(let _cached_value) = _get_product_definition_shape__cache.cachedValue(params: _params) {
      return _cached_value as? ePRODUCT_DEFINITION_SHAPE.PRef
    }

    //PARAMETER VALUES
    var CURRENT = CURRENT; SDAI.TOUCH(var: &CURRENT)

    //BODY
    while !SDAI.IS_TRUE(SDAI.TYPEOF( CURRENT?.PARENT, IS: eCONSTITUENT_SHAPE_ASPECT.self )) {
      //
      let _TEMP1 /* eSHAPE_ASPECT.PRef? */ = CURRENT?.PARENT
      CURRENT = eCONSTITUENT_SHAPE_ASPECT.PRef(/*eSHAPE_ASPECT.PRef*/_TEMP1)
    }
    //
    let _TEMP2 /* eSHAPE_ASPECT.PRef? */ = CURRENT?.PARENT
    let _TEMP3 /* eSHAPE_ASPECT.PRef? */ = _TEMP2?.GROUP_REF(eSHAPE_ASPECT.self)
    let _TEMP4 /* ePRODUCT_DEFINITION_SHAPE.PRef? */ = _TEMP3?.OF_SHAPE
    return _get_product_definition_shape__cache.updateCache(params: _params, value: _TEMP4)
  }

}

//MARK: - function result cache
private let _get_product_definition_shape__cache = SDAI.FunctionResultCache(
  label: "GET_PRODUCT_DEFINITION_SHAPE",
  controller: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.schemaDefinition )

