/* file: get_item_defined_transformations.swift 	 generated: Fri Feb 27 19:08:27 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -FUNCTION definition in EXPRESS

/** FUNCTION definition
- EXPRESS source code:
```express

  FUNCTION get_item_defined_transformations(
               input : set_item_defined_transformation
           ) : SET OF item_defined_transformation;

    LOCAL
      item_set : SET OF item_defined_transformation := [];
    END_LOCAL;
    REPEAT i := 1 TO HIINDEX( input ) BY 1;
      item_set := item_set + input[i];
    END_REPEAT;
    RETURN( item_set );

  END_FUNCTION; -- get_item_defined_transformations (line:45598 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static 
  func GET_ITEM_DEFINED_TRANSFORMATIONS( _ INPUT: tSET_ITEM_DEFINED_TRANSFORMATION?  ) 
    -> SDAI.SET<eITEM_DEFINED_TRANSFORMATION.PRef>? {

    //CACHE LOOKUP
    let _params = SDAI.ParameterList( INPUT )
    if case .available(let _cached_value) = _get_item_defined_transformations__cache.cachedValue(params: _params) {
      return _cached_value as? SDAI.SET<eITEM_DEFINED_TRANSFORMATION.PRef>
    }

    //PARAMETER VALUES
    var INPUT = INPUT; SDAI.TOUCH(var: &INPUT)

    //LOCAL
    var ITEM_SET: SDAI.SET<eITEM_DEFINED_TRANSFORMATION.PRef>?  = SDAI.SET<eITEM_DEFINED_TRANSFORMATION.PRef>(
      SDAI.EMPTY_AGGREGATE); SDAI.TOUCH(var: &ITEM_SET)
    //END_LOCAL

    //BODY
    if let incrementControl/*SDAI.INTEGER*/ = SDAI.FROM(/*SDAI.INTEGER*/1, TO:/*SDAI.INTEGER*/SDAI.HIINDEX( 
        SDAI.SET<eITEM_DEFINED_TRANSFORMATION.PRef>(/*tSET_ITEM_DEFINED_TRANSFORMATION*/INPUT) )) {
      for I in incrementControl {
        
        let _TEMP1 /* eITEM_DEFINED_TRANSFORMATION.PRef? */ = INPUT?[I]
        let _TEMP2 /* SDAI.SET<eITEM_DEFINED_TRANSFORMATION.PRef>? */ = ITEM_SET + _TEMP1
        ITEM_SET = _TEMP2
      }
    }
    return _get_item_defined_transformations__cache.updateCache(params: _params, value: ITEM_SET)
  }

}

//MARK: - function result cache
private let _get_item_defined_transformations__cache = SDAI.FunctionResultCache(
  label: "GET_ITEM_DEFINED_TRANSFORMATIONS",
  controller: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.schemaDefinition )

