/* file: hash_based_v5_uuid_attribute.swift 	 generated: Wed Feb 25 18:12:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY hash_based_v5_uuid_attribute
    SUBTYPE OF ( v5_uuid_attribute );
      hash_function  : STRING;
    WHERE
      wr1: ( hash_function <> '' );
  END_ENTITY; -- hash_based_v5_uuid_attribute (line:19619 file:ap242ed4_mim_lf.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	uuid_attribute
    ATTR:  identifier,	TYPE: uuid -- EXPLICIT

    ATTR:  identified_item,	TYPE: uuid_set_or_list_attribute_select -- EXPLICIT


  SUPER- ENTITY(2)	v5_uuid_attribute
    (no local attributes)

  ENTITY(SELF)	hash_based_v5_uuid_attribute
    ATTR:  hash_function,	TYPE: STRING -- EXPLICIT


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY hash_based_v5_uuid_attribute
    SUBTYPE OF ( v5_uuid_attribute );
      hash_function  : STRING;
    WHERE
      wr1: ( hash_function <> '' );
  END_ENTITY; -- hash_based_v5_uuid_attribute (line:19619 file:ap242ed4_mim_lf.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eV5_UUID_ATTRIBUTE``

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eHASH_BASED_V5_UUID_ATTRIBUTE/PartialEntity``
*/
  public final class eHASH_BASED_V5_UUID_ATTRIBUTE : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eHASH_BASED_V5_UUID_ATTRIBUTE>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eHASH_BASED_V5_UUID_ATTRIBUTE.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eHASH_BASED_V5_UUID_ATTRIBUTE.PartialEntity

    //MARK: SUPERTYPES
    public let super_eUUID_ATTRIBUTE: eUUID_ATTRIBUTE 	// [1]
    public let super_eV5_UUID_ATTRIBUTE: eV5_UUID_ATTRIBUTE 	// [2]
    public var super_eHASH_BASED_V5_UUID_ATTRIBUTE: eHASH_BASED_V5_UUID_ATTRIBUTE { return self } 	// [3]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE`` )
    public var IDENTIFIED_ITEM: sUUID_SET_OR_LIST_ATTRIBUTE_SELECT {
      get {
        let originalValue = super_eUUID_ATTRIBUTE.partialEntity._identified_item
        let value = SDAI.UNWRAP( sUUID_SET_OR_LIST_ATTRIBUTE_SELECT( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eUUID_ATTRIBUTE.partialEntity
        partial._identified_item = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eHASH_BASED_V5_UUID_ATTRIBUTE`` )
    public var HASH_FUNCTION: SDAI.STRING {
      get {
        let originalValue = self.partialEntity._hash_function
        let value = SDAI.UNWRAP( SDAI.STRING( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._hash_function = SDAI.UNWRAP(SDAI.STRING(
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eUUID_ATTRIBUTE`` )
    public var IDENTIFIER: tUUID {
      get {
        let originalValue = super_eUUID_ATTRIBUTE.partialEntity._identifier
        let value = SDAI.UNWRAP( tUUID( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eUUID_ATTRIBUTE.partialEntity
        let SELF = super_eUUID_ATTRIBUTE; SDAI.TOUCH(let:SELF)
        partial._identifier = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eHASH_BASED_V5_UUID_ATTRIBUTE.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eUUID_ATTRIBUTE.self) else { return nil }
      self.super_eUUID_ATTRIBUTE = super1

      guard let super2 = complexEntity?.entityReference(eV5_UUID_ATTRIBUTE.self) else { return nil }
      self.super_eV5_UUID_ATTRIBUTE = super2

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: WHERE RULE VALIDATION (ENTITY)
    public override class func validateWhereRules(instance:SDAI.EntityReference?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      guard let instance = instance as? Self else { return [:] }

      var result = super.validateWhereRules(instance:instance, prefix:prefix)
      result[prefix + " .WHERE_wr1"] = eHASH_BASED_V5_UUID_ATTRIBUTE.PartialEntity.WHERE_wr1(SELF: instance.pRef)
      return result
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "HASH_BASED_V5_UUID_ATTRIBUTE", 
        type: self, explicitAttributeCount: 1)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eUUID_ATTRIBUTE.self)
      entityDef.add(supertype: eV5_UUID_ATTRIBUTE.self)
      entityDef.add(supertype: eHASH_BASED_V5_UUID_ATTRIBUTE.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "IDENTIFIED_ITEM", 
        keyPath: \eHASH_BASED_V5_UUID_ATTRIBUTE.IDENTIFIED_ITEM, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "HASH_FUNCTION", 
        keyPath: \eHASH_BASED_V5_UUID_ATTRIBUTE.HASH_FUNCTION, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "IDENTIFIER", 
        keyPath: \eHASH_BASED_V5_UUID_ATTRIBUTE.IDENTIFIER, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY hash_based_v5_uuid_attribute
      SUBTYPE OF ( v5_uuid_attribute );
        hash_function  : STRING;
      WHERE
        wr1: ( hash_function <> '' );
    END_ENTITY; -- hash_based_v5_uuid_attribute (line:19619 file:ap242ed4_mim_lf.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eHASH_BASED_V5_UUID_ATTRIBUTE``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eHASH_BASED_V5_UUID_ATTRIBUTE.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _hash_function: SDAI.STRING // PLAIN EXPLICIT ATTRIBUTE

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._hash_function.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._hash_function.value.isValueEqualOptionally(to: rhs._hash_function.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._hash_function.value.isValueEqualOptionally(to: rhs._hash_function.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //MARK: WHERE RULES (ENTITY)
      public static func WHERE_wr1(SELF: eHASH_BASED_V5_UUID_ATTRIBUTE.PRef?) -> SDAI.LOGICAL {
        guard let SELF = SELF else { return SDAI.UNKNOWN }

        let _TEMP1 /* SDAI.LOGICAL */ = SELF.HASH_FUNCTION .!=. SDAI.FORCE_OPTIONAL(SDAI.STRING(""))
        return _TEMP1
      }

      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(HASH_FUNCTION: SDAI.STRING) {

        self._hash_function = 
        SDAI.STRING(from: HASH_FUNCTION.asSwiftType)

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( HASH_FUNCTION: original._hash_function )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 1
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: SDAI.STRING.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]HASH_FUNCTION for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( HASH_FUNCTION: p0 )
      }
    }
  }
}
