/* file: pmidq_validate_element_types.swift 	 generated: Fri Mar  6 17:48:00 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -FUNCTION definition in EXPRESS

/** FUNCTION definition
- EXPRESS source code:
```express

  FUNCTION pmidq_validate_element_types(
               ir : data_quality_inspection_report;
               cr : a3m_pmi_data_quality_criterion
           ) : LOGICAL;

    LOCAL
      aqiiri : a3m_data_quality_inspection_instance_report_item;
      dqiir  : data_quality_inspection_instance_report;
      pietn  : LIST [1 : ?] OF pmidq_inspected_element_type_name;
    END_LOCAL;
    pietn := cr.inspected_elements_types;
    IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.DATA_QUALITY_INSPECTION_INSTANCE_REPORT' IN TYPEOF( 
        ir ) THEN
      dqiir := ir;
      REPEAT i := 1 TO SIZEOF( dqiir.inspected_instances ) BY 1;
        IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM' 
            IN TYPEOF( dqiir.inspected_instances[i] ) THEN
          aqiiri := dqiir.inspected_instances[i];
          IF NOT ( pmidq_get_inspected_element_type_name( aqiiri.inspected_elements ) IN pietn ) THEN
            RETURN( FALSE );
          END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
    RETURN( TRUE );

  END_FUNCTION; -- pmidq_validate_element_types (line:48055 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static 
  func PMIDQ_VALIDATE_ELEMENT_TYPES( 
    IR: eDATA_QUALITY_INSPECTION_REPORT.PRef? , 
    CR: eA3M_PMI_DATA_QUALITY_CRITERION.PRef? 
   ) -> SDAI.LOGICAL {

    //CACHE LOOKUP
    let _params = SDAI.ParameterList( IR, CR )
    if case .available(let _cached_value) = _pmidq_validate_element_types__cache.cachedValue(params: _params) {
      return _cached_value as! SDAI.LOGICAL
    }

    //PARAMETER VALUES
    var IR = IR; SDAI.TOUCH(var: &IR)
    var CR = CR; SDAI.TOUCH(var: &CR)

    //LOCAL
    var AQIIRI: eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef? 
    var DQIIR: eDATA_QUALITY_INSPECTION_INSTANCE_REPORT.PRef? 
    var PIETN: (SDAI.LIST<nPMIDQ_INSPECTED_ELEMENT_TYPE_NAME>/*[1:?]*/ )? 
    //END_LOCAL

    //BODY
    //
    let _TEMP1 /* SDAI.LIST<nPMIDQ_INSPECTED_ELEMENT_TYPE_NAME>[1:?] ? */ = CR?.INSPECTED_ELEMENTS_TYPES
    PIETN = _TEMP1
    //
    let _TEMP2 /* SDAI.LOGICAL */ = SDAI.TYPEOF( IR, IS: eDATA_QUALITY_INSPECTION_INSTANCE_REPORT.self )
    if SDAI.IS_TRUE( _TEMP2 ) {
      DQIIR = eDATA_QUALITY_INSPECTION_INSTANCE_REPORT.PRef(/*eDATA_QUALITY_INSPECTION_REPORT.PRef*/IR)
      if let incrementControl/*SDAI.INTEGER*/ = SDAI.FROM(/*SDAI.INTEGER*/1, TO:/*SDAI.INTEGER*/SDAI.SIZEOF( 
          DQIIR?.INSPECTED_INSTANCES )) {
        for I in incrementControl {
          //
          let _TEMP3 /* SDAI.LOGICAL */ = SDAI.TYPEOF( DQIIR?.INSPECTED_INSTANCES?[I], 
            IS: eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.self )
          if SDAI.IS_TRUE( _TEMP3 ) {
            //
            let _TEMP4 /* SDAI.LIST<eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef>[1:?] ? */ = DQIIR?.INSPECTED_INSTANCES
            let _TEMP5 /* eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef? */ = _TEMP4?[I]
            AQIIRI = eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef(/*
              eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef*/_TEMP5)
            //
            let _TEMP6 /* SDAI.SET<sINSPECTED_ELEMENT_SELECT>[1:?] ? */ = AQIIRI?.INSPECTED_ELEMENTS
            let _TEMP7 /* nPMIDQ_INSPECTED_ELEMENT_TYPE_NAME? */ = PMIDQ_GET_INSPECTED_ELEMENT_TYPE_NAME( 
                _TEMP6 )
            let _TEMP8 /* SDAI.LOGICAL */ = SDAI.aggregate( PIETN, contains: _TEMP7 )
            let _TEMP9 /* SDAI.LOGICAL */ =  !_TEMP8
            if SDAI.IS_TRUE( _TEMP9 ) {
              return _pmidq_validate_element_types__cache.updateCache(params: _params, value: SDAI.UNWRAP(
                SDAI.LOGICAL(SDAI.FALSE)))
            }
          }
        }
      }
    }
    return _pmidq_validate_element_types__cache.updateCache(params: _params, value: SDAI.UNWRAP(SDAI.LOGICAL(
      SDAI.TRUE)))
  }

}

//MARK: - function result cache
private let _pmidq_validate_element_types__cache = SDAI.FunctionResultCache(
  label: "PMIDQ_VALIDATE_ELEMENT_TYPES",
  controller: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.schemaDefinition )

