/* file: pmidq_validate_measured_type.swift 	 generated: Sat Feb 28 18:16:17 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -FUNCTION definition in EXPRESS

/** FUNCTION definition
- EXPRESS source code:
```express

  FUNCTION pmidq_validate_measured_type(
               ir : data_quality_inspection_report;
               cr : a3m_pmi_data_quality_criterion
           ) : LOGICAL;

    LOCAL
      aqicri : a3m_data_quality_inspection_criterion_report_item;
      aqiiri : a3m_data_quality_inspection_instance_report_item;
      aqirie : a3m_instance_report_item_with_extreme_instances;
      dqicr  : data_quality_inspection_criterion_report;
      dqiir  : data_quality_inspection_instance_report;
      pmdtn  : pmidq_measured_data_type_name;
    END_LOCAL;
    pmdtn := cr.measured_data_type;
    IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.DATA_QUALITY_INSPECTION_CRITERION_REPORT' IN TYPEOF( 
        ir ) THEN
      dqicr := ir;
      REPEAT i := 1 TO SIZEOF( dqicr.statistical_values ) BY 1;
        IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM' 
            IN TYPEOF( dqicr.statistical_values[i] ) THEN
          aqicri := dqicr.statistical_values[i];
          IF pmidq_get_measured_type_name( aqicri.representative_measured_value ) <> pmdtn THEN
            RETURN( FALSE );
          END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
    IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.DATA_QUALITY_INSPECTION_INSTANCE_REPORT' IN TYPEOF( 
        ir ) THEN
      dqiir := ir;
      REPEAT i := 1 TO SIZEOF( dqiir.inspected_instances ) BY 1;
        IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM' 
            IN TYPEOF( dqiir.inspected_instances[i] ) THEN
          aqiiri := dqiir.inspected_instances[i];
          IF pmidq_get_measured_type_name( aqiiri.representative_measured_value ) <> pmdtn THEN
            RETURN( FALSE );
          END_IF;
        END_IF;
        IF 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES' 
            IN TYPEOF( dqiir.inspected_instances[i] ) THEN
          aqirie := dqiir.inspected_instances[i];
          REPEAT j := 1 TO SIZEOF( aqirie.extreme_instances ) BY 1;
            IF pmidq_get_measured_type_name( aqirie.extreme_instances[j].measured_value ) <> pmdtn THEN
              RETURN( FALSE );
            END_IF;
          END_REPEAT;
        END_IF;
      END_REPEAT;
    END_IF;
    RETURN( TRUE );

  END_FUNCTION; -- pmidq_validate_measured_type (line:48082 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static 
  func PMIDQ_VALIDATE_MEASURED_TYPE( 
    IR: eDATA_QUALITY_INSPECTION_REPORT.PRef? , 
    CR: eA3M_PMI_DATA_QUALITY_CRITERION.PRef? 
   ) -> SDAI.LOGICAL {

    //CACHE LOOKUP
    let _params = SDAI.ParameterList( IR, CR )
    if case .available(let _cached_value) = _pmidq_validate_measured_type__cache.cachedValue(params: _params) {
      return _cached_value as! SDAI.LOGICAL
    }

    //PARAMETER VALUES
    var IR = IR; SDAI.TOUCH(var: &IR)
    var CR = CR; SDAI.TOUCH(var: &CR)

    //LOCAL
    var AQICRI: eA3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM.PRef? 
    var AQIIRI: eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef? 
    var AQIRIE: eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.PRef? 
    var DQICR: eDATA_QUALITY_INSPECTION_CRITERION_REPORT.PRef? 
    var DQIIR: eDATA_QUALITY_INSPECTION_INSTANCE_REPORT.PRef? 
    var PMDTN: nPMIDQ_MEASURED_DATA_TYPE_NAME? 
    //END_LOCAL

    //BODY
    //
    let _TEMP1 /* nPMIDQ_MEASURED_DATA_TYPE_NAME? */ = CR?.MEASURED_DATA_TYPE
    PMDTN = _TEMP1
    //
    let _TEMP2 /* SDAI.LOGICAL */ = SDAI.TYPEOF( IR, IS: eDATA_QUALITY_INSPECTION_CRITERION_REPORT.self )
    if SDAI.IS_TRUE( _TEMP2 ) {
      DQICR = eDATA_QUALITY_INSPECTION_CRITERION_REPORT.PRef(/*eDATA_QUALITY_INSPECTION_REPORT.PRef*/IR)
      if let incrementControl/*SDAI.INTEGER*/ = SDAI.FROM(/*SDAI.INTEGER*/1, TO:/*SDAI.INTEGER*/SDAI.SIZEOF( 
          DQICR?.STATISTICAL_VALUES )) {
        for I in incrementControl {
          //
          let _TEMP3 /* SDAI.LOGICAL */ = SDAI.TYPEOF( DQICR?.STATISTICAL_VALUES?[I], 
            IS: eA3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM.self )
          if SDAI.IS_TRUE( _TEMP3 ) {
            //
            let _TEMP4 /* SDAI.SET<eDATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM.PRef>[1:2] ? */ = DQICR?.STATISTICAL_VALUES
            let _TEMP5 /* eDATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM.PRef? */ = _TEMP4?[I]
            AQICRI = eA3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM.PRef(/*
              eDATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM.PRef*/_TEMP5)
            //
            let _TEMP6 /* sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT? */ = AQICRI?.REPRESENTATIVE_MEASURED_VALUE
            let _TEMP7 /* nPMIDQ_MEASURED_DATA_TYPE_NAME? */ = PMIDQ_GET_MEASURED_TYPE_NAME( 
                _TEMP6 )
            let _TEMP8 /* SDAI.LOGICAL */ = _TEMP7 .!=. PMDTN
            if SDAI.IS_TRUE( _TEMP8 ) {
              return _pmidq_validate_measured_type__cache.updateCache(params: _params, value: SDAI.UNWRAP(
                SDAI.LOGICAL(SDAI.FALSE)))
            }
          }
        }
      }
    }
    //
    let _TEMP9 /* SDAI.LOGICAL */ = SDAI.TYPEOF( IR, IS: eDATA_QUALITY_INSPECTION_INSTANCE_REPORT.self )
    if SDAI.IS_TRUE( _TEMP9 ) {
      DQIIR = eDATA_QUALITY_INSPECTION_INSTANCE_REPORT.PRef(/*eDATA_QUALITY_INSPECTION_REPORT.PRef*/IR)
      if let incrementControl/*SDAI.INTEGER*/ = SDAI.FROM(/*SDAI.INTEGER*/1, TO:/*SDAI.INTEGER*/SDAI.SIZEOF( 
          DQIIR?.INSPECTED_INSTANCES )) {
        for I in incrementControl {
          //
          let _TEMP10 /* SDAI.LOGICAL */ = SDAI.TYPEOF( DQIIR?.INSPECTED_INSTANCES?[I], 
            IS: eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.self )
          if SDAI.IS_TRUE( _TEMP10 ) {
            //
            let _TEMP11 /* SDAI.LIST<eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef>[1:?] ? */ = DQIIR?.INSPECTED_INSTANCES
            let _TEMP12 /* eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef? */ = _TEMP11?[I]
            AQIIRI = eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef(/*
              eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef*/_TEMP12)
            //
            let _TEMP13 /* sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT? */ = AQIIRI?.REPRESENTATIVE_MEASURED_VALUE
            let _TEMP14 /* nPMIDQ_MEASURED_DATA_TYPE_NAME? */ = PMIDQ_GET_MEASURED_TYPE_NAME( 
                _TEMP13 )
            let _TEMP15 /* SDAI.LOGICAL */ = _TEMP14 .!=. PMDTN
            if SDAI.IS_TRUE( _TEMP15 ) {
              return _pmidq_validate_measured_type__cache.updateCache(params: _params, value: SDAI.UNWRAP(
                SDAI.LOGICAL(SDAI.FALSE)))
            }
          }
          //
          let _TEMP16 /* SDAI.LOGICAL */ = SDAI.TYPEOF( DQIIR?.INSPECTED_INSTANCES?[I], 
            IS: eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.self )
          if SDAI.IS_TRUE( _TEMP16 ) {
            //
            let _TEMP17 /* SDAI.LIST<eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef>[1:?] ? */ = DQIIR?.INSPECTED_INSTANCES
            let _TEMP18 /* eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef? */ = _TEMP17?[I]
            AQIRIE = eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.PRef(/*
              eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.PRef*/_TEMP18)
            if let incrementControl/*SDAI.INTEGER*/ = SDAI.FROM(/*SDAI.INTEGER*/1, TO:/*SDAI.INTEGER*/
                SDAI.SIZEOF( AQIRIE?.EXTREME_INSTANCES )) {
              for J in incrementControl {
                //
                let _TEMP19 /* SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>[1:?] ? */ = AQIRIE?.EXTREME_INSTANCES
                let _TEMP20 /* eA3M_EXTREME_INSTANCE.PRef? */ = _TEMP19?[J]
                let _TEMP21 /* sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT? */ = _TEMP20?.MEASURED_VALUE
                let _TEMP22 /* nPMIDQ_MEASURED_DATA_TYPE_NAME? */ = PMIDQ_GET_MEASURED_TYPE_NAME( 
                    _TEMP21 )
                let _TEMP23 /* SDAI.LOGICAL */ = _TEMP22 .!=. PMDTN
                if SDAI.IS_TRUE( _TEMP23 ) {
                  return _pmidq_validate_measured_type__cache.updateCache(params: _params, value: SDAI.UNWRAP(
                    SDAI.LOGICAL(SDAI.FALSE)))
                }
              }
            }
          }
        }
      }
    }
    return _pmidq_validate_measured_type__cache.updateCache(params: _params, value: SDAI.UNWRAP(SDAI.LOGICAL(
      SDAI.TRUE)))
  }

}

//MARK: - function result cache
private let _pmidq_validate_measured_type__cache = SDAI.FunctionResultCache(
  label: "PMIDQ_VALIDATE_MEASURED_TYPE",
  controller: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.schemaDefinition )

