/* file: a3m_instance_report_item_with_extreme_instances.swift 	 generated: Sat Feb 28 18:16:17 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY a3m_instance_report_item_with_extreme_instances
    SUBTYPE OF ( a3m_data_quality_inspection_instance_report_item );
      extreme_instances  : LIST [1 : ?] OF a3m_extreme_instance;
  END_ENTITY; -- a3m_instance_report_item_with_extreme_instances (line:7393 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	representation_item
    ATTR:  name,	TYPE: label -- EXPLICIT


  SUPER- ENTITY(2)	data_quality_inspection_instance_report_item
    ATTR:  inspected_elements,	TYPE: SET [1 : ?] OF inspected_element_select -- EXPLICIT
      -- possibly overridden by
          ENTITY: shape_data_quality_inspection_instance_report_item,	TYPE: SET [1 : ?] OF inspected_shape_element_select
          ENTITY: externally_conditioned_data_quality_inspection_instance_report_item,	TYPE: SET [1 : ?] OF inspected_ecdq_element_select


  SUPER- ENTITY(3)	a3m_data_quality_inspection_instance_report_item
    ATTR:  representative_measured_value,	TYPE: a3m_data_quality_measured_value_select -- EXPLICIT

    ATTR:  value_type_to_report,	TYPE: summary_stats_value_type -- EXPLICIT


  ENTITY(SELF)	a3m_instance_report_item_with_extreme_instances
    ATTR:  extreme_instances,	TYPE: LIST [1 : ?] OF a3m_extreme_instance -- EXPLICIT


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY a3m_instance_report_item_with_extreme_instances
    SUBTYPE OF ( a3m_data_quality_inspection_instance_report_item );
      extreme_instances  : LIST [1 : ?] OF a3m_extreme_instance;
  END_ENTITY; -- a3m_instance_report_item_with_extreme_instances (line:7393 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM``
	2.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM``
	3.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM``

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES/PartialEntity``
*/
  public final class eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.PartialEntity

    //MARK: SUPERTYPES
    public let super_eREPRESENTATION_ITEM: eREPRESENTATION_ITEM 	// [1]
    public let super_eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM: eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM 	// [2]
    public let super_eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM: eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM 	// [3]
    public var super_eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES: eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES { return self } 	// [4]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM`` )
    public var INSPECTED_ELEMENTS: SDAI.SET<sINSPECTED_ELEMENT_SELECT>/*[1:?]*/  {
      get {
        let originalValue = super_eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.partialEntity
          ._inspected_elements
        let value = SDAI.UNWRAP( SDAI.SET<sINSPECTED_ELEMENT_SELECT>( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.partialEntity
        let SELF = super_eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM; SDAI.TOUCH(let:SELF)
        partial._inspected_elements = SDAI.UNWRAP(SDAI.SET<sINSPECTED_ELEMENT_SELECT>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM`` )
    public var VALUE_TYPE_TO_REPORT: nSUMMARY_STATS_VALUE_TYPE {
      get {
        let originalValue = super_eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.partialEntity
          ._value_type_to_report
        let value = SDAI.UNWRAP( nSUMMARY_STATS_VALUE_TYPE( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.partialEntity
        partial._value_type_to_report = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM`` )
    public var REPRESENTATIVE_MEASURED_VALUE: sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT {
      get {
        let originalValue = super_eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.partialEntity
          ._representative_measured_value
        let value = SDAI.UNWRAP( sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.partialEntity
        partial._representative_measured_value = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES`` )
    public var EXTREME_INSTANCES: SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>/*[1:?]*/  {
      get {
        let originalValue = self.partialEntity._extreme_instances
        let value = SDAI.UNWRAP( SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        let SELF = self; SDAI.TOUCH(let:SELF)
        partial._extreme_instances = SDAI.UNWRAP(SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>(
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?), 
          newValue))
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eREPRESENTATION_ITEM`` )
    public var NAME: tLABEL {
      get {
        let originalValue = super_eREPRESENTATION_ITEM.partialEntity._name
        let value = SDAI.UNWRAP( tLABEL( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eREPRESENTATION_ITEM.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eREPRESENTATION_ITEM.self) else { return nil }
      self.super_eREPRESENTATION_ITEM = super1

      guard let super2 = complexEntity?.entityReference(eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.self) else { return nil }
      self.super_eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM = super2

      guard let super3 = complexEntity?.entityReference(eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.self) else { return nil }
      self.super_eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM = super3

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "A3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES", 
        type: self, explicitAttributeCount: 1)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eREPRESENTATION_ITEM.self)
      entityDef.add(supertype: eDATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.self)
      entityDef.add(supertype: eA3M_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM.self)
      entityDef.add(supertype: eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "INSPECTED_ELEMENTS", 
        keyPath: \eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.INSPECTED_ELEMENTS, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "VALUE_TYPE_TO_REPORT", 
        keyPath: \eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.VALUE_TYPE_TO_REPORT, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "REPRESENTATIVE_MEASURED_VALUE", 
        keyPath: \eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.REPRESENTATIVE_MEASURED_VALUE, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "EXTREME_INSTANCES", 
        keyPath: \eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.EXTREME_INSTANCES, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "NAME", 
        keyPath: \eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.NAME, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY a3m_instance_report_item_with_extreme_instances
      SUBTYPE OF ( a3m_data_quality_inspection_instance_report_item );
        extreme_instances  : LIST [1 : ?] OF a3m_extreme_instance;
    END_ENTITY; -- a3m_instance_report_item_with_extreme_instances (line:7393 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eA3M_INSTANCE_REPORT_ITEM_WITH_EXTREME_INSTANCES.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _extreme_instances: SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>/*[1:?]*/  // PLAIN EXPLICIT ATTRIBUTE

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._extreme_instances.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._extreme_instances.value.isValueEqualOptionally(to: rhs._extreme_instances.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._extreme_instances.value.isValueEqualOptionally(to: rhs._extreme_instances.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(EXTREME_INSTANCES: SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>/*[1:?]*/ ) {

        self._extreme_instances = 
        SDAI.LIST<eA3M_EXTREME_INSTANCE.PRef>(from: EXTREME_INSTANCES.asSwiftType, 
          bound1:SDAI.UNWRAP(1), bound2:(nil as SDAI.INTEGER?))

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( EXTREME_INSTANCES: original._extreme_instances )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 1
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: SDAI.LIST<
          eA3M_EXTREME_INSTANCE.PRef>.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]EXTREME_INSTANCES for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( EXTREME_INSTANCES: p0 )
      }
    }
  }
}
