/* file: a3m_data_quality_target_accuracy_association.swift 	 generated: Sat Feb 28 19:28:50 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY a3m_data_quality_target_accuracy_association;
      id                      : identifier;
      name                    : label;
      description             : OPTIONAL text;
      accuracy_specification  : shape_measurement_accuracy;
      target_to_associate     : a3m_accuracy_associated_target_select;
  END_ENTITY; -- a3m_data_quality_target_accuracy_association (line:7137 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  ENTITY(SELF)	a3m_data_quality_target_accuracy_association
    ATTR:  id,	TYPE: identifier -- EXPLICIT

    ATTR:  name,	TYPE: label -- EXPLICIT

    ATTR:  description,	TYPE: OPTIONAL text -- EXPLICIT

    ATTR:  accuracy_specification,	TYPE: shape_measurement_accuracy -- EXPLICIT

    ATTR:  target_to_associate,	TYPE: a3m_accuracy_associated_target_select -- EXPLICIT


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY a3m_data_quality_target_accuracy_association;
      id                      : identifier;
      name                    : label;
      description             : OPTIONAL text;
      accuracy_specification  : shape_measurement_accuracy;
      target_to_associate     : a3m_accuracy_associated_target_select;
  END_ENTITY; -- a3m_data_quality_target_accuracy_association (line:7137 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:

- SUBTYPES:

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION/PartialEntity``
*/
  public final class eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION : SDAI.EntityReference, SDAI.DualModeReference, 
    SDAI.SimpleEntityType, @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.PartialEntity

    //MARK: SUPERTYPES
    public var super_eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION: eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION { return self } 	// [1]

    //MARK: SUBTYPES

    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION`` )
    public var DESCRIPTION: tTEXT?  {
      get {
        let originalValue = self.partialEntity._description
        let value = tTEXT( originalValue )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._description = newValue
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION`` )
    public var TARGET_TO_ASSOCIATE: sA3M_ACCURACY_ASSOCIATED_TARGET_SELECT {
      get {
        let originalValue = self.partialEntity._target_to_associate
        let value = SDAI.UNWRAP( sA3M_ACCURACY_ASSOCIATED_TARGET_SELECT( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._target_to_associate = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION`` )
    public var ID: tIDENTIFIER {
      get {
        let originalValue = self.partialEntity._id
        let value = SDAI.UNWRAP( tIDENTIFIER( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._id = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION`` )
    public var ACCURACY_SPECIFICATION: eSHAPE_MEASUREMENT_ACCURACY.PRef {
      get {
        let originalValue = self.partialEntity._accuracy_specification
        let value = SDAI.UNWRAP( eSHAPE_MEASUREMENT_ACCURACY.PRef( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._accuracy_specification = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION`` )
    public var NAME: tLABEL {
      get {
        let originalValue = self.partialEntity._name
        let value = SDAI.UNWRAP( tLABEL( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = self.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }

    //SIMPLE ENTITY REFERENCE
    /// initialize simple entity reference from single partial entity
    public convenience init?(_ partial:PartialEntity) {
      let complex = SDAI.ComplexEntity(entities:[partial])
      self.init(complex: complex)
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "A3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION", 
        type: self, explicitAttributeCount: 5)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "DESCRIPTION", 
        keyPath: \eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.DESCRIPTION, 
        kind: .explicitOptional, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "TARGET_TO_ASSOCIATE", 
        keyPath: \eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.TARGET_TO_ASSOCIATE, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "ID", 
        keyPath: \eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.ID, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "ACCURACY_SPECIFICATION", 
        keyPath: \eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.ACCURACY_SPECIFICATION, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: true)
      entityDef.addAttribute(name: "NAME", 
        keyPath: \eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.NAME, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY a3m_data_quality_target_accuracy_association;
        id                      : identifier;
        name                    : label;
        description             : OPTIONAL text;
        accuracy_specification  : shape_measurement_accuracy;
        target_to_associate     : a3m_accuracy_associated_target_select;
    END_ENTITY; -- a3m_data_quality_target_accuracy_association (line:7137 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eA3M_DATA_QUALITY_TARGET_ACCURACY_ASSOCIATION.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _id: tIDENTIFIER // PLAIN EXPLICIT ATTRIBUTE

      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _name: tLABEL // PLAIN EXPLICIT ATTRIBUTE

      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _description: tTEXT?  // PLAIN EXPLICIT ATTRIBUTE

      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _accuracy_specification: eSHAPE_MEASUREMENT_ACCURACY.PRef // PLAIN EXPLICIT ATTRIBUTE

      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      public internal(set) var _target_to_associate: sA3M_ACCURACY_ASSOCIATED_TARGET_SELECT // PLAIN EXPLICIT ATTRIBUTE

      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._id.value.hashAsValue(into: &hasher, visited: &complexEntities)
        self._name.value.hashAsValue(into: &hasher, visited: &complexEntities)
        self._description?.value.hashAsValue(into: &hasher, visited: &complexEntities)
        self._accuracy_specification.value.hashAsValue(into: &hasher, visited: &complexEntities)
        self._target_to_associate.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._id.value.isValueEqualOptionally(to: rhs._id.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        if let comp = self._name.value.isValueEqualOptionally(to: rhs._name.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        if let comp = self._description?.value.isValueEqualOptionally(to: rhs._description?.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        if let comp = self._accuracy_specification.value.isValueEqualOptionally(to: rhs._accuracy_specification.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        if let comp = self._target_to_associate.value.isValueEqualOptionally(to: rhs._target_to_associate.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._id.value.isValueEqualOptionally(to: rhs._id.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._name.value.isValueEqualOptionally(to: rhs._name.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._description?.value.isValueEqualOptionally(to: rhs._description?.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._accuracy_specification.value.isValueEqualOptionally(to: rhs._accuracy_specification.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._target_to_associate.value.isValueEqualOptionally(to: rhs._target_to_associate.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(
        ID: tIDENTIFIER, 
        NAME: tLABEL, 
        DESCRIPTION: tTEXT? , 
        ACCURACY_SPECIFICATION: eSHAPE_MEASUREMENT_ACCURACY.PRef, 
        TARGET_TO_ASSOCIATE: sA3M_ACCURACY_ASSOCIATED_TARGET_SELECT
      ) {

        self._id = ID
        self._name = NAME
        self._description = DESCRIPTION
        self._accuracy_specification = ACCURACY_SPECIFICATION
        self._target_to_associate = TARGET_TO_ASSOCIATE

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( ID: original._id, NAME: original._name, DESCRIPTION: original._description, ACCURACY_SPECIFICATION: original._accuracy_specification, TARGET_TO_ASSOCIATE: original._target_to_associate )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 5
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverRequiredParameter(as: tIDENTIFIER.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]ID for partial entity(\(Self.entityName)) constructor"); return nil }

        guard case .success(let p1) = exchangeStructure.recoverRequiredParameter(as: tLABEL.self, from: parameters[1])
        else { exchangeStructure.add(errorContext: "while recovering parameter [1]NAME for partial entity(\(Self.entityName)) constructor"); return nil }

        guard case .success(let p2) = exchangeStructure.recoverOptionalParameter(as: tTEXT.self, from: parameters[2])
        else { exchangeStructure.add(errorContext: "while recovering parameter [2]DESCRIPTION for partial entity(\(Self.entityName)) constructor"); return nil }

        guard case .success(let p3) = exchangeStructure.recoverRequiredParameter(as: 
          eSHAPE_MEASUREMENT_ACCURACY.PRef.self, from: parameters[3])
        else { exchangeStructure.add(errorContext: "while recovering parameter [3]ACCURACY_SPECIFICATION for partial entity(\(Self.entityName)) constructor"); return nil }

        guard case .success(let p4) = exchangeStructure.recoverRequiredParameter(as: 
          sA3M_ACCURACY_ASSOCIATED_TARGET_SELECT.self, from: parameters[4])
        else { exchangeStructure.add(errorContext: "while recovering parameter [4]TARGET_TO_ASSOCIATE for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( ID: p0, NAME: p1, DESCRIPTION: p2, ACCURACY_SPECIFICATION: p3, TARGET_TO_ASSOCIATE: p4 )
      }
    }
  }
}
