/* file: action_method_to_select_from.swift 	 generated: Sat Feb 28 18:16:17 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -ENTITY DEFINITION in EXPRESS
/*

  ENTITY action_method_to_select_from
    SUBTYPE OF ( action_method );
      number_of_elements  : count_measure;
    WHERE
      wr1: ( number_of_elements >= 1 );
      wr2: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'
               + 'ACTION_METHOD_RELATIONSHIP.RELATING_METHOD'  ) ) >= number_of_elements );
  END_ENTITY; -- action_method_to_select_from (line:7749 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES
/*
  SUPER- ENTITY(1)	action_method
    ATTR:  name,	TYPE: label -- EXPLICIT

    ATTR:  description,	TYPE: OPTIONAL text -- EXPLICIT

    ATTR:  consequence,	TYPE: text -- EXPLICIT

    ATTR:  purpose,	TYPE: text -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: decision_point,	TYPE: text	(as DERIVED)


  ENTITY(SELF)	action_method_to_select_from
    ATTR:  number_of_elements,	TYPE: count_measure -- EXPLICIT (DYNAMIC)
      -- possibly overridden by
          ENTITY: decision_point,	TYPE: count_measure	(as DERIVED)


  SUB- ENTITY(3)	decision_point
    REDCR: number_of_elements,	TYPE: count_measure -- DERIVED (DYNAMIC)
      := 1
      -- OVERRIDING ENTITY: action_method_to_select_from

    REDCR: purpose,	TYPE: text -- DERIVED (DYNAMIC)
      := 'decision'
      -- OVERRIDING ENTITY: action_method


*/


//MARK: - Entity Reference

/** ENTITY reference
- EXPRESS source code:
```express
  ENTITY action_method_to_select_from
    SUBTYPE OF ( action_method );
      number_of_elements  : count_measure;
    WHERE
      wr1: ( number_of_elements >= 1 );
      wr2: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'
               + 'ACTION_METHOD_RELATIONSHIP.RELATING_METHOD'  ) ) >= number_of_elements );
  END_ENTITY; -- action_method_to_select_from (line:7749 file:ap242ed4_mim_lf_TY.exp)

```

- SUPERTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD``

- SUBTYPES:
	1.	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eDECISION_POINT``

- PARTIAL ENTITY:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD_TO_SELECT_FROM/PartialEntity``
*/
  public final class eACTION_METHOD_TO_SELECT_FROM : SDAI.EntityReference, SDAI.DualModeReference, 
    @unchecked Sendable {
    /// persistent entity reference type
    public typealias PRef = SDAI.PersistentEntityReference<eACTION_METHOD_TO_SELECT_FROM>

    /// persistent entity reference
    public var pRef: PRef { PRef(self) }


    //MARK: PARTIAL ENTITY
    public override class var partialEntityType: SDAI.PartialEntity.Type {
      eACTION_METHOD_TO_SELECT_FROM.PartialEntity.self
    }
    /// partial entity reference
    public let partialEntity: eACTION_METHOD_TO_SELECT_FROM.PartialEntity

    //MARK: SUPERTYPES
    public let super_eACTION_METHOD: eACTION_METHOD 	// [1]
    public var super_eACTION_METHOD_TO_SELECT_FROM: eACTION_METHOD_TO_SELECT_FROM { return self } 	// [2]

    //MARK: SUBTYPES
    public var sub_eDECISION_POINT: eDECISION_POINT? {	// [3]
      return self.complexEntity.entityReference(eDECISION_POINT.self)
    }


    //MARK: ATTRIBUTES
    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var DESCRIPTION: tTEXT?  {
      get {
        let originalValue = super_eACTION_METHOD.partialEntity._description
        let value = tTEXT( originalValue )
        return value
      }
      set(newValue) {
        let partial = super_eACTION_METHOD.partialEntity
        partial._description = newValue
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var PURPOSE: tTEXT {
      get {
        if let resolved = eACTION_METHOD.PartialEntity._purpose__provider(complex: self.complexEntity) {
          let originalValue = resolved._purpose__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = super_eACTION_METHOD.partialEntity._purpose
          let value = SDAI.UNWRAP( tTEXT( originalValue ) )
          return value
        }
      }
      set(newValue) {
        if let _ = eACTION_METHOD.PartialEntity._purpose__provider(complex: self.complexEntity) { return }

        let partial = super_eACTION_METHOD.partialEntity
        partial._purpose = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT(DYNAMIC)__ attribute
    /// - origin: SELF( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD_TO_SELECT_FROM`` )
    public var NUMBER_OF_ELEMENTS: tCOUNT_MEASURE {
      get {
        if let resolved = eACTION_METHOD_TO_SELECT_FROM.PartialEntity._number_of_elements__provider(complex: self.complexEntity) {
          let originalValue = resolved._number_of_elements__getter(complex: self.complexEntity)
          return originalValue
        }
        else {
          let originalValue = self.partialEntity._number_of_elements
          let value = SDAI.UNWRAP( tCOUNT_MEASURE( originalValue ) )
          return value
        }
      }
      set(newValue) {
        if let _ = eACTION_METHOD_TO_SELECT_FROM.PartialEntity._number_of_elements__provider(complex: self.complexEntity) { return }

        let partial = self.partialEntity
        partial._number_of_elements = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var CONSEQUENCE: tTEXT {
      get {
        let originalValue = super_eACTION_METHOD.partialEntity._consequence
        let value = SDAI.UNWRAP( tTEXT( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eACTION_METHOD.partialEntity
        partial._consequence = SDAI.UNWRAP(newValue)
      }
    }

    /// __EXPLICIT__ attribute
    /// - origin: SUPER( ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD`` )
    public var NAME: tLABEL {
      get {
        let originalValue = super_eACTION_METHOD.partialEntity._name
        let value = SDAI.UNWRAP( tLABEL( originalValue ) )
        return value
      }
      set(newValue) {
        let partial = super_eACTION_METHOD.partialEntity
        partial._name = SDAI.UNWRAP(newValue)
      }
    }


    //MARK: INITIALIZERS
    /// initialize from entity reference (type conversion form)
    public convenience init?(_ entityRef: SDAI.EntityReference?) {
      let complex = entityRef?.complexEntity
      self.init(complex: complex)
    }

    /// initialize from complex entity
    public required init?(complex complexEntity: SDAI.ComplexEntity?) {
      guard let partial = complexEntity?.partialEntityInstance(eACTION_METHOD_TO_SELECT_FROM.PartialEntity.self) else { return nil }
      self.partialEntity = partial

      guard let super1 = complexEntity?.entityReference(eACTION_METHOD.self) else { return nil }
      self.super_eACTION_METHOD = super1

      super.init(complex: complexEntity)
    }

    /// initialize from SDAI generic type
    public required convenience init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let entityRef = generic?.entityReference else { return nil }
      self.init(complex: entityRef.complexEntity)
    }

    /// initialize from SDAI select type (type conversion form)
    public convenience init?<S: SDAI.SelectType>(_ select: S?) { self.init(possiblyFrom: select) }
    /// initialize from complex entity (type conversion form)
    public convenience init?(_ complex: SDAI.ComplexEntity?) { self.init(complex: complex) }


    //MARK: WHERE RULE VALIDATION (ENTITY)
    public override class func validateWhereRules(instance:SDAI.EntityReference?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      guard let instance = instance as? Self else { return [:] }

      var result = super.validateWhereRules(instance:instance, prefix:prefix)
      result[prefix + " .WHERE_wr1"] = eACTION_METHOD_TO_SELECT_FROM.PartialEntity.WHERE_wr1(SELF: instance.pRef)
      result[prefix + " .WHERE_wr2"] = eACTION_METHOD_TO_SELECT_FROM.PartialEntity.WHERE_wr2(SELF: instance.pRef)
      return result
    }


    //MARK: DICTIONARY DEFINITION
    public class override var entityDefinition: SDAIDictionarySchema.EntityDefinition { _entityDefinition }
    private static let _entityDefinition: SDAIDictionarySchema.EntityDefinition = createEntityDefinition()

    private static func createEntityDefinition() -> SDAIDictionarySchema.EntityDefinition {
      let entityDef = SDAIDictionarySchema.EntityDefinition.Prototype( 
        name: "ACTION_METHOD_TO_SELECT_FROM", 
        type: self, explicitAttributeCount: 1)

      //MARK: SUPERTYPE REGISTRATIONS
      entityDef.add(supertype: eACTION_METHOD.self)
      entityDef.add(supertype: eACTION_METHOD_TO_SELECT_FROM.self)

      //MARK: ATTRIBUTE REGISTRATIONS
      entityDef.addAttribute(name: "DESCRIPTION", 
        keyPath: \eACTION_METHOD_TO_SELECT_FROM.DESCRIPTION, 
        kind: .explicitOptional, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "PURPOSE", 
        keyPath: \eACTION_METHOD_TO_SELECT_FROM.PURPOSE, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "NUMBER_OF_ELEMENTS", 
        keyPath: \eACTION_METHOD_TO_SELECT_FROM.NUMBER_OF_ELEMENTS, 
        kind: .explicit, source: .thisEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "CONSEQUENCE", 
        keyPath: \eACTION_METHOD_TO_SELECT_FROM.CONSEQUENCE, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)
      entityDef.addAttribute(name: "NAME", 
        keyPath: \eACTION_METHOD_TO_SELECT_FROM.NAME, 
        kind: .explicit, source: .superEntity, mayYieldEntityReference: false)

      return entityDef.freeze()
    }



//MARK: - Partial Entity

/** Partial Entity
- EXPRESS source code:
```express

    ENTITY action_method_to_select_from
      SUBTYPE OF ( action_method );
        number_of_elements  : count_measure;
      WHERE
        wr1: ( number_of_elements >= 1 );
        wr2: ( SIZEOF( USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'
                 + 'ACTION_METHOD_RELATIONSHIP.RELATING_METHOD'  ) ) >= number_of_elements );
    END_ENTITY; -- action_method_to_select_from (line:7749 file:ap242ed4_mim_lf_TY.exp)

```
- ENTITY reference:
	+	``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/eACTION_METHOD_TO_SELECT_FROM``
*/
    public final class PartialEntity : SDAI.PartialEntity, @unchecked Sendable {
      public override class var entityReferenceType: SDAI.EntityReference.Type {
        eACTION_METHOD_TO_SELECT_FROM.self
      }

      //ATTRIBUTES
      /// EXPLICIT ATTRIBUTE 
      @_documentation(visibility:public)
      /// - see the corresponding attribute accessor in the entity reference definition for the attribute value dynamic lookup logic
      public internal(set) var _number_of_elements: tCOUNT_MEASURE?  // PLAIN EXPLICIT ATTRIBUTE

      internal static func _number_of_elements__provider(complex: SDAI.ComplexEntity) -> eACTION_METHOD_TO_SELECT_FROM__NUMBER_OF_ELEMENTS__provider? {
        let resolved = complex.resolvePartialEntityInstance(from: [eDECISION_POINT.PartialEntity.typeIdentity
          ])
        return resolved as? eACTION_METHOD_TO_SELECT_FROM__NUMBER_OF_ELEMENTS__provider
      }

      //PARTIAL COMPLEX ENTITY SUPPORT - to fill up the explicit attribute values with the baseComplex's redeclared derived attribute value so that the partial complex entities constructed from the baseComplex can provide the consistent attribute values
      final public override class func fixupPartialComplexEntityAttributes(partialComplex: SDAI.ComplexEntity, baseComplex: SDAI.ComplexEntity) {
        guard let pe = partialComplex.partialEntityInstance(eACTION_METHOD_TO_SELECT_FROM.PartialEntity.self) else { return }

        if pe._number_of_elements == nil, 
          self._number_of_elements__provider(complex: partialComplex) == nil, 
          let base__number_of_elements__provider = self._number_of_elements__provider(complex: baseComplex) {
          pe._number_of_elements = base__number_of_elements__provider._number_of_elements__getter(complex: baseComplex)
        }
      }
      public override var typeMembers: Set<SDAI.STRING> {
        var members = Set<SDAI.STRING>()
        members.insert(SDAI.STRING(Self.typeName))
        return members
      }


      //VALUE COMPARISON SUPPORT
      public override func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
        super.hashAsValue(into: &hasher, visited: &complexEntities)
        self._number_of_elements?.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }

      public override func isValueEqual(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
        guard let rhs = rhs as? Self else { return false }
        if !super.isValueEqual(to: rhs, visited: &comppairs) { return false }
        if let comp = self._number_of_elements?.value.isValueEqualOptionally(to: rhs._number_of_elements?.value, visited: &comppairs)	{
          if !comp { return false }
        }
        else { return false }
        return true
      }

      public override func isValueEqualOptionally(to rhs: SDAI.PartialEntity, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
        guard let rhs = rhs as? Self else { return false }
        var result: Bool? = true
        if let comp = super.isValueEqualOptionally(to: rhs, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        if let comp = self._number_of_elements?.value.isValueEqualOptionally(to: rhs._number_of_elements?.value, visited: &comppairs) {
          if !comp { return false }
        }
        else { result = nil }
        return result
      }


      //MARK: WHERE RULES (ENTITY)
      public static func WHERE_wr1(SELF: eACTION_METHOD_TO_SELECT_FROM.PRef?) -> SDAI.LOGICAL {
        guard let SELF = SELF else { return SDAI.UNKNOWN }
//
        let _TEMP1 /* SDAI.LOGICAL */ = SELF.NUMBER_OF_ELEMENTS >= SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
        return _TEMP1
      }
      public static func WHERE_wr2(SELF: eACTION_METHOD_TO_SELECT_FROM.PRef?) -> SDAI.LOGICAL {
        guard let SELF = SELF else { return SDAI.UNKNOWN }
//
        let _TEMP1 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = SDAI.USEDIN(T: SELF, 
          ROLE: \AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.eACTION_METHOD_RELATIONSHIP.RELATING_METHOD)
        let _TEMP2 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP1 )
        let _TEMP3 /* SDAI.LOGICAL */ = _TEMP2 >= SELF.NUMBER_OF_ELEMENTS
        return _TEMP3
      }

      //EXPRESS IMPLICIT PARTIAL ENTITY CONSTRUCTOR
      /// initialize from explicit attribute values
      public init(NUMBER_OF_ELEMENTS: tCOUNT_MEASURE? ) {

        self._number_of_elements = NUMBER_OF_ELEMENTS

        super.init(asAbstractSuperclass:())
      }

      //PARTIAL ENTITY COPY CONSTRUCTOR
      /// copy constructor
      public required convenience init(from original:SDAI.PartialEntity) {
        let original = original as! Self
        self.init( NUMBER_OF_ELEMENTS: original._number_of_elements )
      }

      //p21 PARTIAL ENTITY CONSTRUCTOR
      /// initialize from ISO 10303-21 exchange structure parameters
      public required convenience init?(
        parameters: [P21Decode.ExchangeStructure.Parameter],
        exchangeStructure: P21Decode.ExchangeStructure
      ) {
        let numParams = 1
        guard parameters.count == numParams
        else { exchangeStructure.error = "number of p21 parameters(\(parameters.count)) are different from expected(\(numParams)) for partial entity(\(Self.entityName)) constructor"; return nil }

        guard case .success(let p0) = exchangeStructure.recoverOmittableParameter(as: tCOUNT_MEASURE.self, from: parameters[0])
        else { exchangeStructure.add(errorContext: "while recovering parameter [0]NUMBER_OF_ELEMENTS for partial entity(\(Self.entityName)) constructor"); return nil }

        self.init( NUMBER_OF_ELEMENTS: p0 )
      }
    }
  }
}

//MARK: - Entity Dynamic Attribute Protocols
internal protocol eACTION_METHOD_TO_SELECT_FROM__NUMBER_OF_ELEMENTS__provider {
  @_documentation(visibility:public)
  func _number_of_elements__getter(complex: SDAI.ComplexEntity) -> 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tCOUNT_MEASURE
}
