/* file: machining_feature_definition_constraints.swift 	 generated: Sun Mar  1 18:06:18 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
    derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
    will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -RULE definition in EXPRESS

/** RULE definition
- EXPRESS source code:
```express

  RULE machining_feature_definition_constraints FOR ( feature_definition );

    LOCAL
      mfds : SET OF feature_definition := [];
    END_LOCAL;
    mfds := QUERY ( temp <* feature_definition | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'
        + 'MACHINING_FEATURE_DEFINITION'  IN TYPEOF( temp ) ) );

  WHERE
    wr1: ( SIZEOF( QUERY ( mfd <* mfds | ( NOT ( SIZEOF( QUERY ( pdr <* 
             get_property_definition_representations( mfd ) | ( 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN 
             TYPEOF( pdr.used_representation ) ) ) ) <= 1 ) ) ) ) = 0 );
    wr2: ( SIZEOF( QUERY ( mfd <* mfds | ( NOT ( SIZEOF( QUERY ( pd <* USEDIN( mfd, 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION'  ) | ( NOT ( 
             SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  )
             | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_REPRESENTATION_WITH_PARAMETERS' IN 
             TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* impl_rep.
             used_representation.items | ( ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PLACEMENT' IN 
             TYPEOF( it ) ) AND ( it.name = 'orientation' ) ) ) ) = 1 ) ) ) ) = 0 ) ) ) ) = 0 ) ) ) ) = 0 );
    wr3: ( SIZEOF( QUERY ( mfd <* mfds | ( NOT ( ( NOT ( SIZEOF( [
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ROUND_HOLE' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.BOSS' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.OUTSIDE_PROFILE' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.REMOVAL_VOLUME' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.FLAT_FACE' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POCKET' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROTRUSION' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.RIB_TOP' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ROUNDED_END' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SLOT' , 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.STEP' ] * TYPEOF( mfds ) ) = 1 ) ) OR ( 
             SIZEOF( QUERY ( pdr <* get_property_definition_representations( mfd ) | ( ( 
             'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PLANAR_SHAPE_REPRESENTATION'  IN TYPEOF( pdr.
             used_representation ) ) AND ( pdr.used_representation.name = 'maximum feature limit' ) ) ) ) >= 
             0 ) ) ) ) ) = 0 );

  END_RULE; -- machining_feature_definition_constraints (line:53702 file:ap242ed4_mim_lf_TY.exp)

```

*/

  public static
  func MACHINING_FEATURE_DEFINITION_CONSTRAINTS( 
    allComplexEntities: AnySequence<SDAI.ComplexEntity> ) -> [SDAI.WhereLabel:SDAI.LOGICAL] {

    //ENTITY REFERENCES
    let FEATURE_DEFINITION = SDAI.POPULATION(OF: eFEATURE_DEFINITION.self, FROM: allComplexEntities); SDAI.TOUCH(let: FEATURE_DEFINITION)

    //LOCAL
    var MFDS: SDAI.SET<eFEATURE_DEFINITION.PRef>?  = SDAI.SET<eFEATURE_DEFINITION.PRef>(SDAI.EMPTY_AGGREGATE); SDAI.TOUCH(var: &MFDS)
    //END_LOCAL

    //BODY
    //
    let _TEMP1 /* SDAI.SET<eFEATURE_DEFINITION.PRef> */ = FEATURE_DEFINITION
      .QUERY{ TEMP in 
        // QUERY BODY
        //
        let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( TEMP, IS: sMACHINING_FEATURE_DEFINITION.self )
        return _TEMP1
        // END QUERY BODY
      }
    MFDS = _TEMP1

    //WHERE
    var _conformance: [SDAI.WhereLabel:SDAI.LOGICAL] = [:]
    //
    let _TEMP2 /* SDAI.SET<eFEATURE_DEFINITION.PRef>? */ = MFDS?
      .QUERY{ MFD in 
        // QUERY BODY
        //
        let _TEMP1 /* SDAI.SET<ePROPERTY_DEFINITION_REPRESENTATION.PRef>? */ = 
            GET_PROPERTY_DEFINITION_REPRESENTATIONS( sCHARACTERIZED_DEFINITION(/*eFEATURE_DEFINITION.PRef*/
            MFD) )
        let _TEMP2 /* SDAI.SET<ePROPERTY_DEFINITION_REPRESENTATION.PRef>? */ = _TEMP1?
          .QUERY{ PDR in 
            // QUERY BODY
            //
            let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( PDR.USED_REPRESENTATION, 
              IS: eSHAPE_REPRESENTATION_WITH_PARAMETERS.self )
            return _TEMP1
            // END QUERY BODY
          }
        let _TEMP3 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP2 )
        let _TEMP4 /* SDAI.LOGICAL */ = _TEMP3 <= SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
        let _TEMP5 /* SDAI.LOGICAL */ =  !_TEMP4
        return _TEMP5
        // END QUERY BODY
      }
    let _TEMP3 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP2 )
    let _TEMP4 /* SDAI.LOGICAL */ = _TEMP3 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
    let WHERE_wr1 = _TEMP4
    _conformance["WHERE_wr1"] = WHERE_wr1

    //
    let _TEMP5 /* SDAI.SET<eFEATURE_DEFINITION.PRef>? */ = MFDS?
      .QUERY{ MFD in 
        // QUERY BODY
        //
        let _TEMP1 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = SDAI.USEDIN(T: MFD, 
          ROLE: \AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePROPERTY_DEFINITION.DEFINITION)
        let _TEMP2 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = _TEMP1
          .QUERY{ PD in 
            // QUERY BODY
            //
            let _TEMP1 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = SDAI.USEDIN(T: PD, 
              ROLE: \AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ePROPERTY_DEFINITION_REPRESENTATION
              .DEFINITION)
            let _TEMP2 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = _TEMP1
              .QUERY{ PDR in 
                // QUERY BODY
                //
                let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( PDR.USED_REPRESENTATION, 
                  IS: eSHAPE_REPRESENTATION_WITH_PARAMETERS.self )
                return _TEMP1
                // END QUERY BODY
              }
            let _TEMP3 /* SDAI.BAG<SDAI.GENERIC_ENTITY> */ = _TEMP2
              .QUERY{ IMPL_REP in 
                // QUERY BODY
                //
                let _TEMP1 /* runtime? */ = /*runtime*/IMPL_REP.USED_REPRESENTATION
                let _TEMP2 /* runtime? */ = /*runtime*/_TEMP1?.ITEMS
                let _TEMP3 /* runtime? */ = /*runtime*/_TEMP2?
                  .QUERY{ IT in 
                    // QUERY BODY
                    //
                    let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( IT, IS: ePLACEMENT.self )
                    let _TEMP2 /* runtime?? */ = /*runtime*/IT.NAME
                    let _TEMP3 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(/*runtime*/_TEMP2) .==. SDAI.FORCE_OPTIONAL(
                      SDAI.STRING("orientation"))
                    let _TEMP4 /* SDAI.LOGICAL */ = _TEMP1 && _TEMP3
                    return _TEMP4
                    // END QUERY BODY
                  }
                let _TEMP4 /* SDAI.INTEGER? */ = SDAI.SIZEOF( SDAI.AGGREGATE<SDAI.GENERIC>(/*runtime*/_TEMP3) )
                let _TEMP5 /* SDAI.LOGICAL */ = _TEMP4 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
                let _TEMP6 /* SDAI.LOGICAL */ =  !_TEMP5
                return _TEMP6
                // END QUERY BODY
              }
            let _TEMP4 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP3 )
            let _TEMP5 /* SDAI.LOGICAL */ = _TEMP4 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
            let _TEMP6 /* SDAI.LOGICAL */ =  !_TEMP5
            return _TEMP6
            // END QUERY BODY
          }
        let _TEMP3 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP2 )
        let _TEMP4 /* SDAI.LOGICAL */ = _TEMP3 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
        let _TEMP5 /* SDAI.LOGICAL */ =  !_TEMP4
        return _TEMP5
        // END QUERY BODY
      }
    let _TEMP6 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP5 )
    let _TEMP7 /* SDAI.LOGICAL */ = _TEMP6 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
    let WHERE_wr2 = _TEMP7
    _conformance["WHERE_wr2"] = WHERE_wr2

    //
    let _TEMP8 /* SDAI.SET<eFEATURE_DEFINITION.PRef>? */ = MFDS?
      .QUERY{ MFD in 
        // QUERY BODY
        //
        let _TEMP1 /* SDAI.AGGREGATE<SDAI.STRING> */ =  ([ 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ROUND_HOLE")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.BOSS")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.OUTSIDE_PROFILE")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.REMOVAL_VOLUME")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.FLAT_FACE")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.POCKET")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROTRUSION")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.RIB_TOP")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.ROUNDED_END")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SLOT")), 
            SDAI.AIE(SDAI.STRING("AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.STEP")) ] 
            as [SDAI.AggregationInitializerElement<SDAI.STRING>]) 
        let _TEMP2 /* SDAI.SET<SDAI.STRING> */ = SDAI.TYPEOF( MFDS )
        let _TEMP3 /* SDAI.SET<SDAI.STRING>? */ = SDAI.FORCE_OPTIONAL(_TEMP1) * SDAI.FORCE_OPTIONAL(_TEMP2)
        let _TEMP4 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP3 )
        let _TEMP5 /* SDAI.LOGICAL */ = _TEMP4 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(1))
        let _TEMP6 /* SDAI.LOGICAL */ =  !_TEMP5
        let _TEMP7 /* SDAI.SET<ePROPERTY_DEFINITION_REPRESENTATION.PRef>? */ = 
            GET_PROPERTY_DEFINITION_REPRESENTATIONS( sCHARACTERIZED_DEFINITION(/*eFEATURE_DEFINITION.PRef*/
            MFD) )
        let _TEMP8 /* SDAI.SET<ePROPERTY_DEFINITION_REPRESENTATION.PRef>? */ = _TEMP7?
          .QUERY{ PDR in 
            // QUERY BODY
            //
            let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( PDR.USED_REPRESENTATION, 
              IS: ePLANAR_SHAPE_REPRESENTATION.self )
            let _TEMP2 /* eREPRESENTATION.PRef? */ = PDR.USED_REPRESENTATION
            let _TEMP3 /* tLABEL? */ = _TEMP2?.NAME
            let _TEMP4 /* SDAI.LOGICAL */ = _TEMP3 .==. SDAI.FORCE_OPTIONAL(SDAI.STRING("maximum feature limit"))
            let _TEMP5 /* SDAI.LOGICAL */ = _TEMP1 && _TEMP4
            return _TEMP5
            // END QUERY BODY
          }
        let _TEMP9 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP8 )
        let _TEMP10 /* SDAI.LOGICAL */ = _TEMP9 >= SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
        let _TEMP11 /* SDAI.LOGICAL */ = _TEMP6 || _TEMP10
        let _TEMP12 /* SDAI.LOGICAL */ =  !_TEMP11
        return _TEMP12
        // END QUERY BODY
      }
    let _TEMP9 /* SDAI.INTEGER? */ = SDAI.SIZEOF( _TEMP8 )
    let _TEMP10 /* SDAI.LOGICAL */ = _TEMP9 .==. SDAI.FORCE_OPTIONAL(SDAI.INTEGER(0))
    let WHERE_wr3 = _TEMP10
    _conformance["WHERE_wr3"] = WHERE_wr3


    return _conformance
  }

}
