/* file: tsdq_measured_data_type_name.swift 	 generated: Thu Apr  2 16:34:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE tsdq_measured_data_type_name = a3m_data_quality_measured_data_type_name;
  WHERE
    wr1: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_boolean_value );
    wr2: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_others );
    wr3: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_positive_length_measure );
    wr4: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_positive_plane_angle_measure );
  END_TYPE; -- tsdq_measured_data_type_name (line:6940 file:ap242ed4_mim_lf_TY.exp)

*/

//MARK: - Defined data type (type alias)

/** Defined data type (type alias)
- EXPRESS source code:
```express
  TYPE tsdq_measured_data_type_name = a3m_data_quality_measured_data_type_name;
  WHERE
    wr1: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_boolean_value );
    wr2: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_others );
    wr3: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_positive_length_measure );
    wr4: ( SELF <> a3m_data_quality_measured_data_type_name.pmidqm_positive_plane_angle_measure );
  END_TYPE; -- tsdq_measured_data_type_name (line:6940 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public struct nTSDQ_MEASURED_DATA_TYPE_NAME: TypeHierarchy.nTSDQ_MEASURED_DATA_TYPE_NAME__TypeBehavior {
    public typealias Supertype = nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME
    public typealias FundamentalType = Supertype.FundamentalType
    public typealias Value = Supertype.Value
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TSDQ_MEASURED_DATA_TYPE_NAME"
    public static let bareTypeName: String = "TSDQ_MEASURED_DATA_TYPE_NAME"
    public var typeMembers: Set<SDAI.STRING> {
      var members = rep.typeMembers
      members.insert(SDAI.STRING(Self.typeName))
      return members
    }

    public var rep: Supertype
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) {
      rep = Supertype(fundamental: fundamental)
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let repval = Supertype.convert(fromGeneric: generic) else { return nil }
      rep = repval
    }

    //MARK: WHERE RULES (DEFINED TYPE)
    public static func WHERE_wr1(SELF: nTSDQ_MEASURED_DATA_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME?? */ = 
        nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME.PMIDQM_BOOLEAN_VALUE
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr2(SELF: nTSDQ_MEASURED_DATA_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME?? */ = 
        nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME.PMIDQM_OTHERS
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr3(SELF: nTSDQ_MEASURED_DATA_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME?? */ = 
        nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME.PMIDQM_POSITIVE_LENGTH_MEASURE
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr4(SELF: nTSDQ_MEASURED_DATA_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME?? */ = 
        nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME.PMIDQM_POSITIVE_PLANE_ANGLE_MEASURE
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }

    //WHERE RULE VALIDATION (DEFINED TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      let prefix2 = prefix + "\\nTSDQ_MEASURED_DATA_TYPE_NAME"
      var result = Supertype.validateWhereRules(instance:instance?.rep, prefix:prefix2)

      result[prefix2 + ".WHERE_wr1"] = nTSDQ_MEASURED_DATA_TYPE_NAME.WHERE_wr1(SELF: instance)
      result[prefix2 + ".WHERE_wr2"] = nTSDQ_MEASURED_DATA_TYPE_NAME.WHERE_wr2(SELF: instance)
      result[prefix2 + ".WHERE_wr3"] = nTSDQ_MEASURED_DATA_TYPE_NAME.WHERE_wr3(SELF: instance)
      result[prefix2 + ".WHERE_wr4"] = nTSDQ_MEASURED_DATA_TYPE_NAME.WHERE_wr4(SELF: instance)
      return result
    }

  }
}


//MARK: - DEFINED TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nTSDQ_MEASURED_DATA_TYPE_NAME__TypeBehavior: 
  nA3M_DATA_QUALITY_MEASURED_DATA_TYPE_NAME__Subtype {}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nTSDQ_MEASURED_DATA_TYPE_NAME__Subtype: nTSDQ_MEASURED_DATA_TYPE_NAME__TypeBehavior
{}
}

