/* file: a3m_data_quality_measured_value_select.swift 	 generated: Fri Mar  6 17:48:00 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE a3m_data_quality_measured_value_select = SELECT
    ( area_measure (*TYPE*),
     boolean_value (*TYPE*),
     count_measure (*TYPE*),
     positive_length_measure (*TYPE*),
     positive_plane_angle_measure (*TYPE*),
     ratio_measure (*TYPE*) );
  END_TYPE; -- a3m_data_quality_measured_value_select (line:218 file:ap242ed4_mim_lf_TY.exp)

*/


//MARK: - ALL DEFINED ATTRIBUTES FOR SELECT
/*
  CASE: area_measure (*TYPE*): area_measure

  CASE: boolean_value (*TYPE*): boolean_value

  CASE: count_measure (*TYPE*): count_measure

  CASE: positive_length_measure (*TYPE*): positive_length_measure

  CASE: positive_plane_angle_measure (*TYPE*): positive_plane_angle_measure

  CASE: ratio_measure (*TYPE*): ratio_measure

*/

/** SELECT type
- EXPRESS source code:
```express
  TYPE a3m_data_quality_measured_value_select = SELECT
    ( area_measure (*TYPE*),
     boolean_value (*TYPE*),
     count_measure (*TYPE*),
     positive_length_measure (*TYPE*),
     positive_plane_angle_measure (*TYPE*),
     ratio_measure (*TYPE*) );
  END_TYPE; -- a3m_data_quality_measured_value_select (line:218 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT : SDAI.Value, TypeHierarchy.sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT__TypeBehavior {

    /// SELECT case (TYPE)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/tAREA_MEASURE`` (TYPE)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    @_documentation(visibility:public)
    case _AREA_MEASURE(tAREA_MEASURE)	// (TYPE)

    /// SELECT case (TYPE)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/tBOOLEAN_VALUE`` (TYPE)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    @_documentation(visibility:public)
    case _BOOLEAN_VALUE(tBOOLEAN_VALUE)	// (TYPE)

    /// SELECT case (TYPE)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/tCOUNT_MEASURE`` (TYPE)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    @_documentation(visibility:public)
    case _COUNT_MEASURE(tCOUNT_MEASURE)	// (TYPE)

    /// SELECT case (TYPE)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/tPOSITIVE_LENGTH_MEASURE`` (TYPE)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    @_documentation(visibility:public)
    case _POSITIVE_LENGTH_MEASURE(tPOSITIVE_LENGTH_MEASURE)	// (TYPE)

    /// SELECT case (TYPE)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/tPOSITIVE_PLANE_ANGLE_MEASURE`` (TYPE)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    @_documentation(visibility:public)
    case _POSITIVE_PLANE_ANGLE_MEASURE(tPOSITIVE_PLANE_ANGLE_MEASURE)	// (TYPE)

    /// SELECT case (TYPE)
      ///
      /// - target: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/tRATIO_MEASURE`` (TYPE)
      /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    @_documentation(visibility:public)
    case _RATIO_MEASURE(tRATIO_MEASURE)	// (TYPE)

    //MARK: - CONSTRUCTORS
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) { self = fundamental }

    /// initialize from the underlying type value
    public init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?){
      guard let underlyingType = underlyingType else { return nil }

      if let base = underlyingType as? tAREA_MEASURE {
        self = ._AREA_MEASURE(base)
      }
      else if let base = underlyingType as? tBOOLEAN_VALUE {
        self = ._BOOLEAN_VALUE(base)
      }
      else if let base = underlyingType as? tCOUNT_MEASURE {
        self = ._COUNT_MEASURE(base)
      }
      else if let base = underlyingType as? tPOSITIVE_LENGTH_MEASURE {
        self = ._POSITIVE_LENGTH_MEASURE(base)
      }
      else if let base = underlyingType as? tPOSITIVE_PLANE_ANGLE_MEASURE {
        self = ._POSITIVE_PLANE_ANGLE_MEASURE(base)
      }
      else if let base = underlyingType as? tRATIO_MEASURE {
        self = ._RATIO_MEASURE(base)
      }
      else if let fundamental = underlyingType.asFundamentalType as? tAREA_MEASURE.FundamentalType {
        self = ._AREA_MEASURE( tAREA_MEASURE(fundamental: fundamental) )
      }
      else if let fundamental = underlyingType.asFundamentalType as? tBOOLEAN_VALUE.FundamentalType {
        self = ._BOOLEAN_VALUE( tBOOLEAN_VALUE(fundamental: fundamental) )
      }
      else if let fundamental = underlyingType.asFundamentalType as? tCOUNT_MEASURE.FundamentalType {
        self = ._COUNT_MEASURE( tCOUNT_MEASURE(fundamental: fundamental) )
      }
      else if let fundamental = underlyingType.asFundamentalType as? tPOSITIVE_LENGTH_MEASURE.FundamentalType {
        self = ._POSITIVE_LENGTH_MEASURE( tPOSITIVE_LENGTH_MEASURE(fundamental: fundamental) )
      }
      else if let fundamental = underlyingType.asFundamentalType as? tPOSITIVE_PLANE_ANGLE_MEASURE.FundamentalType {
        self = ._POSITIVE_PLANE_ANGLE_MEASURE( tPOSITIVE_PLANE_ANGLE_MEASURE(fundamental: fundamental) )
      }
      else if let fundamental = underlyingType.asFundamentalType as? tRATIO_MEASURE.FundamentalType {
        self = ._RATIO_MEASURE( tRATIO_MEASURE(fundamental: fundamental) )
      }
      else { return nil }
    }

    /// initialize from complex entity
    public init?(possiblyFrom complex: SDAI.ComplexEntity?) {
      return nil
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let select = generic else { return nil }

      if let fundamental = select as? Self {
        self.init(fundamental: fundamental)
      }
      else if let base = tAREA_MEASURE.convert(fromGeneric: select) {
        self = ._AREA_MEASURE(base)
      }
      else if let base = tBOOLEAN_VALUE.convert(fromGeneric: select) {
        self = ._BOOLEAN_VALUE(base)
      }
      else if let base = tCOUNT_MEASURE.convert(fromGeneric: select) {
        self = ._COUNT_MEASURE(base)
      }
      else if let base = tPOSITIVE_LENGTH_MEASURE.convert(fromGeneric: select) {
        self = ._POSITIVE_LENGTH_MEASURE(base)
      }
      else if let base = tPOSITIVE_PLANE_ANGLE_MEASURE.convert(fromGeneric: select) {
        self = ._POSITIVE_PLANE_ANGLE_MEASURE(base)
      }
      else if let base = tRATIO_MEASURE.convert(fromGeneric: select) {
        self = ._RATIO_MEASURE(base)
      }
      else { return nil }
    }

    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "A3M_DATA_QUALITY_MEASURED_VALUE_SELECT"

    /// initialize from ISO 10303-21 exchange structure typed parameters
    public init?(
      p21typedParam: P21Decode.ExchangeStructure.TypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      guard let keyword = p21typedParam.keyword.asStandardKeyword else { exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"; return nil }

      switch(keyword) {
      case tAREA_MEASURE.bareTypeName:
        guard let base = tAREA_MEASURE(p21typedParam: p21typedParam, from: exchangeStructure) else { exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) select value"); return nil }
        self = ._AREA_MEASURE(base)

      case tBOOLEAN_VALUE.bareTypeName:
        guard let base = tBOOLEAN_VALUE(p21typedParam: p21typedParam, from: exchangeStructure) else { exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) select value"); return nil }
        self = ._BOOLEAN_VALUE(base)

      case tCOUNT_MEASURE.bareTypeName:
        guard let base = tCOUNT_MEASURE(p21typedParam: p21typedParam, from: exchangeStructure) else { exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) select value"); return nil }
        self = ._COUNT_MEASURE(base)

      case tPOSITIVE_LENGTH_MEASURE.bareTypeName:
        guard let base = tPOSITIVE_LENGTH_MEASURE(p21typedParam: p21typedParam, from: exchangeStructure) else { exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) select value"); return nil }
        self = ._POSITIVE_LENGTH_MEASURE(base)

      case tPOSITIVE_PLANE_ANGLE_MEASURE.bareTypeName:
        guard let base = tPOSITIVE_PLANE_ANGLE_MEASURE(p21typedParam: p21typedParam, from: exchangeStructure) else { exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) select value"); return nil }
        self = ._POSITIVE_PLANE_ANGLE_MEASURE(base)

      case tRATIO_MEASURE.bareTypeName:
        guard let base = tRATIO_MEASURE(p21typedParam: p21typedParam, from: exchangeStructure) else { exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) select value"); return nil }
        self = ._RATIO_MEASURE(base)

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21typedParam)) while resolving \(Self.bareTypeName) select value"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public init?(
      p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter,
      from exchangeStructure: P21Decode.ExchangeStructure
    ) {
      switch p21untypedParam {
      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantEntityName(let name):
          guard let entity = exchangeStructure.resolve(constantEntityName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: entity.complexEntity)

        case .entityInstanceName(let name):
          guard let complex = exchangeStructure.resolve(entityInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) instance"); return nil }
          self.init(possiblyFrom: complex)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
          return nil
        }

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) select instance"
        return nil
      }
    }

    /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init?(p21omittedParamfrom exchangeStructure: P21Decode.ExchangeStructure) {
      return nil
    }


    //MARK: - NON-ENTITY UNDERLYING TYPE REFERENCES
    /// underlying type reference (NON-ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    public var super_tAREA_MEASURE: tAREA_MEASURE? {
      switch self {
      case ._AREA_MEASURE(let selectValue): return selectValue
      default: return nil
      }
    }

    /// underlying type reference (NON-ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    public var super_tBOOLEAN_VALUE: tBOOLEAN_VALUE? {
      switch self {
      case ._BOOLEAN_VALUE(let selectValue): return selectValue
      default: return nil
      }
    }

    /// underlying type reference (NON-ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    public var super_tCOUNT_MEASURE: tCOUNT_MEASURE? {
      switch self {
      case ._COUNT_MEASURE(let selectValue): return selectValue
      default: return nil
      }
    }

    /// underlying type reference (NON-ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    public var super_tPOSITIVE_LENGTH_MEASURE: tPOSITIVE_LENGTH_MEASURE? {
      switch self {
      case ._POSITIVE_LENGTH_MEASURE(let selectValue): return selectValue
      default: return nil
      }
    }

    /// underlying type reference (NON-ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    public var super_tPOSITIVE_PLANE_ANGLE_MEASURE: tPOSITIVE_PLANE_ANGLE_MEASURE? {
      switch self {
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selectValue): return selectValue
      default: return nil
      }
    }

    /// underlying type reference (NON-ENTITY)
    ///
    /// - defined in: ``AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF/sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT``
    public var super_tRATIO_MEASURE: tRATIO_MEASURE? {
      switch self {
      case ._RATIO_MEASURE(let selectValue): return selectValue
      default: return nil
      }
    }



    //MARK: - SDAI.Value
    public func isValueEqual<T: SDAI.Value>(to rhs: T) -> Bool {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.value.isValueEqual(to: rhs)
      case ._BOOLEAN_VALUE(let selection): return selection.value.isValueEqual(to: rhs)
      case ._COUNT_MEASURE(let selection): return selection.value.isValueEqual(to: rhs)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.value.isValueEqual(to: rhs)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.value.isValueEqual(to: rhs)
      case ._RATIO_MEASURE(let selection): return selection.value.isValueEqual(to: rhs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?) -> Bool? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._BOOLEAN_VALUE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._COUNT_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      case ._RATIO_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs)
      }
    }

    public func hashAsValue(into hasher: inout Hasher, visited complexEntities: inout Set<SDAI.ComplexEntity>) {
      switch self {
      case ._AREA_MEASURE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._BOOLEAN_VALUE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._COUNT_MEASURE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._POSITIVE_LENGTH_MEASURE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      case ._RATIO_MEASURE(let selection): selection.value.hashAsValue(into: &hasher, visited: &complexEntities)
      }
    }

    public func isValueEqual<T: SDAI.Value>(to rhs: T, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._BOOLEAN_VALUE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._COUNT_MEASURE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      case ._RATIO_MEASURE(let selection): return selection.value.isValueEqual(to: rhs, visited: &comppairs)
      }
    }

    public func isValueEqualOptionally<T: SDAI.Value>(to rhs: T?, visited comppairs: inout Set<SDAI.ComplexPair>) -> Bool? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._BOOLEAN_VALUE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._COUNT_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      case ._RATIO_MEASURE(let selection): return selection.value.isValueEqualOptionally(to: rhs, visited: &comppairs)
      }
    }


    //MARK: SDAIGenericTypeBase
    public func copy() -> Self {
      switch self {
      case ._AREA_MEASURE(let selection): return ._AREA_MEASURE(selection.copy())
      case ._BOOLEAN_VALUE(let selection): return ._BOOLEAN_VALUE(selection.copy())
      case ._COUNT_MEASURE(let selection): return ._COUNT_MEASURE(selection.copy())
      case ._POSITIVE_LENGTH_MEASURE(let selection): return ._POSITIVE_LENGTH_MEASURE(selection.copy())
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return ._POSITIVE_PLANE_ANGLE_MEASURE(selection.copy())
      case ._RATIO_MEASURE(let selection): return ._RATIO_MEASURE(selection.copy())
      }
    }

    //MARK: SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members: Set<SDAI.STRING> = [SDAI.STRING(Self.typeName)]
      switch self {
      case ._AREA_MEASURE(let selection): members.formUnion(selection.typeMembers)
      case ._BOOLEAN_VALUE(let selection): members.formUnion(selection.typeMembers)
      case ._COUNT_MEASURE(let selection): members.formUnion(selection.typeMembers)
      case ._POSITIVE_LENGTH_MEASURE(let selection): members.formUnion(selection.typeMembers)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): members.formUnion(selection.typeMembers)
      case ._RATIO_MEASURE(let selection): members.formUnion(selection.typeMembers)
      }
      return members
    }

    public var entityReference: SDAI.EntityReference? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.entityReference
      case ._BOOLEAN_VALUE(let selection): return selection.entityReference
      case ._COUNT_MEASURE(let selection): return selection.entityReference
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.entityReference
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.entityReference
      case ._RATIO_MEASURE(let selection): return selection.entityReference
      }
    }
    public var stringValue: SDAI.STRING? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.stringValue
      case ._BOOLEAN_VALUE(let selection): return selection.stringValue
      case ._COUNT_MEASURE(let selection): return selection.stringValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.stringValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.stringValue
      case ._RATIO_MEASURE(let selection): return selection.stringValue
      }
    }
    public var binaryValue: SDAI.BINARY? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.binaryValue
      case ._BOOLEAN_VALUE(let selection): return selection.binaryValue
      case ._COUNT_MEASURE(let selection): return selection.binaryValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.binaryValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.binaryValue
      case ._RATIO_MEASURE(let selection): return selection.binaryValue
      }
    }
    public var logicalValue: SDAI.LOGICAL? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.logicalValue
      case ._BOOLEAN_VALUE(let selection): return selection.logicalValue
      case ._COUNT_MEASURE(let selection): return selection.logicalValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.logicalValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.logicalValue
      case ._RATIO_MEASURE(let selection): return selection.logicalValue
      }
    }
    public var booleanValue: SDAI.BOOLEAN? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.booleanValue
      case ._BOOLEAN_VALUE(let selection): return selection.booleanValue
      case ._COUNT_MEASURE(let selection): return selection.booleanValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.booleanValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.booleanValue
      case ._RATIO_MEASURE(let selection): return selection.booleanValue
      }
    }
    public var numberValue: SDAI.NUMBER? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.numberValue
      case ._BOOLEAN_VALUE(let selection): return selection.numberValue
      case ._COUNT_MEASURE(let selection): return selection.numberValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.numberValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.numberValue
      case ._RATIO_MEASURE(let selection): return selection.numberValue
      }
    }
    public var realValue: SDAI.REAL? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.realValue
      case ._BOOLEAN_VALUE(let selection): return selection.realValue
      case ._COUNT_MEASURE(let selection): return selection.realValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.realValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.realValue
      case ._RATIO_MEASURE(let selection): return selection.realValue
      }
    }
    public var integerValue: SDAI.INTEGER? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.integerValue
      case ._BOOLEAN_VALUE(let selection): return selection.integerValue
      case ._COUNT_MEASURE(let selection): return selection.integerValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.integerValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.integerValue
      case ._RATIO_MEASURE(let selection): return selection.integerValue
      }
    }
    public var genericEnumValue: SDAI.GenericEnumValue? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.genericEnumValue
      case ._BOOLEAN_VALUE(let selection): return selection.genericEnumValue
      case ._COUNT_MEASURE(let selection): return selection.genericEnumValue
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.genericEnumValue
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.genericEnumValue
      case ._RATIO_MEASURE(let selection): return selection.genericEnumValue
      }
    }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._BOOLEAN_VALUE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._COUNT_MEASURE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      case ._RATIO_MEASURE(let selection): return selection.arrayOptionalValue(elementType:elementType)
      }
    }
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.arrayValue(elementType:elementType)
      case ._BOOLEAN_VALUE(let selection): return selection.arrayValue(elementType:elementType)
      case ._COUNT_MEASURE(let selection): return selection.arrayValue(elementType:elementType)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.arrayValue(elementType:elementType)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.arrayValue(elementType:elementType)
      case ._RATIO_MEASURE(let selection): return selection.arrayValue(elementType:elementType)
      }
    }
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.listValue(elementType:elementType)
      case ._BOOLEAN_VALUE(let selection): return selection.listValue(elementType:elementType)
      case ._COUNT_MEASURE(let selection): return selection.listValue(elementType:elementType)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.listValue(elementType:elementType)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.listValue(elementType:elementType)
      case ._RATIO_MEASURE(let selection): return selection.listValue(elementType:elementType)
      }
    }
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.bagValue(elementType:elementType)
      case ._BOOLEAN_VALUE(let selection): return selection.bagValue(elementType:elementType)
      case ._COUNT_MEASURE(let selection): return selection.bagValue(elementType:elementType)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.bagValue(elementType:elementType)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.bagValue(elementType:elementType)
      case ._RATIO_MEASURE(let selection): return selection.bagValue(elementType:elementType)
      }
    }
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.setValue(elementType:elementType)
      case ._BOOLEAN_VALUE(let selection): return selection.setValue(elementType:elementType)
      case ._COUNT_MEASURE(let selection): return selection.setValue(elementType:elementType)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.setValue(elementType:elementType)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.setValue(elementType:elementType)
      case ._RATIO_MEASURE(let selection): return selection.setValue(elementType:elementType)
      }
    }
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? {
      switch self {
      case ._AREA_MEASURE(let selection): return selection.enumValue(enumType:enumType)
      case ._BOOLEAN_VALUE(let selection): return selection.enumValue(enumType:enumType)
      case ._COUNT_MEASURE(let selection): return selection.enumValue(enumType:enumType)
      case ._POSITIVE_LENGTH_MEASURE(let selection): return selection.enumValue(enumType:enumType)
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selection): return selection.enumValue(enumType:enumType)
      case ._RATIO_MEASURE(let selection): return selection.enumValue(enumType:enumType)
      }
    }

    //MARK: SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3M_DATA_QUALITY_MEASURED_VALUE_SELECT"
    public var asFundamentalType: FundamentalType { return self }

    //MARK: SDAI.EntityReferenceYielding
    public var entityReferences: AnySequence<SDAI.EntityReference> {
      switch self {
      case ._AREA_MEASURE: return AnySequence<SDAI.EntityReference>(EmptyCollection<SDAI.EntityReference>())
      case ._BOOLEAN_VALUE: return AnySequence<SDAI.EntityReference>(EmptyCollection<SDAI.EntityReference>())
      case ._COUNT_MEASURE: return AnySequence<SDAI.EntityReference>(EmptyCollection<SDAI.EntityReference>())
      case ._POSITIVE_LENGTH_MEASURE: return AnySequence<SDAI.EntityReference>(EmptyCollection<SDAI.EntityReference>())
      case ._POSITIVE_PLANE_ANGLE_MEASURE: return AnySequence<SDAI.EntityReference>(EmptyCollection<SDAI.EntityReference>())
      case ._RATIO_MEASURE: return AnySequence<SDAI.EntityReference>(EmptyCollection<SDAI.EntityReference>())
      }
    }

    public var persistentEntityReferences: AnySequence<SDAI.GenericPersistentEntityReference> {
      switch self {
      case ._AREA_MEASURE: return AnySequence<SDAI.GenericPersistentEntityReference>(EmptyCollection<SDAI.GenericPersistentEntityReference>())
      case ._BOOLEAN_VALUE: return AnySequence<SDAI.GenericPersistentEntityReference>(EmptyCollection<SDAI.GenericPersistentEntityReference>())
      case ._COUNT_MEASURE: return AnySequence<SDAI.GenericPersistentEntityReference>(EmptyCollection<SDAI.GenericPersistentEntityReference>())
      case ._POSITIVE_LENGTH_MEASURE: return AnySequence<SDAI.GenericPersistentEntityReference>(EmptyCollection<SDAI.GenericPersistentEntityReference>())
      case ._POSITIVE_PLANE_ANGLE_MEASURE: return AnySequence<SDAI.GenericPersistentEntityReference>(EmptyCollection<SDAI.GenericPersistentEntityReference>())
      case ._RATIO_MEASURE: return AnySequence<SDAI.GenericPersistentEntityReference>(EmptyCollection<SDAI.GenericPersistentEntityReference>())
      }
    }

    public func isHolding(entityReference: SDAI.EntityReference) -> Bool {
      switch self {
      case ._AREA_MEASURE: return false
      case ._BOOLEAN_VALUE: return false
      case ._COUNT_MEASURE: return false
      case ._POSITIVE_LENGTH_MEASURE: return false
      case ._POSITIVE_PLANE_ANGLE_MEASURE: return false
      case ._RATIO_MEASURE: return false
      }
    }


    //MARK: SDAIAggregationBehavior
    public var aggregationHiBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationHiIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoBound: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationLoIndex: Int? {
      switch self {
      default: return nil
      }
    }
    public var aggregationSize: Int? {
      switch self {
      default: return nil
      }
    }

    //MARK: WHERE RULE VALIDATION (SELECT TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      var result: SDAI.WhereRuleValidationRecords = [:]
      switch instance {
      case ._AREA_MEASURE(let selectValue): result = tAREA_MEASURE.validateWhereRules(instance: selectValue, 
        prefix:prefix + "\\AREA_MEASURE")
      case ._BOOLEAN_VALUE(let selectValue): 
        result = tBOOLEAN_VALUE.validateWhereRules(instance: selectValue, prefix:prefix + "\\BOOLEAN_VALUE")
      case ._COUNT_MEASURE(let selectValue): 
        result = tCOUNT_MEASURE.validateWhereRules(instance: selectValue, prefix:prefix + "\\COUNT_MEASURE")
      case ._POSITIVE_LENGTH_MEASURE(let selectValue): 
        result = tPOSITIVE_LENGTH_MEASURE.validateWhereRules(instance: selectValue, 
        prefix:prefix + "\\POSITIVE_LENGTH_MEASURE")
      case ._POSITIVE_PLANE_ANGLE_MEASURE(let selectValue): 
        result = tPOSITIVE_PLANE_ANGLE_MEASURE.validateWhereRules(instance: selectValue, 
        prefix:prefix + "\\POSITIVE_PLANE_ANGLE_MEASURE")
      case ._RATIO_MEASURE(let selectValue): 
        result = tRATIO_MEASURE.validateWhereRules(instance: selectValue, prefix:prefix + "\\RATIO_MEASURE")
      case nil: break
      }

      return result
    }

  }

}


//MARK: - SELECT TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
public protocol sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT__TypeBehavior: SDAI.SelectType {
  //MARK: GROUP REFERENCES
  var super_tAREA_MEASURE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tAREA_MEASURE? { get }
  var super_tBOOLEAN_VALUE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tBOOLEAN_VALUE? { get }
  var super_tCOUNT_MEASURE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tCOUNT_MEASURE? { get }
  var super_tPOSITIVE_LENGTH_MEASURE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tPOSITIVE_LENGTH_MEASURE? { get }
  var super_tPOSITIVE_PLANE_ANGLE_MEASURE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tPOSITIVE_PLANE_ANGLE_MEASURE? { get }
  var super_tRATIO_MEASURE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tRATIO_MEASURE? { get }

}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT__Subtype: 
  sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT__TypeBehavior, SDAI.DefinedType
where Supertype: sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT__TypeBehavior
{}
}

public extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy.sA3M_DATA_QUALITY_MEASURED_VALUE_SELECT__Subtype {
  //MARK: CONSTRUCTORS
  /// initialize SELECT subtype from complex entity
  init?(possiblyFrom complex: SDAI.ComplexEntity?) {
    self.init(fundamental: FundamentalType(possiblyFrom: complex))
  }

  /// initialize SELECT subtype from the underlying type value
  init?<T: SDAI.UnderlyingType>(possiblyFrom underlyingType: T?) {
    self.init(fundamental: FundamentalType(possiblyFrom: underlyingType))
  }

  /// initialize SELECT subtype from SDAI generic type value
  init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
    self.init(fundamental: FundamentalType.convert(fromGeneric: generic))
  }

  //MARK: GROUP REFERENCES
  var super_tAREA_MEASURE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tAREA_MEASURE? { rep.super_tAREA_MEASURE }
  var super_tBOOLEAN_VALUE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tBOOLEAN_VALUE? { rep.super_tBOOLEAN_VALUE }
  var super_tCOUNT_MEASURE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tCOUNT_MEASURE? { rep.super_tCOUNT_MEASURE }
  var super_tPOSITIVE_LENGTH_MEASURE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tPOSITIVE_LENGTH_MEASURE? { rep.super_tPOSITIVE_LENGTH_MEASURE }
  var super_tPOSITIVE_PLANE_ANGLE_MEASURE: AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tPOSITIVE_PLANE_ANGLE_MEASURE? { rep.super_tPOSITIVE_PLANE_ANGLE_MEASURE }
  var super_tRATIO_MEASURE: 
    AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.tRATIO_MEASURE? { rep.super_tRATIO_MEASURE }

}

