/* file: a3m_data_quality_type_name_for_location_of_extreme_value.swift 	 generated: Sat Feb 28 19:28:50 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE a3m_data_quality_type_name_for_location_of_extreme_value = ENUMERATION OF
    ( tsdqe_others,
     tsdqe_set_of_representative_triangle,
     tsdqe_set_of_tessellated_shell,
     tsdqe_set_of_triangle_edge,
     tsdqe_set_of_triangulated_face,
     tsdqe_triangle_vertex );
  END_TYPE; -- a3m_data_quality_type_name_for_location_of_extreme_value (line:227 file:ap242ed4_mim_lf_TY.exp)

*/


/** ENUMERATION type
- EXPRESS source code:
```express
  TYPE a3m_data_quality_type_name_for_location_of_extreme_value = ENUMERATION OF
    ( tsdqe_others,
     tsdqe_set_of_representative_triangle,
     tsdqe_set_of_tessellated_shell,
     tsdqe_set_of_triangle_edge,
     tsdqe_set_of_triangulated_face,
     tsdqe_triangle_vertex );
  END_TYPE; -- a3m_data_quality_type_name_for_location_of_extreme_value (line:227 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public enum nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE : SDAI.ENUMERATION, SDAI.Value, 
    TypeHierarchy.nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE__TypeBehavior {
    /// ENUMERATION case
    ///
    /// - defined in: ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
    case TSDQE_OTHERS
    /// ENUMERATION case
    ///
    /// - defined in: ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
    case TSDQE_SET_OF_REPRESENTATIVE_TRIANGLE
    /// ENUMERATION case
    ///
    /// - defined in: ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
    case TSDQE_SET_OF_TESSELLATED_SHELL
    /// ENUMERATION case
    ///
    /// - defined in: ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
    case TSDQE_SET_OF_TRIANGLE_EDGE
    /// ENUMERATION case
    ///
    /// - defined in: ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
    case TSDQE_SET_OF_TRIANGULATED_FACE
    /// ENUMERATION case
    ///
    /// - defined in: ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
    case TSDQE_TRIANGLE_VERTEX

    // SDAI.GenericType
    public var typeMembers: Set<SDAI.STRING> {
      var members = Set<SDAI.STRING>()
      members.insert(SDAI.STRING(Self.typeName))
      return members
    }

    public var entityReference: SDAI.EntityReference? {nil}
    public var stringValue: SDAI.STRING? {nil}
    public var binaryValue: SDAI.BINARY? {nil}
    public var logicalValue: SDAI.LOGICAL? {nil}
    public var booleanValue: SDAI.BOOLEAN? {nil}
    public var numberValue: SDAI.NUMBER? {nil}
    public var realValue: SDAI.REAL? {nil}
    public var integerValue: SDAI.INTEGER? {nil}
    public var genericEnumValue: SDAI.GenericEnumValue? { SDAI.GenericEnumValue(self) }
    public func arrayOptionalValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY_OPTIONAL<ELEM>? {nil}
    public func arrayValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.ARRAY<ELEM>? {nil}
    public func listValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.LIST<ELEM>? {nil}
    public func bagValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.BAG<ELEM>? {nil}
    public func setValue<ELEM:SDAI.GenericType>(elementType:ELEM.Type) -> SDAI.SET<ELEM>? {nil}
    public func enumValue<ENUM:SDAI.EnumerationType>(enumType:ENUM.Type) -> ENUM? { return self as? ENUM }

    // SDAI.UnderlyingType
    public typealias FundamentalType = Self
    public static let typeName: String = "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE"
    public var asFundamentalType: FundamentalType { return self }

    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) {
      self = fundamental
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let enumval = generic?.enumValue(enumType: Self.self) else { return nil }
      self = enumval
    }
    // Initializable.ByP21Parameter
    public static let bareTypeName: String = "A3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE"

    /// initialize from ISO 10303-21 exchange structure untyped parameters
    public	init?(p21untypedParam: P21Decode.ExchangeStructure.UntypedParameter, from exchangeStructure: P21Decode.ExchangeStructure) {
      switch p21untypedParam {
      case .enumeration(let enumcase):
        switch enumcase {
        case "TSDQE_OTHERS": self = .TSDQE_OTHERS
        case "TSDQE_SET_OF_REPRESENTATIVE_TRIANGLE": self = .TSDQE_SET_OF_REPRESENTATIVE_TRIANGLE
        case "TSDQE_SET_OF_TESSELLATED_SHELL": self = .TSDQE_SET_OF_TESSELLATED_SHELL
        case "TSDQE_SET_OF_TRIANGLE_EDGE": self = .TSDQE_SET_OF_TRIANGLE_EDGE
        case "TSDQE_SET_OF_TRIANGULATED_FACE": self = .TSDQE_SET_OF_TRIANGULATED_FACE
        case "TSDQE_TRIANGLE_VERTEX": self = .TSDQE_TRIANGLE_VERTEX
        default:
          exchangeStructure.error = "unexpected p21parameter enum case(\(enumcase)) while resolving \(Self.bareTypeName) value"
          return nil
        }

      case .rhsOccurrenceName(let rhsname):
        switch rhsname {
        case .constantValueName(let name):
          guard let generic = exchangeStructure.resolve(constantValueName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) value"); return nil }
          guard let enumValue = generic.enumValue(enumType:Self.self) else { exchangeStructure.error = "constant value(\(name): \(generic)) is not compatible with \(Self.bareTypeName)"; return nil }
          self = enumValue

        case .valueInstanceName(let name):
          guard let param = exchangeStructure.resolve(valueInstanceName: name) else {exchangeStructure.add(errorContext: "while resolving \(Self.bareTypeName) value from \(rhsname)"); return nil }
          self.init(p21param: param, from: exchangeStructure)

        default:
          exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) value"
          return nil
        }

      case .noValue:
        return nil

      default:
        exchangeStructure.error = "unexpected p21parameter(\(p21untypedParam)) while resolving \(Self.bareTypeName) value"
        return nil
      }
    }

  /// initialize from ISO 10303-21 exchange structure omitted parameters
    public init(p21omittedParamfrom exchangeStructure: P21Decode.ExchangeStructure) {
      self = .TSDQE_OTHERS
    }

    //WHERE RULE VALIDATION (ENUMERATION TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      return [:]
    }

  }

  //MARK: -enum case symbol promotions
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
  public static let TSDQE_OTHERS = nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE.TSDQE_OTHERS
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
  public static let TSDQE_SET_OF_REPRESENTATIVE_TRIANGLE = 
    nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE.TSDQE_SET_OF_REPRESENTATIVE_TRIANGLE
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
  public static let TSDQE_SET_OF_TESSELLATED_SHELL = 
    nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE.TSDQE_SET_OF_TESSELLATED_SHELL
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
  public static let TSDQE_SET_OF_TRIANGLE_EDGE = nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE
    .TSDQE_SET_OF_TRIANGLE_EDGE
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
  public static let TSDQE_SET_OF_TRIANGULATED_FACE = 
    nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE.TSDQE_SET_OF_TRIANGULATED_FACE
  /// promoted ENUMERATION case
  ///
  /// - defined in ``nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE``
  public static let TSDQE_TRIANGLE_VERTEX = nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE
    .TSDQE_TRIANGLE_VERTEX
}


//MARK: - ENUMERATION TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE__TypeBehavior: 
  SDAI.EnumerationType {}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE__Subtype: 
  nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE__TypeBehavior, SDAI.DefinedType
where Supertype: nA3M_DATA_QUALITY_TYPE_NAME_FOR_LOCATION_OF_EXTREME_VALUE__TypeBehavior
{}
}

