/* file: a3ma_element_type_name.swift 	 generated: Mon Mar 30 15:41:24 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.2.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE a3ma_element_type_name = a3m_element_type_name;
  WHERE
    wr1: ( SELF <> a3m_element_type_name.etns_connected_edge_set );
    wr2: ( SELF <> a3m_element_type_name.etns_connected_face_set );
    wr3: ( SELF <> a3m_element_type_name.etns_external_representation_item );
    wr4: ( SELF <> a3m_element_type_name.etns_manifold_solid_brep );
    wr5: ( SELF <> a3m_element_type_name.etns_others );
    wr6: ( SELF <> a3m_element_type_name.etns_point_cloud_dataset );
    wr7: ( SELF <> a3m_element_type_name.etns_shell_based_surface_model );
    wr8: ( SELF <> a3m_element_type_name.etns_shell_based_wireframe_model );
    wr9: ( SELF <> a3m_element_type_name.etns_vertex_point );
  END_TYPE; -- a3ma_element_type_name (line:340 file:ap242ed4_mim_lf_TY.exp)

*/

//MARK: - Defined data type (type alias)

/** Defined data type (type alias)
- EXPRESS source code:
```express
  TYPE a3ma_element_type_name = a3m_element_type_name;
  WHERE
    wr1: ( SELF <> a3m_element_type_name.etns_connected_edge_set );
    wr2: ( SELF <> a3m_element_type_name.etns_connected_face_set );
    wr3: ( SELF <> a3m_element_type_name.etns_external_representation_item );
    wr4: ( SELF <> a3m_element_type_name.etns_manifold_solid_brep );
    wr5: ( SELF <> a3m_element_type_name.etns_others );
    wr6: ( SELF <> a3m_element_type_name.etns_point_cloud_dataset );
    wr7: ( SELF <> a3m_element_type_name.etns_shell_based_surface_model );
    wr8: ( SELF <> a3m_element_type_name.etns_shell_based_wireframe_model );
    wr9: ( SELF <> a3m_element_type_name.etns_vertex_point );
  END_TYPE; -- a3ma_element_type_name (line:340 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public struct nA3MA_ELEMENT_TYPE_NAME: TypeHierarchy.nA3MA_ELEMENT_TYPE_NAME__TypeBehavior {
    public typealias Supertype = nA3M_ELEMENT_TYPE_NAME
    public typealias FundamentalType = Supertype.FundamentalType
    public typealias Value = Supertype.Value
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3MA_ELEMENT_TYPE_NAME"
    public static let bareTypeName: String = "A3MA_ELEMENT_TYPE_NAME"
    public var typeMembers: Set<SDAI.STRING> {
      var members = rep.typeMembers
      members.insert(SDAI.STRING(Self.typeName))
      return members
    }

    public var rep: Supertype
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) {
      rep = Supertype(fundamental: fundamental)
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let repval = Supertype.convert(fromGeneric: generic) else { return nil }
      rep = repval
    }

    //MARK: WHERE RULES (DEFINED TYPE)
    public static func WHERE_wr1(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_CONNECTED_EDGE_SET
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr2(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_CONNECTED_FACE_SET
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr3(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_EXTERNAL_REPRESENTATION_ITEM
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr4(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_MANIFOLD_SOLID_BREP
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr5(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_OTHERS
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr6(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_POINT_CLOUD_DATASET
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr7(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_SHELL_BASED_SURFACE_MODEL
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr8(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_SHELL_BASED_WIREFRAME_MODEL
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr9(SELF: nA3MA_ELEMENT_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* nA3M_ELEMENT_TYPE_NAME?? */ = nA3M_ELEMENT_TYPE_NAME.ETNS_VERTEX_POINT
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }

    //WHERE RULE VALIDATION (DEFINED TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      let prefix2 = prefix + "\\nA3MA_ELEMENT_TYPE_NAME"
      var result = Supertype.validateWhereRules(instance:instance?.rep, prefix:prefix2)

      result[prefix2 + ".WHERE_wr1"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr1(SELF: instance)
      result[prefix2 + ".WHERE_wr2"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr2(SELF: instance)
      result[prefix2 + ".WHERE_wr3"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr3(SELF: instance)
      result[prefix2 + ".WHERE_wr4"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr4(SELF: instance)
      result[prefix2 + ".WHERE_wr5"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr5(SELF: instance)
      result[prefix2 + ".WHERE_wr6"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr6(SELF: instance)
      result[prefix2 + ".WHERE_wr7"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr7(SELF: instance)
      result[prefix2 + ".WHERE_wr8"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr8(SELF: instance)
      result[prefix2 + ".WHERE_wr9"] = nA3MA_ELEMENT_TYPE_NAME.WHERE_wr9(SELF: instance)
      return result
    }

  }
}


//MARK: - DEFINED TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nA3MA_ELEMENT_TYPE_NAME__TypeBehavior: nA3M_ELEMENT_TYPE_NAME__Subtype {}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nA3MA_ELEMENT_TYPE_NAME__Subtype: nA3MA_ELEMENT_TYPE_NAME__TypeBehavior
{}
}

