/* file: a3ms_inspected_equivalence_element_select.swift 	 generated: Sun Mar  1 18:06:18 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.1.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE a3ms_inspected_equivalence_element_select = inspected_equivalence_element_select;
  WHERE
    wr1: ( NOT ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PRODUCT_DEFINITION_OR_REFERENCE' IN 
             TYPEOF( SELF ) ) );
    wr2: ( NOT ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_REPRESENTATION' IN TYPEOF( SELF ) ) );
  END_TYPE; -- a3ms_inspected_equivalence_element_select (line:389 file:ap242ed4_mim_lf_TY.exp)

*/

//MARK: - Defined data type (type alias)

/** Defined data type (type alias)
- EXPRESS source code:
```express
  TYPE a3ms_inspected_equivalence_element_select = inspected_equivalence_element_select;
  WHERE
    wr1: ( NOT ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PRODUCT_DEFINITION_OR_REFERENCE' IN 
             TYPEOF( SELF ) ) );
    wr2: ( NOT ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_REPRESENTATION' IN TYPEOF( SELF ) ) );
  END_TYPE; -- a3ms_inspected_equivalence_element_select (line:389 file:ap242ed4_mim_lf_TY.exp)

```
*/
  public struct sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT: TypeHierarchy.sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT__TypeBehavior {
    public typealias Supertype = sINSPECTED_EQUIVALENCE_ELEMENT_SELECT
    public typealias FundamentalType = Supertype.FundamentalType
    public typealias Value = Supertype.Value
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT"
    public static let bareTypeName: String = "A3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT"
    public var typeMembers: Set<SDAI.STRING> {
      var members = rep.typeMembers
      members.insert(SDAI.STRING(Self.typeName))
      //SELECT data types (indirectly) referencing the current type as a member of the select list
      members.insert(SDAI.STRING(sEQUIVALENCE_DETECTED_DIFFERENCE_SELECT.typeName)) // -> Self
      return members
    }

    public var rep: Supertype
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) {
      rep = Supertype(fundamental: fundamental)
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let repval = Supertype.convert(fromGeneric: generic) else { return nil }
      rep = repval
    }

    //MARK: WHERE RULES (DEFINED TYPE)
    public static func WHERE_wr1(SELF: sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( SELF, IS: sPRODUCT_DEFINITION_OR_REFERENCE.self )
      let _TEMP2 /* SDAI.LOGICAL */ =  !_TEMP1
      return _TEMP2
    }
    public static func WHERE_wr2(SELF: sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }
      //
      let _TEMP1 /* SDAI.LOGICAL */ = SDAI.TYPEOF( SELF, IS: eSHAPE_REPRESENTATION.self )
      let _TEMP2 /* SDAI.LOGICAL */ =  !_TEMP1
      return _TEMP2
    }

    //WHERE RULE VALIDATION (DEFINED TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      let prefix2 = prefix + "\\sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT"
      var result = Supertype.validateWhereRules(instance:instance?.rep, prefix:prefix2)

      result[prefix2 + ".WHERE_wr1"] = sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT.WHERE_wr1(SELF: instance)
      result[prefix2 + ".WHERE_wr2"] = sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT.WHERE_wr2(SELF: instance)
      return result
    }

  }
}


//MARK: - DEFINED TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT__TypeBehavior: 
  sINSPECTED_EQUIVALENCE_ELEMENT_SELECT__Subtype {}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT__Subtype: 
  sA3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT__TypeBehavior
{}
}

