/* file: a3ms_detected_difference_type_name.swift 	 generated: Wed Feb 25 18:12:04 2026 */

/* This file was generated by the EXPRESS to Swift translator "exp2swift", 
  derived from STEPcode (formerly NIST's SCL).
 exp2swift version: v.2.0.0, derived from stepcode v0.8 as of 2019/11/23 
 WARNING: You probably don't want to edit it since your modifications 
  will be lost if exp2swift is used to regenerate it.
 */

 
import SwiftSDAIcore

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF {
//MARK: -TYPE DEFINITION in EXPRESS
/*
  TYPE a3ms_detected_difference_type_name = a3m_detected_difference_type_name;
  WHERE
    wr1 : ( SELF <> a3m_detected_difference_type_name.ddna_a3ms_inspected_equivalence_element_select );
    wr2 : ( SELF <> a3m_detected_difference_type_name.ddna_assembly_component_usage );
    wr3 : ( SELF <> a3m_detected_difference_type_name.ddna_binary_assembly_constraint );
    wr4 : ( SELF <> a3m_detected_difference_type_name.ddna_cartesian_point );
    wr5 : ( SELF <> a3m_detected_difference_type_name.ddna_context_dependent_shape_representation );
    wr6 : ( SELF <> a3m_detected_difference_type_name.ddna_count_measure );
    wr7 : ( SELF <> a3m_detected_difference_type_name.ddna_multi_level_reference_designator );
    wr8 : ( SELF <> a3m_detected_difference_type_name.ddna_no_element );
    wr9 : ( SELF <> a3m_detected_difference_type_name.ddna_others );
    wr10: ( SELF <> a3m_detected_difference_type_name.ddna_volume_measure );
  END_TYPE; -- a3ms_detected_difference_type_name (line:358 file:ap242ed4_mim_lf.exp)

*/

//MARK: - Defined data type (type alias)

/** Defined data type (type alias)
- EXPRESS source code:
```express
  TYPE a3ms_detected_difference_type_name = a3m_detected_difference_type_name;
  WHERE
    wr1 : ( SELF <> a3m_detected_difference_type_name.ddna_a3ms_inspected_equivalence_element_select );
    wr2 : ( SELF <> a3m_detected_difference_type_name.ddna_assembly_component_usage );
    wr3 : ( SELF <> a3m_detected_difference_type_name.ddna_binary_assembly_constraint );
    wr4 : ( SELF <> a3m_detected_difference_type_name.ddna_cartesian_point );
    wr5 : ( SELF <> a3m_detected_difference_type_name.ddna_context_dependent_shape_representation );
    wr6 : ( SELF <> a3m_detected_difference_type_name.ddna_count_measure );
    wr7 : ( SELF <> a3m_detected_difference_type_name.ddna_multi_level_reference_designator );
    wr8 : ( SELF <> a3m_detected_difference_type_name.ddna_no_element );
    wr9 : ( SELF <> a3m_detected_difference_type_name.ddna_others );
    wr10: ( SELF <> a3m_detected_difference_type_name.ddna_volume_measure );
  END_TYPE; -- a3ms_detected_difference_type_name (line:358 file:ap242ed4_mim_lf.exp)

```
*/
  public struct nA3MS_DETECTED_DIFFERENCE_TYPE_NAME: TypeHierarchy.nA3MS_DETECTED_DIFFERENCE_TYPE_NAME__TypeBehavior {
    public typealias Supertype = nA3M_DETECTED_DIFFERENCE_TYPE_NAME
    public typealias FundamentalType = Supertype.FundamentalType
    public typealias Value = Supertype.Value
    public static let typeName: String = 
      "AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.A3MS_DETECTED_DIFFERENCE_TYPE_NAME"
    public static let bareTypeName: String = "A3MS_DETECTED_DIFFERENCE_TYPE_NAME"
    public var typeMembers: Set<SDAI.STRING> {
      var members = rep.typeMembers
      members.insert(SDAI.STRING(Self.typeName))
      return members
    }

    public var rep: Supertype
    /// initialize from the fundamental type value
    public init(fundamental: FundamentalType) {
      rep = Supertype(fundamental: fundamental)
    }

    /// initialize from SDAI generic type value
    public init?<G: SDAI.GenericType>(fromGeneric generic: G?) {
      guard let repval = Supertype.convert(fromGeneric: generic) else { return nil }
      rep = repval
    }

    //MARK: WHERE RULES (DEFINED TYPE)
    public static func WHERE_wr1(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_A3MS_INSPECTED_EQUIVALENCE_ELEMENT_SELECT
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr2(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_ASSEMBLY_COMPONENT_USAGE
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr3(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_BINARY_ASSEMBLY_CONSTRAINT
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr4(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_CARTESIAN_POINT
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr5(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_CONTEXT_DEPENDENT_SHAPE_REPRESENTATION
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr6(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_COUNT_MEASURE
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr7(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_MULTI_LEVEL_REFERENCE_DESIGNATOR
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr8(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_NO_ELEMENT
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr9(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_OTHERS
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }
    public static func WHERE_wr10(SELF: nA3MS_DETECTED_DIFFERENCE_TYPE_NAME?) -> SDAI.LOGICAL {
      guard let SELF = SELF else { return SDAI.UNKNOWN }

      let _TEMP1 /* nA3M_DETECTED_DIFFERENCE_TYPE_NAME?? */ = nA3M_DETECTED_DIFFERENCE_TYPE_NAME.DDNA_VOLUME_MEASURE
      let _TEMP2 /* SDAI.LOGICAL */ = SDAI.FORCE_OPTIONAL(SELF) .!=. SDAI.FORCE_OPTIONAL(_TEMP1)
      return _TEMP2
    }

    //WHERE RULE VALIDATION (DEFINED TYPE)
    public static func validateWhereRules(instance:Self?, prefix:SDAI.WhereLabel) -> SDAI.WhereRuleValidationRecords {
      let prefix2 = prefix + "\\nA3MS_DETECTED_DIFFERENCE_TYPE_NAME"
      var result = Supertype.validateWhereRules(instance:instance?.rep, prefix:prefix2)

      result[prefix2 + ".WHERE_wr1"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr1(SELF: instance)
      result[prefix2 + ".WHERE_wr2"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr2(SELF: instance)
      result[prefix2 + ".WHERE_wr3"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr3(SELF: instance)
      result[prefix2 + ".WHERE_wr4"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr4(SELF: instance)
      result[prefix2 + ".WHERE_wr5"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr5(SELF: instance)
      result[prefix2 + ".WHERE_wr6"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr6(SELF: instance)
      result[prefix2 + ".WHERE_wr7"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr7(SELF: instance)
      result[prefix2 + ".WHERE_wr8"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr8(SELF: instance)
      result[prefix2 + ".WHERE_wr9"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr9(SELF: instance)
      result[prefix2 + ".WHERE_wr10"] = nA3MS_DETECTED_DIFFERENCE_TYPE_NAME.WHERE_wr10(SELF: instance)
      return result
    }

  }
}


//MARK: - DEFINED TYPE HIERARCHY
extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nA3MS_DETECTED_DIFFERENCE_TYPE_NAME__TypeBehavior: 
  nA3M_DETECTED_DIFFERENCE_TYPE_NAME__Subtype {}
}

extension AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.TypeHierarchy {
 public protocol nA3MS_DETECTED_DIFFERENCE_TYPE_NAME__Subtype: 
  nA3MS_DETECTED_DIFFERENCE_TYPE_NAME__TypeBehavior
{}
}

